### ISSUE TITLE
Possible to make this work with React Native?

### ISSUE THREAD

**Issue by henrikra** [jeffijoe/awilix#104]
I am using this cool library in Node but can it be used in React Native. Because I tried it and I am getting errors from babel plugins and you are also requiring `path` module in awilix etc :(

**Comment by jeffijoe** [comment]
You should be able to if you import `lib/awilix.browser.js`, it has all the Node-specific stuff stripped out.

**Comment by jeffijoe** [comment]
@henrikra please let me know whether it works so I can close 😀

**Comment by henrikra** [comment]
How do you import that on TS project?
If I do it like this TS says it doesn't exist `import awilix from 'awilix/lib/awilix.browser.js';`
same thing with this `import awilix from 'awilix/lib/awilix.browser';`

Can you try also?

**Comment by henrikra** [comment]
With `import awilix from 'awilix/lib/awilix.browser';` it finds the module but TS is says it doesn't exist so I guess you need to add types for those too.

But even with browser build it is complaining that I don't have `transform-runtime` babel plugin

**Comment by jeffijoe** [comment]
Awilix does not use Babel at all, so that must be originating elsewhere.

I think React Native ships with Babel per default; perhaps you can use a plugin to rewrite the import path?

**Comment by henrikra** [comment]
Yeah React Native projects are using babel.
Hmm looks like is coming from Awilix package.json https://github.com/jeffijoe/awilix/blob/master/package.json#L95 🤔

**Comment by jeffijoe** [comment]
I would, but afraid I can't right now.

To me it sounds like a bug in Metro, RN's bundler. If something is ignored by Babel, it _shouldn't try to transform it or load it's config_.

**Comment by jeffijoe** [comment]
@henrikra I just installed the latest React Native, did `react-native init`, added TS, installed `babel-plugin-module-resolver` and modified my `.babelrc` like so:

```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": [
    [
      "module-resolver",
      {
        "alias": {
          "awilix": "awilix/lib/awilix.browser"
        }
      }
    ]
  ]
}
```

Here is `App.tsx`:

```tsx
import React, { Component } from "react";
import { createContainer, asFunction, asValue, InjectionMode } from "awilix";
import { Platform, StyleSheet, Text, View } from "react-native";

function createGreeter(platform: string): Greeter {
  return {
    greet() {
      return `Hi React Native on ${platform} from Awilix!`;
    }
  };
}

const container = createContainer({ injectionMode: InjectionMode.CLASSIC });
container.register({
  greeter: asFunction(createGreeter),
  platform: asValue(
    Platform.select({
      android: "Android",
      ios: "iOS"
    })
  )
});

interface Greeter {
  greet(): string;
}

export default class App extends Component<any> {
  render() {
    const greeter = container.resolve<Greeter>("greeter");
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>{greeter.greet()}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10
  }
});
```

And the proof in the pudding:

![image](https://user-images.githubusercontent.com/2505474/46916313-04217100-cfb9-11e8-8261-d8d3bb5434b4.png)

**Comment by henrikra** [comment]
I don't know how much you have done React @jeffijoe but do you think we could replace Hocs with Awilix DI? https://reactjs.org/docs/higher-order-components.html

**Comment by jeffijoe** [comment]
You probably can.

**Comment by henrikra** [comment]
Still having error with babel env plugin. When I removed this from awilix package.json then I could get it to run with v4
```
"babel": {
    "presets": [
      [
        "env",
        {
          "targets": {
            "browsers": "last 2 versions",
            "node": "6.0.0"
          }
        }
      ]
    ]
  }
```

**Comment by jeffijoe** [comment]
Using an older RN version?

**Comment by henrikra** [comment]
I am using RN 0.54.4

**Comment by henrikra** [comment]
If you want to try by yourself you can make new project with specific RN version like this `react-native init --version 0.54.4`

**Comment by jeffijoe** [comment]
So this definitely sounds like a bug in RN/Metro Bundler which appears to have been fixed. The project I had tested on was brand-new with no extra packages but Awilix, which worked fine with no modifications.

I would suggest just installing `babel-preset-env` until you are able to upgrade your React Native.

**Comment by henrikra** [comment]
Btw I just ran this code on Android and it doesnt work. But on iOS it works. Did this work on Android for you?

**Comment by jeffijoe** [comment]
I didn’t try running it on Android.

**Comment by henrikra** [comment]
Can you try running on Android and see if it runs for you?

**Comment by jeffijoe** [comment]
Not right now, but if you tell me what error you’re getting using the latest RN I might be able to help.

**Comment by henrikra** [comment]
Now I have run your code and it works on iOS but Android it throws this error:
![image](https://user-images.githubusercontent.com/12229968/50426784-b15d1300-089f-11e9-8234-9991ec1d346a.png)

**Comment by henrikra** [comment]
What do you think is proper fix for this?

**Comment by jeffijoe** [comment]
User-land polyfill until Android catches up. Might be possible to transpile?

**Comment by henrikra** [comment]
But do you mean that this library should include that polyfill like mobx has done https://github.com/mobxjs/mobx-react/pull/499 ?

**Comment by jeffijoe** [comment]
That seems simple enough, so why not. 😀

**Comment by henrikra** [comment]
What is the use case btw for symbols in this project? I haven't used them before 🤔

**Comment by jeffijoe** [comment]
They are used for private non-enumerated props. 😀

**Comment by henrikra** [comment]
Looks like there is another problem. Now I added `import 'core-js/es6/symbol';` to the top of the file which polyfills `Symbol`. Now I get this error

![image](https://user-images.githubusercontent.com/12229968/50445932-a5626700-091a-11e9-8ca6-6c88dd3d9298.png)

**Comment by jeffijoe** [comment]
Awilix uses proxy for one of its injection modes, so if you just add an empty proxy constructor then it shouldn’t error.

**Comment by henrikra** [comment]
To where? Can you please give example? :)

**Comment by jeffijoe** [comment]
If you just add a `global.Proxy = function() {}` before creating the container, it shouldn't error. You can only use `InjectionMode.CLASSIC` though. Proxy isn't something you can polyfill 100% correctly IIRC.

**Comment by henrikra** [comment]
Hmm but then I cannot minify the code? Because usually on client apps you want to minify the bundle so they don't have to download so much stuff

**Comment by jeffijoe** [comment]
Yes, for browsers, but most browsers support these things, while it seems whatever JS engine RN uses on Android does not. You don't need to minify your RN bundle since it's only downloaded once on install.

**Comment by jeffijoe** [comment]
But even if you still wanted to minify, you can disable the option to mangle parameter names.
