### ISSUE TITLE
decorator support wanted

### ISSUE THREAD

**Issue by mysyljr** [jeffijoe/awilix#106]
Can we provide the function to support this style?
```javascript
@Injector
class AService{
  @Inject
  bService
}
```

**Comment by jeffijoe** [comment]
It's possible but I don't want to add this in core.

You could do this with a custom resolver. 😀

**Comment by jeffijoe** [comment]
Closing as this is something that can be done using a custom resolver which could/should be it's own library in order to avoid bloating Awilix core.
