### ISSUE TITLE
Classic injection with extending class

### ISSUE THREAD

**Issue by mathieug** [jeffijoe/awilix#107]
```typescript
import { createContainer, InjectionMode, asClass } from 'awilix';

class Db {
  constructor() {
    console.log('Db', arguments);
  }
}

abstract class Parent {
  constructor(db) {
    console.log('Parent', arguments);
  }
}

class Child1 extends Parent {}

class Child2 extends Parent {
  constructor(db) {
    super(db);
  }
}

const container = createContainer({ injectionMode: InjectionMode.CLASSIC });

container.register('db', asClass(Db));
container.register('child1', asClass(Child1).singleton());
container.register('child2', asClass(Child2).singleton());

console.log('Resolve child1:');
container.resolve<Child1>('child1');
console.log('----');
console.log('Resolve child2:');
container.resolve<Child2>('child2');
```

Output is
```
Resolve child1:
Parent [Arguments] {}
----
Resolve child2:
Db [Arguments] {}
Parent [Arguments] { '0': Db {} }
```

**Comment by jeffijoe** [comment]
Labeling as enhancement. Need to investigate the ability to extract inheritance chain code to parse.

* If it's a class and it has no constructor, and it has an extends clause.. (only works for native classes, not transpiled ones!)
* Or if it has a constructor which calls `super(...arguments)`

Then we can parse the parent and inject those.

**Comment by jeffijoe** [comment]
@mathieug the approach I came up with did not require changes to the parser, and also supports non-ES6 classes. As long as `Object.getPrototypeOf` works with whatever class system you're using, then Awilix will happily follow the chain until it finds a base class with declared parameters.

This will be released as 4.1.0 sometime soon.

**Comment by jeffijoe** [comment]
v4.1.0 has been released! 🎉

**Comment by ShaunEgan** [comment]
Thanks for this, it saved my bacon!

**Comment by aleho** [comment]
@jeffijoe Sorry for the spam, but an emoticon doesn't quite say it all, so: Thanks for the great work! You're awesome!

**Comment by jeffijoe** [comment]
The best kind of spam! ❤️ 

Really appreciate it!
