### ISSUE TITLE
Proposal to enhance the DI Container with dependency injection based on name

### ISSUE THREAD

**Issue by cjhoward92** [jeffijoe/awilix#11]
The current DI Container works, but it is using a common anti-pattern called the [Service Locator](http://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/). 

I was wondering your thoughts on adding a configuration option to enhance the container to read functions and classes for their dependencies based on explicit name. Something like so:

```javascript
container.register({
  dep1: asFunction(makeDep1)
  dep2: asFunction(makeDep2)
})

function makeDep1() {
  function do() { }
  return { do }
}

function makeDep2(dep1) {
  function useDep1() {
    dep1.do();
  }
}
```

Where `makeDep2` would automatically have an instance of `dep1` injected into it because the container recognizes that `dep1` is a registered dependency.

We could easily inspect function and constructor calls for strictly named dependencies and save the required dependencies in the registration object by name.

The advantage to this is that I will know exactly what is being used by a class or function based on the arguments. This is nice for testing, and it makes the dependencies more explicit, which is good.

The issues come into play with minification. If someone wants to minify to take advantage of V8 function inlining or something then the naming conventions would break. We could either tell the users, "Hey, minification will break your app in this configuration" or offer something like Aurelia or Angular where they have special functions and/or string based dependency names to avoid minification issues.

If you like the idea I can try and draft a legitimate proposal and potential write some prototype code to start with. I'd have no problem contributing to this container, I think it has promise!

**Comment by jeffijoe** [comment]
I've been thinking about this as well.

Technically yes, the current approach could be seen as a service locator, but you really should dereference your dependencies in the constructor:

```
function makeDep2({ dep1 }) {
  return {
    useDep1 () {
      return dep1.do()
    }
  }
}
```

Because when you call it during a test, you know exactly what you are supplying:

```
const subject = makeDep2({
  dep1: dep1Mock
}) 
```

Also, passing in more than 5 parameters to a function in JS is also [considered an anti-pattern](http://stackoverflow.com/questions/23890771/too-many-arguments-in-object-containing-functions-anti-pattern) - Awilix embraces the "configuration object" pattern.

Additionally (for testing purposes at least), having to supply the arguments in an exact order can cause headaches.

With that being said, I would definitely be open to supporting it through a configuration option! I think it should be configurable on the container *as well as per-registration*, to be able to mix-and-match as you see fit.

Feel free to hack away a prototype and draft your proposal!

**Comment by cjhoward92** [comment]
I did not know you could dereference in a constructor (or function), that is nice!

As for the 5 parameters rule, I would say that is an anti-pattern in most languages. I would argue more than 4-5 dependencies on any function or class should warrant potential refactoring, but I guess that is a subjective view and this is not the place for that argument haha.

I will play around. When I have something substantial I will let you know!

Thanks for the quick response.

**Comment by jeffijoe** [comment]
If you're using ES6, the destructuring is where it's at! 😄

**Comment by jeffijoe** [comment]
Also, as an aside to your minification concern; minifiers today are smart enough to know what they can safely minify and what they cannot. If they can't trace the calls to your own code they leave the names alone.

**Comment by cjhoward92** [comment]
I would have hoped that would be the case, but I wasn't sure. Good to know!

**Comment by jeffijoe** [comment]
Come to think about it, the way Awilix works today is pretty reliant on the fact that you "pull" the values out of the _cradle_ at construction time, so you might have to wrap constructors/functions to pull them out at the right time.

**Comment by cjhoward92** [comment]
I will take that into account. I have not studied the resolution algorithm in depth quite yet. A wrapper or deferred execution pipeline won't be too hard to implement, I don't think. I just want to find a nice way to integrate it in without being too *hacky*.

**Comment by jeffijoe** [comment]
Good luck!

**Comment by jeffijoe** [comment]
Hey @cjhoward92 any updates? Or should I just close this?

**Comment by cjhoward92** [comment]
Sorry about that. I got preoccupied with work and then we ended up changing dependency management methods so I never got around to it. You can close it. If I ever do give it a shot I will let you know.

Thanks!

**Comment by jeffijoe** [comment]
No problem :+1:

**Comment by cjhoward92** [comment]
I know we closed this a while ago, but I just did it for fun. I finally got everything working. If you would like to see what I have, checkout [this branch](https://github.com/cjhoward92/awilix/tree/regex). The only issue I have is that the linter fails when I construct classes with multiple dependencies because it expects `()` after a constructor, which does not happen there. See [this line](https://github.com/cjhoward92/awilix/blob/regex/lib/registrations.js#L156). Otherwise I have 100% coverage and all that. Plus I updated the README.

Let me know what you think! Checkout the tests in the `registrations.spec.js` for examples!

**Comment by cjhoward92** [comment]
I have a question too, what happens when we pass `null` or `undefined` into the `asClass` or `asFunction` routines? If, for some reason, the consumer does this we have a problem. I do not see any guard code to prevent this, but I may be missing something.

**Comment by jeffijoe** [comment]
@cjhoward92 nice work!

I read the note about backwards compatibility, but come to think about it; if you're not aware of that little "quirk", the behavior might seem odd. One option would be to have a container-wide option on what style to use: **classic** or **proxy**.

**Classic** (the one you just implemented) would be the more _strict_ version, since you are forced to dereference your dependencies when you receive them.

**Proxy** (the original way) would be more _loose_, since nothing is stopping you from just saving a reference to the cradle for use later. _Saving it for later_ goes against DI principles, but it has it uses, for example supporting circular dependencies **when you absolutely need it**:

```js
class Logger {
  constructor (opts) {
    this.opts = opts
  }
  
  get emailService () {
    return this.opts.emailService
  }
  
  log (level, message) {
    console.log(level, message)
    if (level === 'ERROR') {
      // E-mail service resolved just-in-time
      this.emailService.send('admin@icescreamyouscream.com', 'New Error Message', message)
    }
  }
}

class EmailService {
  constructor ({ logger }) {
    this.logger = log
  }
  
  send (to, subject, body) {
    this.logger.log('DEBUG', 'Sending e-mail')
    // ..
  }
}
```

---

Regarding the `as*` methods, you're absolutely right, they need guard assertions. I created #20 for this.

**Comment by cjhoward92** [comment]
I like the global configuration idea a lot. I think it definitely solves the weird quirk of dealing with the cradle when you have a single non-resolvable dependency. I will add that to my changes and submit a PR.

**Comment by jeffijoe** [comment]
Before you do too much work, throw a few API suggestions in here so we can decide on what it should look like.

It could be a global default + a per-registration option (for auto-loading as well)

**Comment by cjhoward92** [comment]
Okay, sounds good. 

I was thinking we can have an option called `mode` or `resolutionMode` on the global container options. This would be copied to the container instance where it would default to `'Proxy'` if it was not set by the user. 

On each resolution it would just read the mode present on the container and do it's thing.

```javascript
// Defined in the registrations.js
ResolutionModes = Object.freeze({
  PROXY: 'Proxy',
  CLASSIC: 'Classic'
})

// Used by the user
awilix.createContainer({
  mode: ResolutionModes.PROXY
})

// In the registration routines
let resolve
if (container.__mode === ResolutionModes.PROXY) {
  resolve = // some function...
} else {
  resolve = // other function...
}
```

You may have a better format, though. As for per-registration overrides, I didn't think about that. Where/how would that be best managed? Should we inject the mode from the `options` into the `as*` functions unless the user specifies one?

```javascript
// Uses container option
container.register({
  func: asFunction(() => {})
})

// Uses registration override
container.register({
  func: asFunction(() => {}, { mode: ResolutionModes.PROXY })
})
```

Thoughts?

**Comment by jeffijoe** [comment]
Yeah I like `resolutionMode`. Use `ResolutionMode` as the namespace for the values.

Both of these should be supported (and is already with Lifetime):

```js
// Boring
container.register({
  func: asFunction(
    () => {}, 
    { lifetime: Lifetime.SINGLETON, resolutionMode: ResolutionMode.CLASSIC }
  )
})

// Fluid
container.register({
  // Super fluid
  func: asFunction(() => {}).singleton().classic(),
  // Regular fluid
  cls: asClass(MyClass)
    .setLifetime(Lifetime.SINGLETON)
    .setResolutionMode(ResolutionModes.PROXY),
})

// Auto-loading
container.loadModules([
  ['services/*.js', Lifetime.SCOPED], // Lifetime shorthand
  ['repositories/*.js', {
    // Full-blown config
    lifetime: Lifetime.SINGLETON, 
    resolutionMode: ResolutionMode.CLASSIC 
  }]
])
```

**Comment by cjhoward92** [comment]
That all looks good. I will get to work! Any other thoughts or comments before I get too far into it?

**Comment by jeffijoe** [comment]
Only thing I can think of is make sure your regex works for transpiled code. IIRC, some transpilers will rename parameters but maybe I'm wrong. It's worth looking into.

**Comment by cjhoward92** [comment]
I will run some TypeScript tests to verify.

**Comment by jeffijoe** [comment]
Babel and TypeScript for sure!

**Comment by cjhoward92** [comment]
How do you want me to test Babel and TypeScript? Right now I have an example project in the examples folder that compile the typescript and runs the output. It appears to be working fine. I am not sure if there is a "better way" to do it, though.

**Comment by jeffijoe** [comment]
Yeah thats good enough. If people are having trouble they can use Proxy mode. 😀

**Comment by cjhoward92** [comment]
Haha sounds good to me!

**Comment by jeffijoe** [comment]
Implemented by @cjhoward92 - great work!
