### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by rafamedina** [jeffijoe/awilix#113]
Hi

I'm creating the container using mongoose, well

```
const mongoose = require('mongoose');
mongoose.Promise = global.Promise
```

and the registration

```
mongoose: asFunction(() => mongoose).singleton()
```

I also have my database file

```
module.exports = ({ mongoose, dbSettings }) => {
   const connect = () => { ... }
   return { connect }
}
```

with this register
```
db: asFunction(() => database).singleton()
```

The problem is when the database object is resolve and invoke the connect method throws the error "Cannot read property 'mongoose' of undefined'
If I show up the output from the resolve('mongoose'), it is there.

Any idea about I'm missing?

Thanks

**Comment by jeffijoe** [comment]
If database is the function, then asFunction(database) is what you need.

Also, you can use asValue(mongoose)

**Comment by rafamedina** [comment]
I worked. Thank you so much

The point is you can register them with the wrong type (asValue, asFunction, asClass) and we you want to use the function/class, it doesn't "receive" the magic hehehe in the constructor.
