### ISSUE TITLE
InjectionMode.CLASSIC without parsing

### ISSUE THREAD

**Issue by BrandonLWhite** [jeffijoe/awilix#114]
I'd like to use CLASSIC injection mode but without the function parsing and instead manually specify the dependencies to inject (eg via an array of strings).

At present, it seems that Awilix CLASSIC mode only supports the "Implicit Annotation" style (to borrow from AngularJS vocabulary).  This is certainly more automatic, and I get why people like it.  There's the standard 'not compatible with minification' disclaimer of course.

I'm interested in using an explicit annotation style, where the dependencies are manually declared.  This would be similar to AngularJS 'Inline Array Annotation' in concept.

How would I go about achieving this "CLASSIC_EXPLICIT" injection mode?

**Comment by BrandonLWhite** [comment]
An alternative that I think would be just as good (perhaps better?) is PROXY mode but with explicit dependency declaration. So this would mean that you still get one proxy object passed to the function/ctor but instead of being a full-blown Service Locator :( it is an object with only the dependencies you've declared :)  And they are resolved at that time.

This would promote the nice destructuring syntax for function args but without the issue of the Service Locator where the instance can be saved for later and any arbitrary module accessed at a later time.

So now, after pondering this a little more, I'm thinking Awilix would benefit from having a way to use explicit dependency declarations for both CLASSIC and PROXY mode.  CLASSIC_EXPLICIT and PROXY_EXPLICIT if you will.

**Comment by BrandonLWhite** [comment]
Great, thanks for the direction!

**Comment by jeffijoe** [comment]
No problem! Peek at the implementation of the other resolvers and pick whatever you need. Awilix' resolver system was built for pulling off tricks like this without requiring any changes to core. Others have done some pretty fun things like grouping up services into a facade using a resolver, caching instances for a specific amount of time, etc.

Have fun! 🙌
