### ISSUE TITLE
Node 10 - resolver.resolve is not a function with any example used in documentation

### ISSUE THREAD

**Issue by jordantogether** [jeffijoe/awilix#117]
Hi,

It looks like there's some stuff missing in the documentation about supplying parameters. When I used the example, with a service which required parameters, the service did not load and would not be retrieved when calling `container.resolve`. 

When I use `loadModules`, I still get this error, no matter what I do: 

```javascript
// MyService.js
const {
    RESOLVER
} = require('awilix');

class MyService {
 constructor({ x, y}) {
  // ...
}
}

MyService[RESOLVER] = {};

module.exports = {
    default: MyService,
    MyService,
}

// Container.js
const {
    createContainer,
    asClass,
    Lifetime,
    InjectionMode,
} = require('awilix');

// An object containing the parameters passed to register()
const appConf = require("./app.conf");

const {
    LuisService
} = require('./../services/LUISService');

// Create the container to be injected.
const serviceContainer = createContainer();

serviceContainer.register({
    ...appConf,
});


serviceContainer.loadModules([
    `services/*.js`,
], {
    formatName: 'camelCase',
});

var x = serviceContainer.resolve('myService'); // resolver.resolve is not a function.
```

No matter which of the examples I use, I can't get this to work. Registering the services individually doesn't work, passing in an object to the loadModules first array parameter doesn't work (containing settings to say `asClass` and to use `PROXY` as the method of resolving parameters), so I'm quite stumped to be honest. 

OS: Windows 10
Node Version: 10.0.0
Awilix Version: 4.1.0

**Comment by jeffijoe** [comment]
In your example you are not exporting anything?

**Comment by jeffijoe** [comment]
And that works right?

**Comment by jordantogether** [comment]
Nope, does not work, unfortunately. I mean, I forgot to add that to the example above.

**Comment by jeffijoe** [comment]
Can you provide a zip with a repro? I’m certain its a misconfig 😀

**Comment by jordantogether** [comment]
> Better yet, compare against the examples in this repo 😄

I have, but unfortunately they don't work. I have used the koa and simple example, and they aren't retrieving the service. I'll just hack until I get it, close the ticket please :)

**Comment by jeffijoe** [comment]
If you share a repo where it breaks Im happy to take a look 😀

**Comment by jordantogether** [comment]
I figured it out. So for me, the use of "repository" was a little bit confusing, because there's no explanation of what it's intended for, but I can infer it now from a bit more research. 

The cause is passing in values to `.register` that aren't wrapped with `asValue`. Doing that resolves the issue, or using the repository also works - my bad 🐺
