### ISSUE TITLE
Remove specific registrations by key

### ISSUE THREAD

**Issue by faustbrian** [jeffijoe/awilix#118]
Is there any way to remove a value in the container based on its key instead of having to recreate a new container without the value? Something like `container.dispose('userRepository')`.

**Comment by jeffijoe** [comment]
What’s the use case?

**Comment by jeffijoe** [comment]
Sounds like a use case for scopes?

**Comment by faustbrian** [comment]
Guess I will use scopes for now, just feels a bit odd rather then simply removing an entry. Thanks 👍
