### ISSUE TITLE
Preserving TS types?

### ISSUE THREAD

**Issue by alekbarszczewski** [jeffijoe/awilix#122]
Hey, first of all thanks for great package - I love it!

I was wondering if it would be possible to preserve container services types in TS. Right now AFAIK to preserve types you have to resolve like this `container.resolve<MyService>('myService').doSomething()`. And if you will make typo in `'myService'` TS won't complain...

Consider this example:

```ts
interface ContainerDef {
  [key: string]: new (...args: any[]) => any;
}

class Container<T extends ContainerDef> {
  constructor(private containerDef: T) {}

  public resolve<K extends keyof T>(key: K): InstanceType<T[K]> {
    const Cls = this.containerDef[key];
    return new Cls();
  }
}

class MyService {
  public doSomething(): void {}
}

const container = new Container({
  myService: MyService,
});

const myService = container.resolve('myService').doSomething(); // <-- types are preserved without type "casting"
// instead of container.resolve<MyService>('myService').doSomething()
```

It only covers class type service, but it should be possible to define others (value/function). It has some limitations (for example whole container definition must be passed directly to constructor to preserve types, so dynamic service loading would not work here) but maybe it's worth considering?

In my example VS Code/TS, when you write `container.resolve('`  automatically suggests 'myService' and it also knows resolved class instance type based on `myService` key.

Pros:
* Automatic suggestions of all registered services
* Automatic (without "casting") preserving of type of resolved service
* No need to import service class to cast to it when resolving service instance

Cons:
* No dynamic/automatic loading/registering of services - container definition must be passed to Container constructor to preserve types (it could be a "pro" at the same time, because it would simplify awilix code)
* Breaking change

What do you think?

Please note that I am not very experienced typescript dev. Still learning.

**Comment by jeffijoe** [comment]
I think if you add another registration then the type checking will fail because it will now be `MyService | OtherService`.

**Comment by jeffijoe** [comment]
I'm very impressed by your initial example, I hadn't thought of this before and it made me do some digging.

I don't want to force non-TS users to deal with TS limitations, however I do have a solution for you that you can apply to your own projects, or release as a separate library if you want to.

```ts

/**
 * Container definition base.
 */
interface ContainerDefinition {
  [key: string]: Resolver<unknown>
}

/**
 * Extracts the type that will be resolved from a resolver.
 */
type ExtractResolverType<T> = T extends Resolver<infer X> ? X : null

/**
 * Strongly-typed container.
 */
interface TypedAwilixContainer<T extends ContainerDefinition>
  extends Pick<AwilixContainer, Exclude<keyof AwilixContainer, 'resolve'>> {
  /**
   * Resolves the registration with the given name.
   *
   * @param  {string} name
   * The name of the registration to resolve.
   *
   * @return {*}
   * Whatever was resolved.
   */
  resolve<K extends keyof T>(
    key: K,
    resolveOptions?: ResolveOptions
  ): ExtractResolverType<T[K]>
}

/**
 * Wraps `createContainer` and calls `register` on it.
 */
function createTypedContainer<T extends ContainerDefinition>(
  registrations: T,
  opts?: ContainerOptions,
): TypedAwilixContainer<T> {
  return createContainer(opts).register(registrations) as any
}

const test = createTypedContainer({
  func: asFunction(() => 'nice'),
  val: asValue(123),
  cls: asClass(Date)
}, {
  injectionMode: InjectionMode.CLASSIC
})

// These all type check
test.resolve('func').toLowerCase()
test.resolve('val').toPrecision(2)
test.resolve('cls').toISOString()
```

**Comment by alekbarszczewski** [comment]
@jeffijoe Thanks man, it works!
I haven't thought about making it this way!

**Comment by JustinTRoss** [comment]
The code snippet above is helpful for initial registrations. Deps registered later do not get added to the typing though.

**Comment by gustawdaniel** [comment]
@jeffijoe Thank you for your comment from https://github.com/jeffijoe/awilix/issues/199

How to use this example combined with dynamic registration? My code

```
const container = createTypedContainer({}, {
  injectionMode: InjectionMode.CLASSIC
})

async function configureContainer (): Promise<AwilixContainer> {
  const connection = await connect(process.env.RABBIT_URI ?? 'amqp://localhost')
  const channel = await connection.createChannel()

  return container.register({
    redis: asValue(redis),
    channel: asValue(channel),
    emitter: asClass(EpgEmitter).singleton(),
    snapshotsService: asClass(LSportsSnapshotsService).singleton(),
    messagingService: asClass(LSportsMessagingService).singleton()
  })
}

export {
  configureContainer,
  container
}
```

connected issues:
https://github.com/jeffijoe/awilix/issues/265

**Comment by jeffijoe** [comment]
@gustawdaniel in practice, it doesn't really buy you much since you should prefer receiving dependencies through the constructor rather than passing the container around (except in cases where you are implementing a factory).

**Comment by gustawdaniel** [comment]
I finished with code using https://github.com/jeffijoe/awilix/issues/122#issuecomment-467356329 and exporting async `configureContainer` function.

```
export async function configureContainer () {
  const connection = await connect(process.env.RABBIT_URI ?? 'amqp://localhost')
  const channel = await connection.createChannel()

  return createTypedContainer({
    redis: asValue(redis),
    channel: asValue(channel),
    emitter: asClass(EpgEmitter).singleton(),
    snapshotsService: asClass(LSportsSnapshotsService).singleton(),
    messagingService: asClass(LSportsMessagingService).singleton()
  }, {
    injectionMode: InjectionMode.CLASSIC
  })
}
```

cradle is not typed, but typescript works if I will write

```
const container = await configureContainer()

container.resolve('messagingService').handleMessage(message, channel))
```

maybe it it worth exporting `createTypedContainer` from the library code or adding this brilliant example of TS from https://github.com/jeffijoe/awilix/issues/122#issuecomment-467356329 to docs?

**Comment by jeffijoe** [comment]
Adding it to docs would be the best option I think.
