### ISSUE TITLE
async/await not working with with higher order functions

### ISSUE THREAD

**Issue by gate3** [jeffijoe/awilix#123]
Awesome library, does the job perfectly. Thank you!

I have an issue though. I have a function I need to pass arguments to, so I decided to use a higher order function like this 

```javascript
const signupController = ({ userModel, encryptionHelper, cacheHelper }) => async (data) => {
  try {
    const { username, firstName, lastName, password } = data
    const user = new userModel()
    user.first_name = firstName
    user.last_name = lastName
    user.username = username
    const pass = encryptionHelper.hashSync(password)
    user.password = pass
    const result = await user.save()
    console.log(result)
    // await cacheHelper.addToSet(cacheHelper.CONSTANTS.USERNAMES, username)
    return Promise.resolve(result)
  } catch (e) {
    console.log(e)
    if (e.code === 11000) {
      // eslint-disable-next-line prefer-promise-reject-errors
      return Promise.reject('Usernmae already exists')
    }
    return Promise.reject(e)
  }
}
module.exports = signupController
```

But for some reason the  async/await isn't working. I can't handle error or success.

Here is how I am calling it

const aw = require('../../initAwilix')
aw.initialize()
const container = aw.container
const data = await container.resolve('signupCtrl')(req.body)

**Comment by jeffijoe** [comment]
What part isn't working? This should work just fine, it's how the Express and Koa bindings work.

**Comment by jeffijoe** [comment]
On a separate note, you don't have to use `Promise.resolve` and `Promise.reject`, `return result` and `throw e` will be sufficient.

**Comment by gate3** [comment]
Hi @jeffijoe thanks for your response. So I am calling the controller function from my route like this

```javascript
const result  = await container.resolve('signupCtrl')(req.body)
```
Thanks for the tip on Promise.resolve and reject.

**Comment by jeffijoe** [comment]
It should work just fine, I need some more detail on what the problem is.

**Comment by gate3** [comment]
Would you be open to me committing the code to a repository and giving you access?

**Comment by jeffijoe** [comment]
Sure, but please explain what the issue is. Is it throwing an error? What's happening?

**Comment by gate3** [comment]
Its not throwing any errors, nothing. No result, the catch block isn't catching any errors either, one thing i noticed though is that when running in cluster mode the app crashes the worker its running in. 

Here is the link to the repo

[https://github.com/gate3/naijacowry-core-demo](https://github.com/gate3/naijacowry-core-demo)

**Comment by jeffijoe** [comment]
I am not seeing any controller files in that repo. But check to see if `container.registrations` contains your `signupCtrl`, if not then its not being loaded.

**Comment by gate3** [comment]
The controllers exist in src/auth. They are all files the files that have ctrl behind them. Just committed again, sorry some things where missing like the routes. You can find them in src/auth/routes.

**Comment by jeffijoe** [comment]
Please log `container.registrations` and verify they are registered under the names you expect. And I still don't see the code you posted for the route anywhere.

**Comment by gate3** [comment]
I logged it, 

![image](https://user-images.githubusercontent.com/3597437/53506639-b19fa780-3ab6-11e9-9933-7112d46aacc9.png)

The sign up controller exists in the DI.

Here is the route code

https://github.com/gate3/naijacowry-core-demo/blob/master/src/auth/routes.js

**Comment by jeffijoe** [comment]
You are not awaiting it.

![image](https://user-images.githubusercontent.com/2505474/53506946-4bffeb00-3ab7-11e9-9a1d-3f2bff306341.png)

**Comment by gate3** [comment]
Still thesame problem, just tried it awaiting it.

**Comment by jeffijoe** [comment]
I am certain the error is unrelated to Awilix though. See https://github.com/jeffijoe/koa-es7-boilerplate for a working repository.

**Comment by gate3** [comment]
Sigh.. Thanks
