### ISSUE TITLE
Could not resolve 'Symbol(Symbol.toPrimitive)'

### ISSUE THREAD

**Issue by chrisgo** [jeffijoe/awilix#127]
Hi,

This is somewhat related to https://github.com/jeffijoe/awilix/issues/7
specifically trying to load a class that extends Bull (Queue)
https://github.com/OptimalBits/bull

```
var Queue = require('bull');

class TestQueue extends Queue {
}

module.exports = TestQueue;
```

then create a container using `container.loadModules(...);`

and it breaks right away when you do something like

```
const testQueue = container.resolve('testQueue');
```

Specifically this line 
https://github.com/OptimalBits/bull/blob/develop/lib/queue.js#L1139

```
Resolution path: testQueue -> Symbol(Symbol.toPrimitive)
  at resolve (/var/www/project/nodejs/node_modules/awilix/lib/container.js:232:23)
  at Object.get (/var/www/project/nodejs/node_modules/awilix/lib/container.js:63:32)
  at Array.join (native)
  at TestQueue.Queue.toKey (/var/www/project/nodejs/node_modules/bull/lib/queue.js:1139:49)
  at Queue._.each.key (/var/www/project/nodejs/node_modules/bull/lib/queue.js:261:24)
  at arrayEach (/var/www/project/nodejs/node_modules/lodash/lodash.js:516:11)
  at Function.forEach (/var/www/project/nodejs/node_modules/lodash/lodash.js:9344:14)
  at new Queue (/var/www/project/nodejs/node_modules/bull/lib/queue.js:238:5)
  at new TestQueue (/var/www/project/nodejs/app_di/queues/index.js:10:1)
  at newClass (/var/www/project/nodejs/node_modules/awilix/lib/resolvers.js:85:24) AwilixResolutionError: Could not resolve 'Symbol(Symbol.toPrimitive)'.
```

I have tried to set the `util.inspect(...)` to undefined but that didn't seem to work

```
container.register({
  inspect: awilix.asValue(undefined),
});
```

Not really sure how to handle and if this can be patched?

**Comment by jeffijoe** [comment]
Third party classes and functions are best added to the container manually using asFunction. If your class does not have any dependencies, you can declare a constructor that just calls super().

**Comment by jeffijoe** [comment]
To clarify, you can either do this:

```js
class TestQueue extends Queue {
  constructor() {
    super()
  }
}
```

Or you can register your queue like this (I would recommend doing this, more control):

```js
container.register{
  queue: asFunction(() => new TestQueue())
})
```

**Comment by chrisgo** [comment]
Thank you so much, adding the `constructor() { ... }` works

**Comment by fraybabak** [comment]
I have this issue when I am trying to inject my own error handler . 

the error
```
export class GeneralError extends Error {
  constructor(message, code) {
    super(message);
    this.message = message;
    this.code = code;
  }
}
```
inside container:

```
container.register({
    generalError: awilix.asClass(GeneralError),
  })
```

`error: AwilixResolutionError: Could not resolve 'Symbol(Symbol.toPrimitive)'.`

**Comment by mcarrf90-bz** [comment]
> I have this issue when I am trying to inject my own error handler .
> 
> the error
> 
> ```
> export class GeneralError extends Error {
>   constructor(message, code) {
>     super(message);
>     this.message = message;
>     this.code = code;
>   }
> }
> ```
> 
> inside container:
> 
> ```
> container.register({
>     generalError: awilix.asClass(GeneralError),
>   })
> ```
> 
> `error: AwilixResolutionError: Could not resolve 'Symbol(Symbol.toPrimitive)'.`

Have the same issue currently, any solution?

**Comment by jeffijoe** [comment]
Why would you register an error class like that?

The error is thrown because you are likely using proxy-mode, so Awilix passes in the cradle as `message`, and the `super(message)` attempts to read properties from the cradle which Awilix intercepts and attempts to resolve as a dependency.

**Comment by mcarrf90-bz** [comment]
What's the problem with registering an error class in this way? I'm sorry if the question is too basic but I'm new to Awilix and currently migrating all of our app.

**Comment by mcarrf90-bz** [comment]
Thanks a lot for your response Jeff. I'm really loving Awilix so far. Just to clarify some points:

- Why wouldn't I want to inject a utility for example, like i18next. You could have some default configurations on the top level  and inject it to other classes that might need it. What I'm thinking base on my experience is that I should probably generate an abstraction layer in between i18next and whatever class might use it

**Comment by jeffijoe** [comment]
Yes, that falls under the I/O category (the translations come from somewhere, right?)

When I said utilities, I meant things like `map`, `sort`, `leftPad`. If you have something that is pre-configured at startup, then that's fine to inject, because you are injecting it for a reason, not just "because". 😄
