### ISSUE TITLE
first DI, need confirmation + question about class and function 

### ISSUE THREAD

**Issue by fas3r** [jeffijoe/awilix#128]
Hello, 

I did this first "DI" to test and I would like to know if it's the way to go please ..

/system/system-tracer.js
```
'use strict';
import { createLogger, format, transports } from 'winston';
import 'winston-daily-rotate-file';
const {splat, combine, timestamp, label, prettyPrint, json } = format;
const { DailyRotateFile, Console } = transports;

export default ({params}) => ({mechanism=params.mechanism, endpoint, service, component, method}) => {

  console.log({mechanism});

  const rootPath = `logs/${endpoint}/${service}/${method}`;
  // fileTransport to store locally
  const fileTransport = new (DailyRotateFile)({
    filename: `${component}.log`,
    dirname : rootPath,
    auditFile : `${rootPath}/${component}-audit.json`,
    handleExceptions: (process.env.NODE_ENV !== 'production'),
    datePattern: 'YYYY-MM-DD-HH',
    zippedArchive: true,
    maxSize: process.env.LOG_SIZE || '20m',
    maxFiles: process.env.LOG_ROTATION_DAYS || '14d'
  });


  // check if the log trace is suppose to be muted ( not visible in logs )
  const isPrivate = format((info, opts) => {
    if (info.private) { return false; }
    return info;
  });

  // add header from the object to the trace. Endpoint, service, component, method
  const addPath = format( (info, opts) => {
    info.enpoint = endpoint;
    info.service = service;
    info.component = component;
    info.method = method;
    return info;
  });

  // default configuration for the logger
  const loggerOptions = {
    level : process.env.LOG_LEVEL || 'info',
    format : combine(
      isPrivate(),
      isPassword(),
      isToken(),
      json()
    ),
    transports: [
      fileTransport
    ],
    exceptionHandlers: [
      new transports.File({ filename: 'exceptions.log' })
    ]
  };


  // create the logger instance
  const logger = createLogger(loggerOptions);


  // if Dev, then "output" the log in the console too.
  // If Prod, then "log" in files + AMQP.
  if (process.env.NODE_ENV !== 'production') {
    logger.add(new Console({
      format: combine(
        splat(),
        isPrivate(),
        addPath(),
        timestamp(),
        prettyPrint(),
      )
    }));
  } else {
    // add AMQP connector or syslog connector... We will see.
  }


  // Do not cause winston to exit the application.
  logger.exitOnError = false;

  return logger
};
```

and in index.js : 

```
'use strict';

import {createContainer, asClass, asFunction, Lifetime, asValue} from "awilix";

const container = createContainer();

container.loadModules( [
    [`${__dirname}/system/*.js`, {
      injector: () => ({ params : {
          mechanism : 'local'
        }
      })
    }]
  ], {
  formatName: 'camelCase',
  resolverOptions: {
    register: asFunction,
    lifetime: Lifetime.SINGLETON
  }
});

example
const log = container.cradle.systemTracer({
  endpoint : '/',
  component : 'notification',
  service : 'auth',
  method : 'http'
}).info({mechanism : 'amqp' , authToken : 'dldksfldkfdslfk', password : 'asldkalasdlsdad',message : 'lklsdkflsdkf'});
```

It's working, `mechanism` define in the `injector` (local) . get overwritten by the one from the `example` ( ampq) . 

Is it the way to go with `awilix` ? 

This will sound a bit stupid, but when should I use a class / against a factory function ? 

Class when create/update/delete data ? 
Function to access resource (db,cache, amqp )?

The only thing that I know is that FF need twice the time to initialise compare to a class but we talk in millisecond I guess it's acceptable  :D

Thanks.

**Comment by jeffijoe** [comment]
Yeah that looks good to me! You used the injector correctly :)

Class vs factory, thats mostly personal preference. Factories might be a tad slower to initialize, but I think that they are faster if they share scoped state vs a class needing to do `this.stuff` every time.

**Comment by fas3r** [comment]
Hello @jeffijoe , 

ok cool thanks :D I was not expecting an answer so fast, thank you. I need to add the disposal.. forgot.

Regarding your answer about Class vs Factory, Ok I see what you mean, I tried to find and read as much as possible on this, but as you say it's more a question of preference. 
I thought it was good to ask here as building such tool require a good understanding ( I guess ) of the underline of node.js. 

Last Question, I see many times Object.assign() or Object.frooze(), is it necessary to return such object or awilix deal with it bases on the LIFETIME ?

Thanks by advance.

**Comment by jeffijoe** [comment]
I don’t understand your last question? :)

**Comment by fas3r** [comment]
Sorry, 

In many how-to / tutorials about Dependency Injection , I see stuff like this (based on my example ) :

```return Object.assign({}, logger)```

instead of 

```return logger```

Just wondering if it's necessary or awilix do it for us as we define the scope of the Function / Class.

Thanks

**Comment by jeffijoe** [comment]
Hmm, well the assign variant creates a new object with the same props as logger. I dont think you need to worry about that. You might be interested in scopes though, check out the docs on scopes and lifetime 😀
