### ISSUE TITLE
Documentation Discrepancy

### ISSUE THREAD

**Issue by jhoscar1** [jeffijoe/awilix#129]
The documentation around `container.createScope()` seems to have contradictory information.

-----

"A Scope maintains it's own cache of Lifetime.SCOPED registrations, meaning it **does not use the parent's cache for scoped registrations.**"

```
let counter = 1
container.register({
  counterValue: asFunction(() => counter++).scoped()
})
const scope1 = container.createScope()
const scope2 = container.createScope()

container.cradle.counterValue === 1

// These are resolved to the parent's cached value.
scope1.cradle.counterValue === 1
scope1.cradle.counterValue === 1
scope2.cradle.counterValue === 1
scope2.cradle.counterValue === 1
```
-----

The bolded text seems to directly contradict the comment in the code example. It _seems_ like there should be a "not" in the comment judging by the code example. Which one is true?

**Comment by jeffijoe** [comment]
You are correct, the behavior changed and I must have forgotten to update that part of the docs. I’ll take a look when my eyes recover, just got out of surgery 👀

https://github.com/jeffijoe/awilix/commit/b65ae3439e1ea3d6900d020115166a22646ef365

**Comment by jhoscar1** [comment]
@jeffijoe Thanks for the quick response! Wishing you a speedy recovery!

**Comment by jeffijoe** [comment]
Thanks!
