### ISSUE TITLE
Resolve to a custom method

### ISSUE THREAD

**Issue by sharathm** [jeffijoe/awilix#132]
Hi,
I have the following class, its nothing complicted, just sets up a connection to RabbitMQ and exposes the channel via a `get interface()`. 

```
'use strict';
import amqplib from 'amqplib';
export default class RabbitMQService {
	constructor(opts) {
		const connectionString = 'amqp://' + process.env.AMQP_USER + ':' + process.env.AMQP_PASSWORD + '@' + process.env.AMQP_HOST + ':' + process.env.AMQP_PORT;
		amqplib.connect(connectionString)
			.then((connection) => {
				this.connection = connection;
				return connection.createChannel();
			}).then((channel) => {
				this.channel = channel;
			})
			.catch(console.error);
	}
	dispose() {
		if (this.connection)
			this.connection.close();
		super.dispose();
	}
	get interface() {
		return this.channel;
	}
}
```

This is being registered to the diContainer as `asClass`. 
`container.register('rabbitMQService',asClass(RabbitMQService));`

What I wanted to know was, that when I resolve this as below,
`container.resolve('rabbitMQService')`, i want access to only the value returned by `interface()`. Right now, it returns me the whole object which container the connection object etc, which i am looking to hide.

Is there any way to achieve this, by writing a custom resolver handler or some such mechanism? 
I am looking to have a common structure for all my services so that only required operations are exposed via the `interface`. 

Any help is appreciated..

**Comment by jeffijoe** [comment]
That's definitely possible, but before I explain how, I'll explain why this is going to be a problem.

Firstly, your connection is not immediately available, so if you resolve it before it connects, you'd get `undefined` back.

Secondly, you are letting your application continue despite an error being thrown when connecting to a critical piece of infrastructure (I presume). If you are not monitoring your logs, you wouldn't notice it until your users start seeing `cannot read property .. of undefined`.

This is what I recommend doing: have a `configureContainer` function that connects to Rabbit, and registers it in the container.

```js
async function configureContainer() {
  // Connect here. It it fails, so does setting up the container.
  const rabbitConnection = await amqplib.connect(connectionString)
  
  const container = createContainer()
  
  // Register it in the container as a singleton,
  // and set up the disposer.
  container.register('rabbit', asFunction(() => rabbitConnection).singleton().disposer(c => c.close()))
  
  return container
}
```

This lets you connect at startup and also still have Awilix dispose the connection for you.

**Comment by sharathm** [comment]
Yes, i agree with the implementation points, i have already refactored the code into a `start()` function that does all the connection related activities. 

So basically what you are recommending is, take connections or other infrastructure setup out of the scope of the container, and let the container only deal with instances of those external connections like databases, loggers, queues etc?

**Comment by sharathm** [comment]
The broader idea i had was that, i will have a folder full of `services` and `components` and auto load them, and the components would use the services as needed via proxy injections.

**Comment by jeffijoe** [comment]
A lot of libraries will actually return you the "connection" immediately (sync) and not create an actual DB connection before you invoke some of it's methods for the first time. For those, you can register them in the container and have the container create them for you.

But whenever there's async involved, you either need to `await` the dependency that gets injected, or simply await it before you register it using the approach I outlined above.

But yes, in general I've found it best to set up the connection before registering them. 😄

**Comment by jeffijoe** [comment]
If you really really really wanted to do this though, you could write a Resolver that returns a Proxy, and that Proxy would get a connection and then invoke the actual called method.

**Comment by jeffijoe** [comment]
With all of this said, there's an alternative way. You register an async factory.


```js
// Your component..
class MyComponent {
  constructor({ getRabbitConnection }) {
    this.getRabbitConnection = getRabbitConnection
  }
  
  async doStuff() {
    const rabbit = await this.getRabbitConnection()
    await rabbit.whatever()
  }
}

// In your container file...
container.register({
  myComponent: asClass(MyComponent),
  rabbit: asFunction(() => amqplib.connect())
    .singleton()
    // Since `connect` returns a promise, we need to await it before we can close
    .disposer(p => p.then(c => c.close())),
  // This just resolves to a function that, when called, resolves the `rabbit` connection.
  getRabbitConnection: asAliasFactory('rabbit')
})

// Creates a resolver that returns a function which, when called, resolves the registration name
function asAliasFactory(registrationName) {
  return {
    resolve(container) {
      return () => container.resolve(registrationName)
    }
  }
}
```

**Comment by sharathm** [comment]
Great stuff, thanks a lot! I think this will help, and also thanks for the pointer on initialising connections before the container gets involved, i am also thinking that is a good idea to do it the way you are proposing. Lets see..  😄

**Comment by jeffijoe** [comment]
Sounds good, I'll close this for now then, good luck! 😄
