### ISSUE TITLE
Ability to use Symbol as a name

### ISSUE THREAD

**Issue by moltar** [jeffijoe/awilix#136]
Would be nice to be able to use Symbols to ensure that the names are unique.

Right now this is not possible.

```ts
export class Env {
  public static readonly symbol = Symbol(Env.name)
}

container.register(Env.symbol, asClass(Env).singleton())
```

Error:

```
    TypeError: Cannot convert a Symbol value to a string
        at Array.join (native)

    at new AwilixResolutionError (node_modules/awilix/src/errors.ts:135:50)
      at resolve (node_modules/awilix/src/container.ts:450:15)
      at dependencies.map.p (node_modules/awilix/src/resolvers.ts:475:9)
          at Array.map (<anonymous>)
      at Object.resolve (node_modules/awilix/src/resolvers.ts:474:37)
      at Object.resolve (node_modules/awilix/src/container.ts:468:33)
```

Thanks!

**Comment by jeffijoe** [comment]
Curious why you’re doing this though?

**Comment by moltar** [comment]
Just to make sure there is no accidental duplication of names.

**Comment by moltar** [comment]
And keep names close to the class itself, so that I don't produce any "magical strings".

**Comment by jeffijoe** [comment]
But how would you inject these into constructors/functions? If you are `resolve`ing manually everywhere then there's almost no point in using Awilix? 😄

**Comment by jeffijoe** [comment]
I just added this test and it passes, so there's something else wrong with your configuration?

```ts
describe('using symbols', () => {
  it('works', () => {
    class Test {
      static readonly symbol = Symbol(Test.name)
    }

    const container = createContainer()
    container.register(Test.symbol, asClass(Test))
    expect(container.resolve(Test.symbol)).toBeInstanceOf(Test)
  })
})

```

**Comment by moltar** [comment]
> But how would you inject these into constructors/functions?

I would inject a proxy, and then just take what I need?

E.g.

```ts
constructor(deps) {
  this.test = deps[Test.symbol]
}
```

> I just added this test and it passes, so there's something else wrong with your configuration?

Thanks for looking at that. Pretty strange that it doesn't work on my setup.

I will investigate.

I'm using TypeScript, so maybe it's something to do with that.

Thanks!

**Comment by jeffijoe** [comment]
Awilix is written in TS and so are the tests, so I don't think that's anything to do with it.

**Comment by moltar** [comment]
Yeah, I think it works now ... for some reason. I have no idea how and why 😂 

But the ultimate problem, I realize now, is that there isn't a good way to do type-safe, and typO-safe injections.

For proxies, the constructor argument is untyped.

```ts
constructor(deps: any) {
// we don't know what that deps is... must be any
}
```

For classic, then we rely on parameter names matching the dependency names.

```ts
container.register('foo', asValue(1))

constructor(foo: number) {
  // but what happens if registration is renamed?
  // now the parameter will break
}
```

Are there any good solutions to this?

1. Keep DRY
2. Stay type safe

What do you think?

Thanks.

**Comment by jeffijoe** [comment]
I don't think there's any nice way to do this in a dynamic language.

If you rename the parameter, you'll get a resolution error which should be caught by your integration tests, surely?

**Comment by moltar** [comment]
> I don't think there's any nice way to do this in a dynamic language.

I agree. But there might be some lesser nice ways, but still acceptable? 😁 

---

> should be caught by your integration tests, surely?

![image](https://user-images.githubusercontent.com/491247/59036492-675c5e00-883d-11e9-9ffd-c99ad0016110.png)

**Comment by jeffijoe** [comment]
You could potentially extend my idea from here: https://github.com/jeffijoe/awilix/issues/122#issuecomment-467356329

**Comment by moltar** [comment]
Okay, I'll play around with #122. Thanks!
