### ISSUE TITLE
How should I configure the container?

### ISSUE THREAD

**Issue by JamieCorkhill** [jeffijoe/awilix#137]
In your Medium article, you create a factory function to do the work of configuring/registering the container:

```javascript
export default function configureContainer () {
  const container = createContainer()
  
  // Ordering does not matter.
  container.register({
    // Notice the scoped() at the end - this signals
    // Awilix that we are gonna want a new instance per "scope"
    todosService: asFunction(makeTodosService).scoped(),
    // We only want a single instance of this
    // for the apps lifetime (it does not deal with user context),
    // so we can reuse it!
    todosRepository: asClass(TodosRepository).singleton()
  })
  
  return container
}
```
I'm using `container.loadModules`, so I was wondering if it's alright to do something like this:

```javascript
// containerFactory.js

const awilix = require('awilix');

// Default Factory Function
module.exports = () => {
    // Create the DI Container.
    const container = awilix.createContainer();

    // Load modules.
    container.loadModules([
        [
            'custom-exceptions/index.js',
            {
                register: awilix.asClass,
                lifetime: awilix.Lifetime.TRANSIENT,
            }
        ], {
            formatName: 'camelCase'
        }
    ]);

    return container;
};
```
What I'm worried about, however, is that calling this function in all of my files is going to make Awilix go out and try to autoload all of my dependencies again.

If I have ten other files, and I do this at the top of each file:

```javascript
const container = require('./containerFactory')();
```
Will Awilix attempt to register the container ten other times and be extremely latent (if I have hundreds of deps), or will using `require` make the factory function a singleton (I worry about module caching issues in different scopes), or does Awilix perform its own internal caching of registered dependencies behind the scenes?

Thank you.

**Comment by jeffijoe** [comment]
I do the same, but I only create a single root container per process. Why would you call it in all of your files?

**Comment by JamieCorkhill** [comment]
@jeffijoe That's what I'm wondering. It sounded peculiar, which is why I asked.

If I'm using Express, and I have different routes/controllers in different files, is the only way to use Awilix though the `awilix-expess` middleware?

What about requiring the container in different integration test files?

**Comment by jeffijoe** [comment]
> If I'm using Express, and I have different routes/controllers in different files, is the only way to use Awilix though the awilix-expess middleware?

Not at all! At their core, the Express (and Koa, which I would recommend you use instead) Awilix middlewares could be expressed in as little code as this:

```js
function inject(container, handler) {
  return (req, res, next) => container.createScope().build(handler)(req, res, next)
}
```

However, the Express and Koa bindings have a neat "controller" declaration system which uses a router under the hood and also hides the whole container thing.

> What about requiring the container in different integration test files?

If you are using Jest, each file usually gets their own environment (or at least your would-be singletons are run for as many cores you have on your machine, can't remember). Even so, I haven't seen any performance issues.

**Comment by JamieCorkhill** [comment]
@jeffijoe Thanks for the information.

All I need is to be able to pull my Service off the container inside the Controller and allow the Service to attain a Repository. 

What's the best way of doing that?

I have my own auth middleware that puts a `user` object onto each Controller for those that need it, so I don't need `scopePerRequest`.

Again, thanks for your time.

**Comment by jeffijoe** [comment]
I would strongly recommend using `scopePerRequest` specifically for passing your `user` to the controllers.

Your middleware would simply be:

```js
function auth(req, res, next) {
  req.container.register('user', asValue(req.user).scoped())
  next()
}
```

Take a look at [this boilerplate](https://github.com/jeffijoe/koa-es7-boilerplate), it sounds like it covers everything you want. [This bit](https://github.com/jeffijoe/koa-es7-boilerplate/blob/master/src/middleware/register-context.js) and [this bit](https://github.com/jeffijoe/koa-es7-boilerplate/blob/master/src/services/todo-service.js) might be of interest.

I'm usually lurking in the [Koa Slack](https://communityinviter.com/apps/koa-js/koajs) if you're thinking of making the switch :)

**Comment by JamieCorkhill** [comment]
@jeffijoe Thank you for the resources. Why do you prefer Koa over Express?

> I would strongly recommend using `scopePerRequest` specifically for passing your ` user` to the controllers.

Not every endpoint requires an authenticated user. Some are publicly accessible. 

> Take a look at this boilerplate

Will that show how the model gets injected into the repository, how the repository gets injected into the service, and how the service gets injected into the controller, as per my updated comment?

Sorry to bother you with these questions. Thanks for your help and thanks for making Awilix.

**Comment by jeffijoe** [comment]
> Not every endpoint requires an authenticated user. Some are publicly accessible.

Still supported, simply register a default empty user context.

> Will that show how the model gets injected into the repository, how the repository gets injected into the service, and how the service gets injected into the controller, as per my updated comment?

That's exactly what it does. 😄

**Comment by JamieCorkhill** [comment]
@jeffijoe 

> Still supported, simply register a default empty user context.

So if I have

`GET /products` - Public
`POST /products` - Protected

inside the same file, and I register with an empty user context, how is my GET Route going to get the empty content and my POST Route going to get the authenticated `user` object?

**Comment by jeffijoe** [comment]
Use `scopePerRequest` first. In `configureContainer`, do the following:

```js
// Always provide a context. Initialize the user to `null`.
// This is available at all times.
container.register('context', asValue({ user: null }).scoped())
```

Make sure `scopePerRequest` is added at the top-end of your middleware chain so it runs before all your auth and controller stuff.

In your auth middleware:

```js
function auth(req, res, next) {
  // In fact I would let requests with no auth parameters
  // pass through and make the assertion in my controller.
  req.container.resolve('context').user = req.user
  next()
}
```

In your controller:

```js
const { NotAuthenticated } =  require('fejl') // shameless plug

class MyController {
  constructor(context, productRepository) {
    this.context = context
    this.productRepository = productRepository
  }

  async createProduct(req, res) {
    // Throw a NotAuthenticated if the user is not set.
    NotAuthenticated.assert(this.context.user, 'You are not authenticated')
    const product = await productRepository.create({
      created_by: this.context.user.id,
      ...req.body
    })
    res.status(200).json(json)
  }
}
```

**Comment by jeffijoe** [comment]
I prefer Koa because it's middleware system makes more sense, it's more flexible, it's async, it's leaner and faster. [See this](https://medium.com/netscape/mastering-koa-middleware-f0af6d327a69). 😄

**Comment by JamieCorkhill** [comment]
@jeffijoe 

Thanks very much for your time. I appreciate it.

I'll do some more work tomorrow with your example and with the boilerplate you sent me. I'll let you know how it goes or if I have more questions (if that's okay?).

Thank you.

**Comment by jeffijoe** [comment]
Sure! Slack is a better medium for instant communication though. 😄

**Comment by JamieCorkhill** [comment]
@jeffijoe I'll sign up to the Slack link you sent.

Pertaining to my auth middleware function, I currently have this:

```javascript
const jwt = require('jsonwebtoken');
const User = require('./../models/user');

const auth = async (req, res, next) => {
    try {
        const token = req.header('Authorization').replace('Bearer ', '');
        const decoded = jwt.verify(token, process.env.JWT_SECRET);
        const user = await User.findOne({ _id: decoded._id, 'tokens.token': token });

        if (!user) {
            throw new Error();
        }

        req.token = token;
        req.user = user;
        next();
    } catch (e) {
        res.status(401).send({ error: 'Please authenticate.' });
    }
}

module.exports = auth;
```
And would use it like this:

```javscript
app.get('/products', (req, res) => res.send());
app.post('/products', auth, (req, res) => res.send());
```
But, you are saying to do this:
```javascript
const jwt = require('jsonwebtoken');
const User = require('./../models/user');

const auth = async (req, res, next) => {
   const token = req.header('Authorization').replace('Bearer ', '');
   const decoded = jwt.verify(token, process.env.JWT_SECRET);
   const user = await User.findOne({ _id: decoded._id, 'tokens.token': token });

    req.user = req.container.resolve('context').user = req.user;
    next();
}

module.exports = auth;
```
And then, in a Controller, and suppose I have my own `AuthenticationError` that `extends` `Error`, I'd assert that `req.container.user` is not `null`, like this:

```javascript

class MyController {
    // ctor ...
   createProduct(req, res) {
       if (!req.container.cradle.user) res.status(401).send();

      // ...
   }
}
```

Since that `if` statement is going to be reused in many places, can that not be made into its own middleware and be reused in each endpoint that require protection?

I still don't understand how `context` and `productRepository` get injected into `MyController`, but perhaps I'll understand better if I take a closer look at the boilerplate you sent.

**Comment by jeffijoe** [comment]
You can do the auth check however you want. DRY shouldn't be applied relentlessly, sometimes it makes more sense to have some composable one-liners so you can glance at a method and see how it flows as opposed to relying on some auth middleware defined elsewhere. Also, it doesn't have to be middleware! It could be as simple as

```js
function requireAuth(context) {
  if (!context.user) { throw new AuthError() }
  return context.user
}

class Ctrl {
  // ctor..

  async doStuff(req, res) {
    if (req.params.something) {
      const user = requireAuth(this.context)
      // Do something with user
    } else {
      // Dont require auth here maybe
    }
  }
}
```

The advantage is also to do selective auth. Like "if this parameter is specified, require that the user is authenticated".

Don't reference the container in your controller, inject the dependencies using `awilix-express`. I recommend using `loadControllers`.

In general, try to make HTTP (Express, Koa) an implementation detail of the outer "layer". If you some day want to expose your app over Websockets or TCP, you only need to write an "adapter" that translates websocket messages into your service calls. I've done this in practice where I have a service exposed over HTTP as well as Websocket, where the service was using `.scoped()` lifetime and would create an in-memory cache that would be scoped to the request, but when using websockets it would be scoped to the websocket connection.

**Comment by JamieCorkhill** [comment]
@jeffijoe Thank you.

I understand. The Controller layer should be very thin, sitting on top, and should only handle I/O of data. It also should never pass a `req` or `res` object directly to the service because then you would be coupling the service with either the HTTP Framework or the WebSocket implementation, etc.

I'll look into the `loadControllers` function in the docs for `awilix-express`, it sounds like what I'm looking for in terms of injecting services and repositories. 

Thanks.

**Comment by JamieCorkhill** [comment]
@jeffijoe 

I'm still a little stuck over what the best way to accomplish injection is. If you have time, I'd really appreciate it if you could help with this last question. I've attempted to show an extremely simple use case just to help me get my head around how `Awilix` and `awilix-express` works. The comments should show the questions I have. It would be helpful if you could show how this would be refactored to use `Awilix`.

Thanks again for your time.

```javascript
const express = require('express');
const app = express();

/* ////////// Products ////////// */

// File: ProductService.js
class ProductService {
  constructor({ productRepository }) { /* ... */ }
  getProducts(limit, skip) {
    return productRepository.getAll(limit, skip);
  }
  postNewProduct(productInfo) {
    return productRepository.save(productInfo);
  }
}

// File: ProductRepository.js
class ProductRepository {
  constructor({ productModel }) { /* ... */ }
  getAll(limit, skip) {
    return productModel.find().paginate(limit, skip);
  }
  save(productInfo) {
    return productModel.save(productInfo);
  }
}

/* ////////// Users ////////// */

// File: UserService.js
class UserService {
  constructor({ userRepository }) { /* ... */ }
  signUpNewUser(userInfo) {
    return userRepository.save(userInfo);
  }
}

// File: UserRepository.js
class UserRepository {
  constructor({ userModel }) { /* ... */ }
  save(userInfo) {
    return userModel.save(userInfo);
  }
}

/* ////////// Routes ////////// */

// File: products.js
app.get('/products', (req, res) => {
  // How do I get productService into this endpoint?
  const products = productService.getAll(10, 0);
  res.send(products);
});

app.post('/products', auth, (req, res) => {
  // How do I handle authentication in this endpoint?
  // How do I get productService in this endpoint?
  const product = productService.postNewProduct(req.product);
  res.send(product);
});

// File: user.js
app.post('/users', (req, res) => {
  // How do get userService in this endpoint?
  const user = UserService.signUpNewUser(req.user);
  res.send(user);
});

app.get('/users/me', auth, (req, res) => {
  // req.user is currently coming from my auth middleware.
  res.send(req.user);
});

/* ////////// Auth Middleware ////////// */

// auth.js
const auth = async (req, res, next) => {
    try {
        // The Authorization Bearer Token sent in the header of the request needs to be decoded.
        const token = req.header('Authorization').replace('Bearer ', '');
        const decoded = await admin.auth().verifyIdToken(token);

        // Finding that user in the database by their Firebase UID.
        const user = await User.findOne({ _id: decoded.uid });

        if (!user) {
            throw new Error();
        }

        // Making the user accessible to the endpoint.
        req.user = user;

        // Proceed
        next();
    } catch (e) {
        // HTTP 401 Unauthorized Response Status
        res.status(401).send({ error: 'Please authenticate.' });
    }
}

module.exports = auth;

```

**Comment by jeffijoe** [comment]
Keep using `scopePerRequest`, then use `inject` for the simplest way.

Example:

```js
const { inject } = require('awilix-express')
// Routes file.
app.post('/users', inject(({ userService }) => (req, res) => {
    const user = { username: 'Jamie' };

    userService.signUpNewUser(user);

    res.send('Complete');
}));
```

`inject` will use the `req.container` that `scopePerRequest` configures to inject dependencies into a request handler.

For auth, you can do:

```js
const auth = async (req, res, next) => {
    try {
        // The Authorization Bearer Token sent in the header of the request needs to be decoded.
        const token = req.header('Authorization').replace('Bearer ', '');
        const decoded = await admin.auth().verifyIdToken(token);

        // Finding that user in the database by their Firebase UID.
        const user = await User.findOne({ _id: decoded.uid });

        if (!user) {
            throw new Error();
        }

        // Making the user accessible to the endpoint.
        req.user = user;
        // Register the user in the container so we can inject it into services
        req.container.register('user', asValue(user))
        // Proceed
        next();
    } catch (e) {
        // HTTP 401 Unauthorized Response Status
        res.status(401).send({ error: 'Please authenticate.' });
    }
}
```

Now you can depend on `user` in your service, given that you've registered it with scoped lifetime (hence `scopePerRequest` 😄 )

**Comment by JamieCorkhill** [comment]
@jeffijoe Thank you very much. I understand now.

Is it possible to use `inject` as global middleware in any way so that I don't have to use it in every single endpoint?

With the `auth` example, do I still use `auth` inside each endpoint, i.e, `app.get('/protected', auth, inject ...);`?

**Comment by jeffijoe** [comment]
> Is it possible to use inject as global middleware in any way so that I don't have to use it in every single endpoint?

This is what the `controller` is for in `awilix-express` and `awilix-koa`. 😄

> With the auth example, do I still use auth inside each endpoint, i.e, app.get('/protected', auth, inject ...);?

Yes.

**Comment by JamieCorkhill** [comment]
@jeffijoe Thank you.

Also, will Awilix overwrite files of the same name? That is, if I attempt to autoload:

```
src/api/routes/user.js,
src/models/user.js,
...
```,
will the route be overwritten by the model?

**Comment by jeffijoe** [comment]
Yes it will overwrite.

**Comment by JamieCorkhill** [comment]
@jeffijoe I see, thanks. Or, perhaps I could just name them as `user.service.js`, and `user.route.js`, and `user.repository.js, etc..

I think I prefer your method, however.

Sorry for asking all of these questions - this is my first time using Dependency Injection. I've used Express many, many times, but never DI nor Awilix with Express, so, as you might imagine, I'm quite confused. I think I'm getting there, however. Thanks.

**Comment by jeffijoe** [comment]
No problem! Did you read my Medium series on DI with Awilix? It should explain a lot of this.

https://link.medium.com/LfcVPai9CX

**Comment by JamieCorkhill** [comment]
> Use `scopePerRequest` first. In `configureContainer`, do the following:
> 
> ```js
> // Always provide a context. Initialize the user to `null`.
> // This is available at all times.
> container.register('context', asValue({ user: null }).scoped())
> ```
> 
> Make sure `scopePerRequest` is added at the top-end of your middleware chain so it runs before all your auth and controller stuff.
> 
> In your auth middleware:
> 
> ```js
> function auth(req, res, next) {
>   // In fact I would let requests with no auth parameters
>   // pass through and make the assertion in my controller.
>   req.container.resolve('context').user = req.user
>   next()
> }
> ```
> 
> In your controller:
> 
> ```js
> const { NotAuthenticated } =  require('fejl') // shameless plug
> 
> class MyController {
>   constructor(context, productRepository) {
>     this.context = context
>     this.productRepository = productRepository
>   }
> 
>   async createProduct(req, res) {
>     // Throw a NotAuthenticated if the user is not set.
>     NotAuthenticated.assert(this.context.user, 'You are not authenticated')
>     const product = await productRepository.create({
>       created_by: this.context.user.id,
>       ...req.body
>     })
>     res.status(200).json(json)
>   }
> }
> ```
This comment you sent a few hours ago ^.

My main point of misunderstanding right now is how `productRespository` will get into `MyController` - i.e, how is that set up on the Express side in my `app.js`/`server.js` file.

**Comment by jeffijoe** [comment]
That happens when resolving the controller which you do with inject

**Comment by JamieCorkhill** [comment]
> No problem! Did you read my Medium series on DI with Awilix? It should explain a lot of this.
> 
> https://link.medium.com/LfcVPai9CX

I did. I think I should read the last article a second time, however.

They were very nice and well-written articles, by the way. Not many people can _inject_ (pardon the pun) humor into the text that way and still manage to make write something informative.

**Comment by jeffijoe** [comment]
Haha, happy to hear it!

**Comment by JamieCorkhill** [comment]
> That happens when resolving the controller which you do with inject

Right, so how do I use `inject` in that way but globally, such that I don't have to manually write `inject` into each endpoint?

**Comment by jeffijoe** [comment]
By letting awilix-express handle the routing. See the “new in v1” section in the docs.

**Comment by JamieCorkhill** [comment]
> By letting awilix-express handle the routing. See the “new in v1” section in the docs.

How do I selectively choose which routes have `auth` middleware?

**Comment by jeffijoe** [comment]
Using `before` - see the Awesome Usage section.

**Comment by JamieCorkhill** [comment]
> Using `before` - see the Awesome Usage section.

I had thought that - I must have read the entire docs five times now. What about file uploading with Multer? Can I use `before` in different places or will each `before` affect all routes beneath it, similar to fall through?

> But again, I would always run the auth middleware and leave it up to the service to determine whether auth is required. It gives you more flexibility, like auth is only required if the product is marked private.

In which case, I might have two middleware functions - an `attachUser` to register a user object into the container, whether it's null or not, and a `verifyAuth` to check whether `user` is null, and if so, return 401.

Is there not any way to inject deps into endpoints without having to make controllers and without having to do it manually for everyone?

Thanks.

**Comment by jeffijoe** [comment]
You can use before per route and per controller.

You can just pull dependencies out of req.container.cradle but I don’t see why you wouldnt just use the controllers feature or even just plain inject?

What if you want to verify auth based on some attributes from a product you have to fetch? Adding a verifyAuth middleware would not give you that flexibility, and you are coupling your authz to HTTP.

**Comment by JamieCorkhill** [comment]
@jeffijoe 

I'll just use `inject` manually for now. I'm on a timeline with regards to completing this project, so I'll spend more time learning `awilix-express` and refactor later to use a more maintainable pattern.

I agree with you about Auth and HTTP. Do decouple them, I have my own `AuthenticationError` that extends `Error`, and my auth middleware throws that error.

I use (express-async-errors)[https://www.npmjs.com/package/express-async-errors] to allow me to catch errors inside of a bottom `app.use` middleware function. That middleware function looks at the type of error, and if it's one of the errors I created, it pulls that error message and status code off that error object and sends it to the client, otherwise, the client gets a 500.

Thanks very much for your help. I apologize for taking up so much of your time.

**Comment by JamieCorkhill** [comment]
@jeffijoe Just to check, should I load all my third-party dependencies into the Container as well, such as the Node AWS SDK, the Firebase Admin SDK, the UUID Library, etc.?

**Comment by jeffijoe** [comment]
Only if you think you're getting value from that. I inject SDK's (because they require configuration) but not simple utilities like UUID.

**Comment by JamieCorkhill** [comment]
Thank you.

The only thing would be, with UUID, for example, that I could mock it to always give me the same random ID so that tests can be easier.

I suppose, however, that a Jest Manual Mock would do just fine.

In terms of injecting the Firebase Admin SDK or the Node AWS SDK, again, I can mock then manually with Jest, but I'm not sure if that goes against DI principals. Registering them in the container, however, might present problems with ensuring they are fully configured prior to registration.
________________________________

**Comment by jeffijoe** [comment]
Well if you already have a DI setup, if you do need to mock UUID then go ahead and inject UUID. You shouldn't have to use Jest module mocks for anything.

Injecting the SDKs, again, if you intend to mock them, sure. If not, do whatever you feel is more pragmatic. 😄

**Comment by JamieCorkhill** [comment]
@jeffijoe 

Alright - I suppose, then, in a Unit Test, I could register a new Container and overwrite the mocks, whereas, in an Integration Test, I could call the `containerFactory` again from earlier. 

Additionally, if I wanted to use the same Mock across Unit Test Suites, then I could write the mock as a fixture, export it, and register a new container in one of the `before` hooks in Jest.

Indeed, I define Adapters for my SDKs, so perhaps I could just do something like this:

```javascript
// Amazon Web Services and Amazon Web Services Mock
const aws = require('./../../config/aws/aws');
const awsMock = require('mock-aws-s3');

const FileCRUDAdapter = require('./FileCRUDAdapter');

const { cloudStorageConfig } = require('./../../config/config');

if (process.env.MODE === 'test') awsMock.config.basePath = '/tmp/buckets';

const s3 = process.env.MODE === 'test' ? (
    awsMock.S3({ params: { Bucket: cloudStorageConfig.buckets.testing.name }})
) : (
    new aws.S3()
);

// FileCRUDAdapterFactory (function)
module.exports = (bucket = undefined) => new FileCRUDAdapter(s3, bucket);
```

**Comment by JamieCorkhill** [comment]
And thanks, by the way.

**Comment by jeffijoe** [comment]
TBH your unit tests should not need to use a container, you should just construct your SUT (Subject Under Test) normally and provide whatever mocks you need.

I usually create my DB connections in `configureContainer` (see my Koa boilerplate), register them with Awilix and let Awilix dispose them on shutdown (`container.dispose()`).

**Comment by JamieCorkhill** [comment]
@jeffijoe 

 I see. Thanks. So it would be normal for the file that houses the `configureContainer` factory function to have many require statements when it comes to third-party NPM Modules if and only if those modules are being mocked?

**Comment by jeffijoe** [comment]
Don't have to be mocked, if it just makes sense to inject a "prepared" module (like an SDK) then you can. If you'd rather just import the module directly because it is part of the implementation and is not something you'd want to mock, just import it.

> So it would be normal for the file that houses the configureContainer factory function to have many require statements 

Absolutely! In fact that's the point! It's your *composition root*.

**Comment by JamieCorkhill** [comment]
@jeffijoe Great! Thanks.

So would this setup be considered normal?

config/firebase/firebase.js:
```javascript
const admin = require('firebase-admin');

admin.initializeApp({
    credential: admin.credential.cert(process.env.GOOGLE_APPLICATION_CREDENTIALS),
    databaseURL: "[URL]"
});

module.exports = admin;
```
Composition Root:

```javascript
const awilix = require('awilix');

// Third-party pre-configured SDKs:
const admin = require('./../config/firebase/firebase');

// Default Factory Function
module.exports = () => {
    // Create the DI Container.
    const container = awilix.createContainer({
        injectionMode: awilix.InjectionMode.CLASSIC
    });

    // Load modules.
    container.loadModules([
        [
            '../custom-exceptions/index.js',
            {
                register: awilix.asValue,
                lifetime: awilix.Lifetime.TRANSIENT,
            }
        ]
    ],  {
            cwd: __dirname,
        })
        .register({
            admin: awilix.asValue(admin) // RIGHT HERE
        });

    return container;
};
```
An Adapter getting the SDK injected: 

```javascript
module.exports = class AdminAdapter {
    constructor({ admin, AuthenticationError }) {
        // Dependency Injection
        this.admin = admin; 
        this.AuthenticationError = AuthenticationError; // A custom exception.
    }

    async verifyAuthToken(token) {
        try {
            const decoded = await admin.auth().verifyIdToken(token);
            return decoded;
        } catch (err) {
            throw new this.AuthenticationError();
        }
    }
}
```
Is it alright to be asking questions here like this, or am I taking up too much of your time?

Thanks.

**Comment by jeffijoe** [comment]
Yeah that looks reasonable, although not sure why you are injecting the error classes though, and also asValue does not use lifetime. 😀

Its fine, I don’t mind helping out, but it would be easier on the Koa Slack (and you really should consider Koa 😁)

**Comment by JamieCorkhill** [comment]
@jeffijoe I will consider Koa. This project is for a startup, I'm the only developer, and I'm on a 1.5-month timeline for getting an MVP in front Investors, so, for now, I'll stick with Express since I know it best. Eventually, I'll be refactoring my codebase to use TypeScript instead of JavaScript, and to use PostgreSQL instead of MongoDB, so I'll ponder a possible Koa migration then.

For Slack, do you mean the Private Messaging feature?

**Comment by jeffijoe** [comment]
Yeah, or you can ask your general design-related questions in the general chat and others can chime in too.

**Comment by JamieCorkhill** [comment]
@jeffijoe Alright. Thanks. I'll see you there.
