### ISSUE TITLE
Should the "name" alias in inlined resolver options "resolve" when a component is registered?

### ISSUE THREAD

**Issue by rclayton-the-terrible** [jeffijoe/awilix#139]
I saw this comment in the docs:

> Additionally, if we add a name field and use loadModules, the name is used for registration.

I'm wondering if `loadModules` is the only time the `Class.RESOLVER.name` property should be respected by the containers?

I have some test code here:

```typescript
class FoobarComponent {
  static [RESOLVER] = {
    name: 'component.foobar',
    lifetime: Lifetime.SCOPED
  }
}

const container = createContainer()

container.register({
  foobar: asClass(FoobarComponent),
})

console.log(container.registrations)

console.log(container.resolve('component.foobar'))
```

Which outputs:
```
{ foobar:
         { lifetime: 'SCOPED',
           name: 'component.foobar',
           resolve: [Function: resolve],
           setLifetime: [Function: setLifetime],
           inject: [Function: inject],
           transient: [Function: partiallyApplied],
           scoped: [Function: partiallyApplied],
           singleton: [Function: partiallyApplied],
           setInjectionMode: [Function: setInjectionMode],
           proxy: [Function: partiallyApplied],
           classic: [Function: partiallyApplied],
           disposer: [Function: disposer] } }
```

And then throws an error:
```
AwilixResolutionError: Could not resolve 'component.foobar'.

Resolution path: component.foobar
```

---

Admittedly, this isn't the prettiest approach to DI, but I'm trying to simulate something like Spring's "Get all beans of type" or Inversify's `@multiInject`.  I'm trying to build a simple component framework that uses Awilix as the DI container

This isn't a major problem for me -- I can just peek down into the registration and look at the name and resolve from the key.  However, I think an approach that could register aliases in addition to the object key would be quite valuable to developers implementing APIs on top of Awilix.

For instance, my primary goal is to do something like this:

```typescript
const container = createContainer()

container.register({
  check1: healthCheck(PGCheck), // aliases to "check.pg"
  check2: healthCheck(RedisCheck), // aliases to "check.redis"
})

// And then internally, I could do something like:
const checks = resolveHealthChecks(container) // which pulls anything that starts with "check."

// But even more ideally:
const checks = container.resolveMany('check.')

// Which might be a simplification of:
const checks = constainer.resolveMany(r => r.name.startsWith('check.'))
```

I would be happy to implement this feature and submit a PR.  I just want to see if you would be interested in this contribution.

Thank you - I know you are busy!

**Comment by rclayton-the-terrible** [comment]
@jeffijoe one thought on the `aliasTo` is that it basically becomes two registrations.  It would be great if you could do something like:

```
container.register({
  check1: asClass(PGCheck).aliasTo('check.pg')
})
```

Which would effectively allow a component author to create higher-order registrations:

```
container.register({
  check1: healthCheck(PGCheck),
})
```

**Comment by jeffijoe** [comment]
Registrations map 1 to 1 with a resolver, so that’s not possible.
