### ISSUE TITLE
Add TypeScript Definition file (index.d.ts)

### ISSUE THREAD

**Issue by blove** [jeffijoe/awilix#14]
This looks like a cool DI container service. Could you include a TypeScript definition file (index.d.ts) for use with TS?

**Comment by jeffijoe** [comment]
Yeah I've been thinking about it but haven't found the time to do it yet. It's either write a def file or rewrite Awilix in TS, still haven't decided yet. I kinda like how there's no build step at the moment.

Also, the TS defs would not provide much value other than a typed interface to the container (`register()`, `resolve()`, etc)

**Comment by jeffijoe** [comment]
If you're up for it though, feel free to write an index.d.ts and submit a PR, I'll gladly look at it. :)

**Comment by blove** [comment]
@jeffijoe I might do that. I am looking at using this in a TypeScript with Express project.

**Comment by jeffijoe** [comment]
Nice - @talyssonoc already wrote [Express bindings for Awilix](https://github.com/talyssonoc/awilix-express). 😄

**Comment by blove** [comment]
@jeffijoe I have a draft of the TypeScript definitions created. I studied your code and the documentation to create this first draft. I am going to be using Awilix in my project and will be using the definitions (and creating them allowed me to gain a good understanding of your library, all of the functions and methods, etc). 

I have not created any tests nor have I used the definitions in my project yet, so there may be some necessary updates/corrections. I will submit a PR after. But, I thought you might want to review what I created:

https://github.com/blove/awilix/blob/14-typescript-definitions/index.d.ts

**Comment by jeffijoe** [comment]
Nice work! 👍 

A few comments:

- `AwilixContainer` should probably be an interface instead of a class.
- The `asValue()` does not return an object with the lifetime funtions (it can be only one), so you would get a runtime error trying to do `asValue().singleton()`
- `formatName` can be a string (currently just `"camelCase"`) or it can be a function `(fileName: string) => string`
- `Registration` functions should return `this`:

  ```
  export interface Registration {
    singleton(): this;
    scoped(): this;
    transient(): this;
  }
  ```

Thanks a lot for this! If you have time, adding a TS test using the defs (that just verify they work as intended) would be great.

**Comment by blove** [comment]
Thanks, I'll work on these changes.

Can you verify if the `listModules()` function returns a promise object? In the code comments you indicate such, but it doesn't look that way in the documentation (the README).

**Comment by jeffijoe** [comment]
Yeah it did once - I thought I removed the comments detailing that, my bad.

**Comment by blove** [comment]
OK, I will update the return type to: `Module[]`.

**Comment by jeffijoe** [comment]
Thanks, just updated the code comments :+1:

**Comment by blove** [comment]
I made the updates as you suggested with one exception. I think the return type for the methods in the Registration class should be `Registration` and not `this`. Correct me if I am wrong.

https://github.com/blove/awilix/blob/14-typescript-definitions/index.d.ts

**Comment by jeffijoe** [comment]
Using `this` means `Registration` to TypeScript - it's useful for doing fluent API's.

**Comment by blove** [comment]
Got it. Committed and pushed.

**Comment by jeffijoe** [comment]
Nice, thanks! Submit a PR when you've battled-tested them. If you have any Awilix questions feel free to ask. Good luck with your project! 😄

**Comment by blove** [comment]
@jeffijoe I have submitted PR #15
