### ISSUE TITLE
[Question] pass arguments to 'makeInvoker' function?

### ISSUE THREAD

**Issue by jclaessens97** [jeffijoe/awilix#140]
Hello,

I want to use the makeInvoker function as a callback for passportJS verify function. It's not really working because the only thing that is getting passed trough is the req object, which is correct behavior if I take a look at the implementation.

I was wondering if it was possible to invoke a function of the controller with custom parameters? Thanks in advance!

**Comment by jeffijoe** [comment]
You can also use `req.container.build` for those cases if it’s not regular middleware.

**Comment by jclaessens97** [comment]
Just what I needed!
