### ISSUE TITLE
Can't resolve dependency with babel

### ISSUE THREAD

**Issue by KrGyan** [jeffijoe/awilix#141]
Hi,

I am using babel with express. I want all my services( already registered in container) to be available in controllers ( which are exported as class and bind to routes).

By using console.log(container.resolve('sampleService').getSample()) in app.js I can invoke the functions however when I try to get the service is controller it throws error:
  var sampleService = _ref.sampleService;
                                  ^
TypeError: Cannot read property 'sampleService' of undefined

**Controller:**

```js
'use strict'; 
import  BaseController  from '../system/providers/base.controller';
class sampleC extends BaseController {

        constructor({sampleService}){
            super();
            this.sampleVariable = null;
            this.sampleSHelper =  sampleService;
        }
        
       async getSample(req,res){
           try{
            let result = await this.sampleSHelper.getSampleData({test:'Yes Sample'}, null);
            res.done(result);
           }catch(err){
               console.log(err);
               res.json('Error In Sample Route');
           }
        }
        async getSampleMethod(req,res){
        }
}
module.exports = new  sampleC();
```

**app.js**

```
const awilix = require('awilix');
const { asValue,createContainer, InjectionMode,Lifetime } = require('awilix');
const listModules = require('awilix').listModules;
import {scopePerRequest } from 'awilix-express';

const container = createContainer({
  injectionMode: InjectionMode.PROXY
});

container.loadModules(["v3.2/services/**/*.js","v3.2/controllers/**/*.js"], {
  formatName: "camelCase",
  resolverOptions: {
    register: awilix.asClass,
    lifetime: Lifetime.SCOPED
  }
});
app.use(scopePerRequest(container));
```

**Comment by KrGyan** [comment]
@jeffijoe would be great to get your help on this.

**Comment by jeffijoe** [comment]
I'm not seeing any code that resolves the `sampleC`. I recommend using `awilix-express` controllers.

**Comment by KrGyan** [comment]
@jeffijoe, firstly thanks for quick response ( one of most quickest response till date) . I want to avoid using too much dependency on awilix-express . As my controller is just a simple class whose functions are binded to router in routes files.

Is ther any way, one can resolve the controllers ( would be great if you can insight on resolving controllers).

**Comment by jeffijoe** [comment]
Yes, you can use `container.build`

**Comment by KrGyan** [comment]
import sampleC  from '../controllers/sampleController';

module.exports = function(app,container) {
  const sampleController = container.build(sampleC)
  app.use("/sample", sampleController.getSample);
};

still the same error. Am I using conatiner.build correctly?

**Comment by jeffijoe** [comment]
`container.build(asClass(sampleC))`

**Comment by KrGyan** [comment]
@jeffijoe , works like charm . Thanks.

I will close the thread now .
