### ISSUE TITLE
How to exclude a file while loading via container.loadModules ?

### ISSUE THREAD

**Issue by Vivekhs** [jeffijoe/awilix#145]
Hi,

Inside the services folder there is a file called applicationService.js which I don't want to load in container. I can move this file to some other folder but Is there any way to do this by keeping in the same folder ? 
- Code 
` const container = createContainer()
container.loadModules(['services/**/*.js',], {
  resolverOptions: {
    injectionMode: InjectionMode.CLASSIC
  }
}) `

@jeffijoe Request you to guide me on this.

**Comment by jeffijoe** [comment]
I would suggest renaming it `application.js` and change the pattern to `'services/**/*Service.js`

**Comment by Vivekhs** [comment]
Thanks @jeffijoe. Closing this issue now.
