### ISSUE TITLE
Current Scope Reference

### ISSUE THREAD

**Issue by sharmanitin** [jeffijoe/awilix#146]
Hi,
thanks for the wonderful library.

I have few questions, first I'll share my setup

I load all services using loadModules:
`const modulesToLoad = [
  ['services/**/*.js', Lifetime.SCOPED],
  ...
];`
we create scope on every request in middleware
`ctx.scope = container.createScope();`

in our controller, we resolve service using ctx scope using the following code
`const service = ctx.scope.resolve('serviceA');`

I believe this service will be instantiated every time a new request being called for that api/controller. Additionally, I have also injected container reference (self reference) using asFunction:

> ```
> const result = createContainer(opts)
>     .loadModules(modulesToLoad, {
>       cwd: __dirname,
>       formatName: 'camelCase'
>     })
>    .register({
>       container: asFunction(getContainer),
>       lifetime: Lifetime.SINGLETON,
>     })...

this enables our service instance to have reference of root container:

> ```
> class ServiceA{
>     constructor({models, logger, container }) {
>       this.container = container;
>       ...
>     }
>    async someMethod() {
>     const serviceB = this.container.resolve('serviceB');
>    }
> }

I have following questions with regard to current setup:

- Is this the right way to setup DI and get dependent service instances ?
- In method defined above as `someMethod`, is `serviceB` gonna get scoped to root container or current request scope. If it gets attached to root container scope, how I can make it attach to current scope and not root container.
- Is there a way to get the current scope. this may help in resolving services in appropriate scope.
- should we call dispose() on every createScope() to avoid memory leaks

Additionally, how can i pass params to factory function so that I get dynamic strategy instance based on the param.

**Comment by sharmanitin** [comment]
@jeffijoe I have another question
It is related to dynamic injection of a strategy in the constructor of scope service (when we do resolve)

```
// service class
class A extends BaseService {
 constructor({ models, logger}) {
   super({models, logger});
 }
 someServiceMethod(payload) {
  // current calls factory function manually to get appropriate strategy to process request.
 const strategy = factoryFunction.getStrategy(payload.property);
 strategy.process(payload);
 }
}

// controller code - another file
const service = ctx.scope.resolve('a');
a.someServiceMethod(req.body);
```

Is there a way to inject strategy using the factory function when resolving service A, so that manual retrieval of strategy can be avoided.

**Comment by jeffijoe** [comment]
Not sure I understand, your factory depends on the payload, so how can you possibly avoid it?

**Comment by sharmanitin** [comment]
of what i understood, resolve will call the constructor to create the object of the named class. 
now there can be two options:
1. controller already have the payload, so can it pass the payload to the constructor, so that the constructor can set the appropriate strategy while creating the instance in the constructor itself
2. other way could be injecting factory with payload in the constructor, so that in the constructor  we can just call something like `factoryInstance.getStrategy()` to set the strategy

**Comment by jeffijoe** [comment]
It sounds like you want a regular factory.

```js
class MyClass {
  constructor({ myFactory }) {
    this.myFactory = myFactory
  }

  someMethod(payload) {
    const instance = this.myFactory(payload)
    instance.stuff()
  }
}
```

Then you register your factory:

```js
container.register({
  myFactory: {
    resolve: c => (payload) => c.build(asClass(MyThing).inject(() => ({ payload })))
  }
})
```
