### ISSUE TITLE
Awilix with TypeScript

### ISSUE THREAD

**Issue by jshjohnson** [jeffijoe/awilix#147]
Hey 👋 

More of a question than an issue but...

How do you suggest managing interfaces/maintaining type safety when using Awilix with TypeScript? Do you define a container interface and share that around? And if so, surely that makes unit testing a lot harder as you need to stub our out the entire container instead of just mocking the dependency you care about?

We've been using Awilix in production for years now btw - thanks for creating it 🎉

**Comment by jeffijoe** [comment]
I personally use classic injection, and there's no type safety when Awilix builds the module, but you can specify the types of the parameters.

```ts
function MyModule(dep1: IDep1, dep2: IDep2) {}
```

Awesome to hear you're happy with it! 🎉

**Comment by jshjohnson** [comment]
Thanks @jeffijoe - out of interest how do you go about unit testing with that approach? For example if `dep1` was `lodash`, you would need to mock all lodash methods

**Comment by jeffijoe** [comment]
Don’t mock lodash. ;)

You can use `Pick<>` to only specify what you need. Or use functions. 😀
