### ISSUE TITLE
Custom Params on .resolve() for per-module local injections

### ISSUE THREAD

**Issue by pragmaticivan** [jeffijoe/awilix#148]
```js
export default function userRepository({ db, timeout }) {
  return {
    find() {
      return Promise.race([
        db.query('select * from users'),
        Promise.delay(timeout).then(() =>
          Promise.reject(new Error('Timed out'))
        )
      ])
    }
  }
}
```

I know I could do something like:

```js
const container = createContainer()
  // Using the fluid variant:
  .register({
    userRepository: asFunction(createUserRepository)
      // Provide an injection function that returns an object with locals.
      // The function is called once per resolve of the registration
      // it is attached to.
      .inject(() => ({ timeout: 2000 }))
  })
```

How can I do to pass a custom `timeout` every time I use the `.resolve` function?

```js
const userRepository = container.resolve('userRepository', {timeout: 123})
```

**Comment by pragmaticivan** [comment]
Is that something possible right now? @jeffijoe

**Comment by jeffijoe** [comment]
Weird, I am certain I responded to this 😮

You can do something like this:

```js
.register({
  createUserRepository: buildResolver({
    resolve: c => {
      return (timeout) => c.build(asFunction(createUserRepository).inject(() => ({ timeout })))
    }
  })
})
```

You can then use it like this

```js
function createUserService({ createUserRepository }) {
  const repo = createUserRepository(123)
}
```

**Comment by pragmaticivan** [comment]
Maybe that's something that deserves a place in the docs? Thank you very much!

**Comment by jeffijoe** [comment]
It's a rather hacky way of doing it, you really shouldn't have to. I personally think a more explicit way would be to register an actual factory that passes the parameters.

```js
.register({
  createUserRepository: asFunction(({ db }) => 
    (timeout) =>  createUserRepository({ db, timeout })
  )
})
```

**Comment by pragmaticivan** [comment]
What are your thoughts this approach for multi-tenant architecture?

```
clientDb |> plansRepository |> plansUseCase
```

Multiple domains will need to pass a custom param down to the repository constructor:

```
clientDb |> plansRepository(tenantId) |> plansUseCase (tenantId)
```
Would you still apply the same thing returning a function? because I was thinking about automating the the way I inject dependencies but just allow custom params to be merged to the constructor if they are expecting for that.

```
PlansRepository({ clientDb, tenantId}) |> PlansUseCase({ plansRepository, tenantId})
```

If I don't do something like that, `tenantId` will need to be a param for each function on UseCase.

**Comment by jeffijoe** [comment]
Where do you get the tenant ID? A middleware? If so, you can register it in the request scope.

**Comment by pragmaticivan** [comment]
Yes, that would be provided via middleware through HTTP transport.

Having the feeling I would need to replicate returning function for any Class that needs tenantId?

Something like perhaps?
```
.register({
 createPlansUseCase: buildResolver({
    resolve: c => {
      return (tenantId) => c.build(asFunction(createPlansUseCase).inject(() => ({ tenantId })))
    }
  })
  createPlansRepository: buildResolver({
    resolve: c => {
      return (tenantId) => c.build(asFunction(createUserRepository).inject(() => ({ tenantId })))
    }
  })
})
```


I was actually hoping for something like:

`const plansUseCase = req.container.resolve('plansUseCase', {tenantId});`

Where on resolve I could pass params not registered in the CI container. Wonder if there are plans for something like that in the future

**Comment by jeffijoe** [comment]
Why not simply do

```
const middleware = async (ctx, next) => {
  ctx.state.container.register('tenantId', asValue(ctx.header('Tenant-Id')))
  return next()
}
```

Now you can depend on `tenantId` directly without a factory.

**Comment by pragmaticivan** [comment]
You have a good point, per scope seems to be cleaner on that case, thanks!
