### ISSUE TITLE
What "as" for object?

### ISSUE THREAD

**Issue by akmalhazim24** [jeffijoe/awilix#154]
Hello,
I'm trying out Awilix and found out this is an amazing library. It reminds me the powerful PHP Laravel dependency injection pattern.

I'm checking out the asValue, asClass and asFunction. However, I'm confused on choosing the right "as" for an object. Considering I already have an invoked class and just want Awilix to return the object as-is, what is the correct "as" context for this?

Thank you very much for your time and effort.

**Comment by jeffijoe** [comment]
Thanks! You want to use asValue for that.
