### ISSUE TITLE
Calling container.resolve('someservice').method() "this" variable returns undefined

### ISSUE THREAD

**Issue by akmalhazim24** [jeffijoe/awilix#155]
Hello,
May I know why when I do this, `container.resolve('someservice').method()`, where `method()` needs to use `this`, `this` returns undefined.

Thanks

**Comment by jeffijoe** [comment]
That should work just fine, need a reproduction case.

**Comment by akmalhazim24** [comment]
I'm using Express. This is how I call my code
`router.post('/auth/login', f(container.resolve('passportController').login));`

**Comment by JamieCorkhill** [comment]
You shouldn't be manually injecting your dependencies with `container.resolve()` and should instead be utilizing [Awilix's Injection Modes](https://github.com/jeffijoe/awilix#injection-modes).

Have you seen [awilix-express](https://www.npmjs.com/package/awilix-express)? It will permit you to scope your container on a per-request basis and *inject* your dependencies automatically.

**Comment by jeffijoe** [comment]
You are passing the method directly, which makes it lose its' context unless you bind it elsewhere. `f(container.resolve('passportController').login)`.

But yes, see awilix-express.

**Comment by akmalhazim24** [comment]
Oh, that's great! Been reading and trying to understand the concept. Right now in my country, it's like mid-night. I'll try this morning after I woke up. Thanks for this amazing library @jeffijoe! You've helped slow developers like me a lot!

**Comment by akmalhazim24** [comment]
Hey @jeffijoe,
I've tried awilix-express and that works flawlessly. But I have a question, currently, my code is as the following:
`const passportController = makeInvoker(passportController)`
`router.get('/auth/login', f(passportController('login')))`

Notice that the `f()` wrapper is wrapping the invoker. If my router is growing with more routes, adding the `f()` wrapper will make the code look messy. I'm thinking of the following code:-
`const passportController = (method) => f(makeInvoker(passportController)(method))`
`router.get('/auth/login', passportController('login'))`

With the new code, it will wrap all the route that requires the invoker perfectly. But my concern, how is the performance gain and is it a best practice?

Thanks!

**Comment by akmalhazim24** [comment]
If you are wondering whats the purpose of 'f()', it is a async error-catcher since I'm return `Promise `instead of a normal `res.json()`.

**Comment by jeffijoe** [comment]
Awilix Express handles promises so you don’t have to. Closing as this is not an actual Awilix issue.
