### ISSUE TITLE
refreshing singleton objects registered with asFunction

### ISSUE THREAD

**Issue by moda20** [jeffijoe/awilix#156]
hey !

I am trying to create a configuration file for my system while using Awilix. the configuration is a JSON file returned from a factory function that I register with the container with asFunction and a singleton nature. 
What I want to do next is change the configuration file, manually or programmatically, and get the changed values into the config object received from the container in other classes. 

Right now, the configuration object resolved via the container doesn't change when I change the configuration JSON file. So how can I do that ?

I am using ` "awilix": "^3.0.9"`

**Comment by JamieCorkhill** [comment]
Can you tell me if I have this correct?

You have some factory function, registered `asFunction` in the container, that creates, generates, or writes to disk a JSON Configuration file, and that, somewhere along the line, you parse or deserialize that JSON file into a JavaScript `config` object, and when you modify that JSON File, either through your code or by hand, you want the resulting updates to be reflected within the `config` object?

**Comment by jeffijoe** [comment]
This does not sound like an Awilix problem. If you register it as singleton, then you can update that object however you see fit.

**Comment by JamieCorkhill** [comment]
@jeffijoe I was thinking that -  it sounds more like an infrastructural problem pertaining to updating the file.

@moda20 Off the top of my head, the Node `fs` API provides the `fs.watchFile` event/handler so you can watch for file changes. Short of that, maybe you can take an MD5 hash or some other checksum of the JSON File every time it is updated, and then read the file again and do a diff (re-hash and compare the hashes) at regular intervals (perhaps a cron-job) if you don't need immediate updates.

**Comment by moda20** [comment]
@JamieCorkhill yeah, but would the config object resolved from the container with a lifetime of singleton be able to update itself automatically? if I change the config JSON file and then, without rerunning my node instance, would I get a different config file from the container?

**Comment by JamieCorkhill** [comment]
Well, it's not going to update itself, so you'd have to update the object manually every time you see that the file has been modified.

**Comment by jeffijoe** [comment]
@moda20 if the config file changes, you would need to load it and assign its values to the instance.

Alternatively, use the default transient lifetime and load the configuration each time, then you always load whats on disk.

```js
function loadConfiguration() {
  return JSON.parse(fs.readFileSync('config.json'))
}

container.register({
  config: asFunction(loadConfiguration)
})
```

**Comment by moda20** [comment]
@jeffijoe elsewhere ? means any class or function that injects the config object would need to be transient too ? 
a quick question : would adding an fs file watch in the factory function returning the config object like @JamieCorkhill suggested, do the trick of an automatic refresh ? does aliwix use a sort of cache for singletons ?

**Comment by jeffijoe** [comment]
Singletons are by definition single instance, so yes, Awilix caches them. Yes, what Jamie suggests is what you want.

**Comment by jeffijoe** [comment]
You can probably do something like this:

```js
import fs from 'fs'

function Config() {
  const file = 'config.json'
  const cfg = {}
  load()
  fs.watchFile(file, load)
  return cfg

  function load() {
    const parsed = JSON.parse(fs.readFileSync(file))
    Object.assign(cfg, parsed)
  }
}

container.register({
  config: asFunction(Config).singleton()
})
```
