### ISSUE TITLE
Support class injections & setting parent dynamically.

### ISSUE THREAD

**Issue by overflowz** [jeffijoe/awilix#157]
Hi, first of all, I'd like to thank you for the great work! :)

I'd like to have support for two features if it's possible:

1. setting parent of the container dynamically (e.g. `container.setParent(otherContainer)`)
2. able to register classes... as classes ;p (e.g. `container.register(ClassA)`) without the need to specify a string.

Use cases:
The first one would be great when dealing with hierarchical tree (e.g. creating a custom decorator with default container inside and when bootstrapping, build up the relationship between them, like angular).

The second one would be great with the `emitDecoratorMetadata` feature of typescript, also like angular is resolving the dependencies.

If you have any questions, please let me know since English is not my native language.

Thank you! :)

**Comment by jeffijoe** [comment]
1. I don't know the use case for this, but to me it smells like over-engineering and trying to be too clever. The DI container should not require much interaction beyond initial registration of modules and resolving a root.
2. I don't feel comfortable adding decorator-based stuff to core, but this is something you can do yourself with a function that takes the container and the class as a parameter.

**Comment by overflowz** [comment]
Hi!

#1 helps to maintain decorators easily. e.g. you have decorators defined on each module (like angular) and then when bootstrapping, build a relationship in that way.

#2 I will still need to transform class somehow into a string to be able to do that since resolver does not support resolving with classes but only strings/symbols (or can I create custom resolver too?)

Thank you!

**Comment by jeffijoe** [comment]
Supporting these would go against Awilix’ core principle of the DI mechanism being invisible in application code. From what I can tell, and I apologize if I’m mistaken, you are over-complicating your DI setup.

**Comment by overflowz** [comment]
> DI mechanism being invisible in application code.

Yeah, this makes sense. As for the overcomplication, I am trying to write a library that acts just like angular's module system, I thought how could I do that with awilix, but the only ideas I came that is will be much easier to do for me was those two features 😄

Anyway, You might be right that I am overcomplicating it but I dunno how to do that in another way 😋 

Closing this and Merry Christmas!

**Comment by jeffijoe** [comment]
Merry Christmas!
