### ISSUE TITLE
Type error when registering classes programically

### ISSUE THREAD

**Issue by dschuessler** [jeffijoe/awilix#158]
In my project I use Typescript and a lot of singletons. Instead of having a long list of calls to `asClass` I tried to register them programatically from a list of classes. This is an example:

```Typescript
import { asClass, createContainer, InjectionMode, Lifetime } from "awilix"

class A {
    public a: number;
}

class B {
    public b: number;
}

class C {
    public c: number;
}

const dependencies = [A, B, C];

const container = createContainer({
    injectionMode: InjectionMode.CLASSIC
}).register(
    Object.fromEntries(
        dependencies.map(dependency => [
            dependency.constructor.name.toLowerCase(),
            asClass(dependency, { lifetime: Lifetime.SINGLETON })
        ])
    )
);
```

Unfortunately I get this type error when trying to call `asClass`:

```
Argument of type 'typeof A | typeof B | typeof C' is not assignable to parameter of type 'Constructor<A>'.
  Type 'typeof B' is not assignable to type 'Constructor<A>'.
    Property 'a' is missing in type 'B' but required in type 'A'.
```

I see no reason why `asClass` should be expecting the type `Constructor<A>`, thus I suspect a wrong type definition on your side, but I'm glad for any help I can get on this.

I created a repository for easy reproduction: https://github.com/dschuessler/awilix-type-error-example/tree/master

**Comment by jeffijoe** [comment]
What if you do this?

```ts
const dependencies: Constructor<any>[] = [A, B, C];
```

**Comment by dschuessler** [comment]
This indeed solves the problem. Thanks for your quick assistence.
