### ISSUE TITLE
Question: Class extends from registry

### ISSUE THREAD

**Issue by tehnorm** [jeffijoe/awilix#159]
We really love awilix and have pretty much starting using at the default DI tool for all js projects to we work on. Thank you so much for creating it!

I am wondering, is there a way to have awilix find a dependency via the extends keyword? To achieve that currently we do something like this:

```
const CalibrationProcessDefinition = cradle => class CalibrationProcess extends cradle.pouchInterfaceDefinition {
	constructor(innerCradle) {
		super(innerCradle, 'calibration_process');
	}
};

module.exports = CalibrationProcessDefinition;
```

In our registry we map two versions of each dependency (in most cases) as `calibrationProcessDefinition` and `calibrationProcess` in this particular instance.

```
_createMapping = (module, lifetime) => {
        const mod = require(module.path);
        const definition = `${camelCase(module.name)}Definition`;

        mappings[definition] = asFunction(
                mod,
                { lifetime },
        );

        mappings[camelCase(module.name)] = asClass(
                class {
                        constructor(cradle) {
                                const c = cradle.registry.resolve(definition);
                                if (c.length > 1) {
                                        throw new Error(`${c.name} defined as Factory but resolved as Class.`);
                                }
                                return cradle.registry.build(c);
                        }
                },
                { lifetime },
        );
};
```

Is there anyway to instead have something like:

```
class CalibrationProcess extends cradle.pouchInterfaceDefinition {
	constructor(innerCradle) {
		super(innerCradle, 'calibration_process');
	}
};

module.exports = CalibrationProcess;
```

We've thought about using the Composition pattern vs Inheritance but it ends up with tons of pass through methods and duplication in our case. https://en.wikipedia.org/wiki/Composition_over_inheritance

If you have any thoughts or ideas that we are missing we'd love your expert opinion.

My next move was going to be to monkey patch `require` and feed in a version that creates a wrapper that includes the `registry/cradle` object at runtime via `options.require` in `createContainer()` so that extends would have access to `cradle.pouchInterfaceDefinition`.

**Comment by jeffijoe** [comment]
Thanks!

This definitely smells like trying to be too clever, I have no idea what's going on there 😅

Don't be afraid of some duplication, I've seen DRY taken to the extreme.

**Comment by tehnorm** [comment]
To simplify: Is there anyway that `InterfaceDefinition` can come from a registry?

```
class CalibrationProcess extends InterfaceDefinition {
	constructor(registry) {
		super(registry);
	}
};

module.exports = CalibrationProcess;
```

**Comment by jeffijoe** [comment]
Why do you need it to? You really shouldn't be doing that.

**Comment by tehnorm** [comment]
Gotcha. Could you elaborate on why that shouldn't be done? Is there a better way to inherit or reuse functionality?

This is a more likely example:
```
class CalibrationProcess extends EventEmitter {
	constructor(registry) {
		super();
	}
};

module.exports = CalibrationProcess;

**Comment by jeffijoe** [comment]
You can compose objects instead of using classes. Or you can inject the functionality you need and expose as a facade. Anything that does not require the use of magic. 😄 

What is your concrete use case?

**Comment by tehnorm** [comment]
Interesting. So to be clear, with Awilix there isn't a clean way to use the es6 keyword `extends` and should be considered an anti-pattern?

A concrete use case would be extending `EventEmitter`.

**Comment by jeffijoe** [comment]
You can extend `EventEmitter` without any DI. You shouldn't use `extends` in any magical way as you were trying to do. 😉

**Comment by tehnorm** [comment]
Sure, but that would mean needing a require() in the file correct? Isn't that considered anti DI? That would mean that it would be hard to mock or test `EventEmitter`?

```js
const EventEmitter = require('events');

class CalibrationProcess extends EventEmitter {
	constructor(registry) {
		super();
	}
};

module.exports = CalibrationProcess;
```

**Comment by jeffijoe** [comment]
Why would you mock or test `EventEmitter`? It's completely fine to have hard dependencies. You want to inject the things you might actually want to swap out, or separate cleanly. Extending event emitter is perfectly fine.

**Comment by tehnorm** [comment]
Fair point. Still feels icky. What about an interface class that does need to get swapped out but is extended from?

**Comment by jeffijoe** [comment]
Trust me, once you've gone off the deep end with DI, you will find such simplicity pleasing. 😄

Sometimes you need to stop and ask yourself "am I doing this because I should or because I can?"

**Comment by tehnorm** [comment]
I'm trying to do it so that I can swap things out for testing. The other reason is that `extends` is explicit and very easy for other developer to follow. Facades and composition are not. They are a form of indirection.

We are half a million lines in with DI using Awilix. We do appreciate the simplicity. If it can't be done that is fine. I am still not seeing why it shouldn't be done other than opinion.

**Comment by jeffijoe** [comment]
Boring straight-forward code is easy to follow

Magic is easy to follow for the person who built it. Don't be afraid of some duplication, sometimes the alternative is unnecessary complexity.

I strongly recommend [this talk by Greg Young](https://www.infoq.com/presentations/8-lines-code-refactoring/).
