### ISSUE TITLE
Auto-resolve loadModules result (Mongoose model registration issue)

### ISSUE THREAD

**Issue by andrey-hohlov** [jeffijoe/awilix#160]
I stuck with the Mongoose model registration and came to this issue.

@JamieCorkhill proposed the solution https://github.com/jeffijoe/awilix/issues/142#issuecomment-517940063

```javascript
const mongoose = require("mongoose");

const schema = new mongoose.Schema({});
const User = mongoose.model("User", schema);

module.exports = User;
```

But it doesn't fit my requirements because it doesn't allow use dependency injection in the model registration function.
For example, I want to use some functions from a container inside model methods.
From another side, if I export registration function - I don't have the model until it's not resolved somewhere.

```javascript
module.exports = ({ mongoose }) => {
  const schema = new mongoose.Schema({});
  return mongoose.model("User", schema);
};
```

In my case, it breaks [population](https://mongoosejs.com/docs/populate.html) when schema property contains a reference to another model.

```javascript
module.exports = ({ mongoose }) => {
  const schema = new mongoose.Schema({
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User', 
    },
  });
  return mongoose.model("Document", schema);
};
```
User model registered in the container, but not resolved at the moment when Document requested and populate called.

So, in case I need to have DI inside mongoose models I have to manually resolve models.

I'm new in DI and maybe I miss some core principles. But I have some ideas how to support this case in Awilix:

1. container.loadModules() can return a list of loaded modules names. Then we can manually resolve them. 

2. container.loadModules() can have ```autoResolve``` option.

For now, I use this workaround:

```javascript
// This is a method in Application class used for loading models/controllers/services on initialization
loadModules(globPatterns, options = {}, autoResolve = false) {
  const loadedModules = [];

  const formatName = (name, descriptor) => {
    let result = name;

    if (typeof options.formatName === 'function') {
      result = options.formatName(name, descriptor);
    } else if (options.formatName === 'camelCase') {
      result = _.camelCase(name);
    }

    loadedModules.push(result);

    return result;
  };

  // this.container is Awilix container
  this.container.loadModules(globPatterns, {
    resolverOptions: {
      lifetime: awilix.Lifetime.SINGLETON,
    },
    ...options,
    formatName,
  });

  if (autoResolve) {
    loadedModules.forEach((module) => {
      this.container.resolve(module);
    })
  }
}
```

**Comment by jeffijoe** [comment]
Firstly, I would strongly suggest you keep your model clean of dependencies.

If you insist on doing it anyway, just register the models manually and resolve them after the fact.

```js
function registerModels(container) {
  const modelFactories = {
    User: require('../models/User'),
    Document: require('../models/Document')
  }

  // Register
  Object.entries(modelFactories).forEach(
    ([name, fac]) => 
      container.register({
        [name]: asFunction(fac).singleton() 
      })
  )

  // Resolve now
  Object.keys(modelFactories).forEach(key => container.resolve(key))
}
```

**Comment by andrey-hohlov** [comment]
Thanks for examples.
Also, I can use ```awilix.listModules``` method to get all models from a folder. Maybe it's better than my trying to keep ```formatName``` feature.

I just thought the conception of auto-resolving can be useful 🤷‍♂️

P.S. @jeffijoe can you please give me advice - why is it better to keep model clean of dependencies? Mongoose models can have big functionality - hooks, methods, etc.

**Comment by jeffijoe** [comment]
In my opinion, your model should be pure domain logic, anything else should be handled by the application layer. I personally wouldn't use all those things Mongoose gives you, but that is up to you.

Auto-loading can be useful but it can also be the source of many bugs. Explicit registration is boring, but that also means everybody can understand it. 😄

**Comment by andrey-hohlov** [comment]
Thank you!
