### ISSUE TITLE
Question: How can I make a service shared between two containers ?

### ISSUE THREAD

**Issue by agarwalkartik** [jeffijoe/awilix#161]
Hey,

I am using awilix to create **two containers** in my app, both of which have **different database** connections (and other third party services). Now, I have to make an **http server** which should allow **using containers based on the routes**. For eg: all the routes with prefix `/app1` should use `container1` and all the routes with prefix `/app2` shall use `contaner2`. Note that the sub routes, controllers, etc of both `/app1` and `/app2` are same, its just that they should use different containers. Any idea on how to implement this would be helpful.

Thanks.

**Comment by jeffijoe** [comment]
Yes, something like `app.use('/app1', scopePerContainer(container`))`. You can probably write middleware that does this if that doesn't work.
