### ISSUE TITLE
Re instantiate a class

### ISSUE THREAD

**Issue by ksromero** [jeffijoe/awilix#162]
Hi I'm a little bit confused since I'm using this package for the first time and I'm using this with Bookshelf.js / Knex.js

This is my database to be able to use the **bookshelf**
```
import knexInit from './dbInit';

import bookshelfJs from 'bookshelf';

const bookshelf = bookshelfJs(knexInit);

bookshelf.plugin(['bookshelf-eloquent'])

export default bookshelf;
```

I imported the **bookshelf** to be able to extend it on my User model
```
import bookshelf from '../database/bookshelf';

const TABLE_NAME = 'users';
const ID_ATTRIBUTE = 'id';
const HIDDEN =  [];

class User extends bookshelfInit.Model {
  get tableName () {
    return TABLE_NAME;
  }

  get hidden() {
    return HIDDEN;
  }

  get idAttribute() {
    return ID_ATTRIBUTE;
  }
}
```
Now on my service I'm importing the User class model **without using the package**, like this
```
import User from '../models/user'; //import user model

class UserService  {
  async createUser(request, response) {
    const data = request.body;
    try {
      const result = await new User().save(data, {method: 'insert'}); // instantiate User model
      return response.json({
        data   : result,
        result : true
      });
    } catch (e) {
      return response.json({
        result: false,
        errorMsg   : e.sqlMessage,
      })
    }
  }
}
```

Now I can successfully create a User without a problem, As it continuously re instantiate the User model.

Now when I use this package

```
import User from '../models/user';
import UsersService from '../services/usersService';

 /**
 * User Model
 */
export const user = {
    user : asClass(User).classic().singleton()
}

 /**
 * Users Service
 */
export const usersService = {
    usersService: asClass(UsersService).singleton()
}
```

this is how I create a container 

```
import { createContainer } from 'awilix';
import * as usersModule from './usersModule';

export const container = createContainer();

container
    .register(userModule.user)
    .register(userModule.usersService)
```
and this is how I resolved it

```
import { container } from '../di/container';

const UserService = container.resolve('UserService');

//UserService.createApp
```

My UsersService would look like

```
class UsersService  {

  /**
   * Constructor
   */
  constructor({user}) {
    this.user = user;
    autoBind(this);
  }

  async createUser(request, response) {
    const data = request.body;
    try {
      const result = await this.user.save(data, {method: 'insert'}); // I used the this.user here
      return response.json({
        data   : result,
        result : true
      });
    } catch (e) {
      return response.json({
        result: false,
        errorMsg   : e.sqlMessage,
      })
    }
  }
}
```

Now I can successfully save the user data, but the problem is I can only save the user data on the first try however on the next tries, I cannot save because I'm having a duplication error 

`"Duplicate entry '8' for key 'PRIMARY'"`

It feels like the `this.user` keeps re-using the **user model** without re instantiating it again.

**Summary:**
**Difference**
**Without Package** - I can successfully saved the user data without having any problem
**With Package**      - I can only saved user data on first try only since **this.user** is not reinstantiating  again. I'm having duplication errors on insertion since it keeps reusing the **this.user**

**Comment by JamieCorkhill** [comment]
By using the Awilix `asClass` resolver, you're telling Awilix to instantiate the given function with the `new` operator and then provide that instance to the classes/functions that require it.

If you want to be able to re-instantiate `user` yourself on every invocation of the service function, consider registering the model `asValue`, and then instantiate it yourself.

That registration would look like this:

```javascript
container.register({ user: asValue(User) });
```

And you'd instantiate the model like this:

```javascript
// UserService.js
(new this.user()).save(/* ... */);
```

**Comment by ksromero** [comment]
thank you @JamieCorkhill it worked!

**Comment by JamieCorkhill** [comment]
You're welcome, @ksromero. I'm glad it works.
