### ISSUE TITLE
Proper way to extend EventEmitter

### ISSUE THREAD

**Issue by mathieug** [jeffijoe/awilix#163]
There is a new parameter `opts` on the EventEmitter constructor.
My issue since a recent a node update: https://runkit.com/embed/vomvrzfoeuob

What's the proper way to ignore this constructor parameter? Should I use .proxy() or .inject()?

**Comment by jeffijoe** [comment]
Are you inheriting `EventEmitter`?

**Comment by mathieug** [comment]
> Are you inheriting `EventEmitter`?

Yes, check the runkit (which uses a recent version of Node.js)

**Comment by jeffijoe** [comment]
Ah, so Awilix will scan the base class constructor if the constructor in your class is empty. You can simply do `constructor({})`, that should fix it.
