### ISSUE TITLE
Make AwilixContainer generic

### ISSUE THREAD

**Issue by roikoren755** [jeffijoe/awilix#167]
As of now, the `cradle` property on the `AwilixContainer` interface is typed as `any`. It would be helpful, in my opinion, if it accepted an optional generic parameter to type the cradle. 

The simple, dumb solution would be to simply change the signature of the interface to `export interface AwilixContainer<T = any> { ... }`. Other than this change, would it be too difficult to implement it so that the creation function would pass the generic parameter? I'm willing to work on a PR, I would just appreciate some direction as to where to start and what should I change.

Thanks

**Comment by jeffijoe** [comment]
I think that would be too big a change due to the `Constructor` and `FunctionReturning` types needing to work for both Proxy and Classic.

**Comment by roikoren755** [comment]
If you are not opposed to the change in general, I'll try and give it a go over the weekend, and update this issue when I have more information

**Comment by jeffijoe** [comment]
Feel free to try, as long as it does not break the existing ecosystem (`awilix-koa`, `awilix-express`).

**Comment by roikoren755** [comment]
I opened a PR with this change [https://github.com/jeffijoe/awilix/pull/169](url)
