### ISSUE TITLE
Question: When is a module registered as a `Class` is instantiated in awilix

### ISSUE THREAD

**Issue by agarwalkartik** [jeffijoe/awilix#170]
If I register a module like this `mongo: awilix.asClass(Mongo, { lifetime: awilix.Lifetime.SCOPED })` when will the instance of class `Mongo` be created by awilix. Is it created as soon as we register the module or when some other module resolves it as a dependency? Slightly confused here. Also is this behaviour changed when using different lifetime types ?

**Comment by agarwalkartik** [comment]
> There are 3 lifetime types available.
> 
> Lifetime.TRANSIENT: This is the default. The registration is resolved every time it is needed. This means if you resolve a class more than once, you will get back a new instance every time.
> Lifetime.SCOPED: The registration is scoped to the container - that means that the resolved value will be reused when resolved from the same scope (or a child scope).
> Lifetime.SINGLETON: The registration is always reused no matter what - that means that the resolved value is cached in the root container.

This part of documentation makes it pretty clear about how many classes are made for each type of lifetime, bu my question is about when exactly these classes are instantiated.

**Comment by jeffijoe** [comment]
Resolve = instantiate. How could it possibly be created on register if using any other lifetime than singleton? 😄

**Comment by agarwalkartik** [comment]
"How could it possibly be created on register if using any other lifetime than singleton", yes this makes sense, I should have thought about this earlier. :). Thanks

**Comment by jeffijoe** [comment]
No problem, happy to help. :)
