### ISSUE TITLE
Conditoinal Injection

### ISSUE THREAD

**Issue by vipreshjha** [jeffijoe/awilix#174]
Let's say I have a class called RedisKeys and many sub-classes of this.
Now based on different conditions  I want a different sub-class to be injected in different services.
For eg., there are multiple services like "EntityDataStore", "FilterDataStore".
EntityDataStore needs EntityRedisKeys & FilterDataStore needs FilterRedisKeys, but both of them have a constructor argument named redisKeys.

Coming from .Net backGround, Something like this is available in NInject.
https://github.com/ninject/Ninject/wiki/Contextual-Binding
for eg.
`Bind<IWarrior>().To<Samurai>().WhenInjectedInto(typeof(OnLandAttack));
Bind<IWarrior>().To<SpecialNinja>().WhenInjectedInto(typeof(AmphibiousAttack));
`

The current framework ("intravenous") I am using its possible , would be nice to have this feature in awilix.

**Comment by jeffijoe** [comment]
You can do this with `inject`.


```ts
container.register({
  entityDataStore: asClass(EntityDataStore).inject(c => ({ entityKeys: c.resolve('entityRedisKeys') }))
})
```

**Comment by vipreshjha** [comment]
> You can do this with `inject`.
> 
> ```ts
> container.register({
>   entityDataStore: asClass(EntityDataStore).inject(c => ({ entityKeys: c.resolve('entityRedisKeys') }))
> })
> ```

The "EntityDataStore" has other dependencies apart from the "redisKeys" will they work or I will have to list all of them in the "inject" method?
If it's latter then it will be complicated and defeat the purpose.

**Comment by jeffijoe** [comment]
Nope, that's the point of `inject`, it's just to specify specific ones.
