### ISSUE TITLE
Injecting array of all registered classes for interface?

### ISSUE THREAD

**Issue by robodude666** [jeffijoe/awilix#176]
Howdy,

I'm curious if it's possible to do something like this:

```typescript

export class UserCreatedHandler implements EventHandler { }
export class PostCreatedHandler implements EventHandler { }
export class CommentCreatedHandler implements EventHandler { }

// ..

container.register({
  userCreatedHandler: asClass(UserCreatedHandler),
  postCreatedHandler: asClass(PostCreatedHandler),
  commentCreatedHandler: asClass(CommentCreatedHandler),
})

// ...

export class EventSubscriber {
  constructor(
    private readonly eventHandlers: EventHandler[]
  ) {}
}
```

I'm guessing not, and you'd have to register it as a single `eventHandlers`, but how do you register an array of handlers if the handlers have dependencies that need to be resolved?

Thanks,
-robodude666

**Comment by jeffijoe** [comment]
You can [create a resolver](https://github.com/jeffijoe/awilix/issues/80#issuecomment-365033070) that does this.

**Comment by robodude666** [comment]
Thanks! I guess this points to the README not mentioning (or if it does, not making it obvious) the ability to recreate custom resolvers.

**Comment by jeffijoe** [comment]
I typically don't want to encourage people to do overly fancy things with their DI setup as it's easy to fall into a complexity trap, so I didn't document it. ;)
