### ISSUE TITLE
demo of a DRY declaration

### ISSUE THREAD

**Issue by moltar** [jeffijoe/awilix#177]
With the addition of #169 (thanks @roikoren755!), it is now possible to create a DRY container with type support.

It took me a while to figure out the `Container` type, so I just want to document it here, and also get a sanity check.

```ts
import { createContainer, asClass, asFunction, asValue } from 'awilix'

export function helloWorld() {
  return 'hello world'
}

class Foo {
  num = 42
}

const registrations = {
  foo: asClass(Foo),
  bar: asFunction(helloWorld).singleton(),
  val: asValue(1),
}

type Container = {
  [P in keyof typeof registrations]: ReturnType<typeof registrations[P]['resolve']>
}

const container = createContainer<Container>()

container.register(registrations)

console.log(container.cradle.bar)
console.log(container.cradle.foo.num)
console.log(container.cradle.val)
```

**Comment by moltar** [comment]
One thing I wish I could figure out to make this better, is to have a type for `registrations` variable. I tried typing it with `NameAndRegistrationPair`, but can't figure it out.

**Comment by moltar** [comment]
Bonus: resolve function that does not require a generic input.

```ts
function resolve<K extends keyof Container>(key: K, resolveOptions?: ResolveOptions) {
  return container.resolve<Container[K]>(key, resolveOptions)
}

// param (key) is typed, return is also typed
const foo = resolve('foo')
```

**Comment by jeffijoe** [comment]
> One thing I wish I could figure out to make this better, is to have a type for registrations constant. I tried typing it with NameAndRegistrationPair, but can't figure it out.

Maybe something like:

```ts
type Registrations = {
  [P in keyof Container]: Resolver<Container[P]>
}
```

NOTE: I didn't test this.

**Comment by jeffijoe** [comment]
Yes, `SomeTypeHere` = `Registrations`

**Comment by moltar** [comment]
But that's circular, because `Container` type does not exist before `registrations` is created.

**Comment by jeffijoe** [comment]
Or you can use `RegistrationHash`.

**Comment by moltar** [comment]
That worked. But it made it worse, because all of the values are `Resolver<any>` now. :)

I think it's better to keep it un-typed.

**Comment by jeffijoe** [comment]
Yeah I wouldn't bother. If you use anything but a resolver anyway, you won't be allowed to call `register`.

**Comment by moltar** [comment]
Another interesting option. Factory function pattern.

```ts
function create<T extends Record<string, Resolver<any>>>(registrations: T) {
  const container = createContainer<
    {
      [K in keyof T]: ReturnType<T[K]['resolve']>
    }
  >()

  return container.register(registrations)
}

const cont = create({
  foo: asClass(Foo),
  bar: asFunction(helloWorld).singleton(),
  val: asValue(1),
})

//                      ↓ this is typed now
console.log(cont.cradle.bar)
```

<img width="685" alt="Screen-Shot-2020-04-12-22-56-56" src="https://user-images.githubusercontent.com/491247/79073451-eac5c600-7d10-11ea-89bb-4d42edbd9b15.png">

**Comment by roikoren755** [comment]
Sorry for the delay, the following should work

```
import { createContainer, asClass, asFunction, asValue } from 'awilix';

export function helloWorld() {
  return 'hello world';
}

class Foo {
  num = 42;
}

const registrations = {
  foo: asClass(Foo),
  bar: asFunction(helloWorld).singleton(),
  val: asValue(1),
};

interface IContainerOptions {
  foo: Foo;
  bar: string;
  val: number;
}

const container = createContainer<IContainerOptions>();

container.register(registrations);

console.log(container.cradle.bar);
console.log(container.cradle.foo.num);
console.log(container.cradle.val);

```

**Comment by roikoren755** [comment]
And then, in the factory example, the following is correctly typed
```
function create<T extends Record<string, any>>(registration: NameAndRegistrationPair<T>) {
  const container = createContainer<T>();

  return container.register(registration);
}

const cont = create({
  foo: asClass(Foo),
  bar: asFunction(helloWorld).singleton(),
  val: asValue(1),
});

//                      ↓ this is typed now
console.log(cont.cradle.bar);
```

**Comment by moltar** [comment]
@roikoren755 but in your first example you have to redefine `IContainerOptions`. The point of my exercise was to avoid having to redefine the interface, and infer the interface from the registration itself.

As for the second example - that is great that it can be simplified even further! Thanks for that :)

**Comment by roikoren755** [comment]
> @roikoren755 but in your first example you have to redefine `IContainerOptions`. The point of my exercise was to avoid having to redefine the interface, and infer the interface from the registration itself.

That is true, but I'm not sure how you can specify a type for the `registration` const otherwise.

As for inferring the interface when creating the container, that can also be problematic, since the creation of the container (and the decision on the type of the cradle) is separate from the call to register.

**Comment by moltar** [comment]
> since the creation of the container (and the decision on the type of the cradle) is separate from the call to register.

I am sorry, I am not following. Could you please make an example?

Thanks!

**Comment by moltar** [comment]
How about this? A registration factory:

```ts
function createRegistrations<T extends Record<string, Resolver<any>>>(registrations: T) {
  return registrations
}

const regs = createRegistrations({
  foo: asClass(Foo),
  bar: asFunction(helloWorld).singleton(),
  val: asValue(1),
})
```

The params are type checked, and therefore not possible to supply an invalid value:


<img width="589" alt="Screen-Shot-2020-04-13-14-40-35" src="https://user-images.githubusercontent.com/491247/79102340-be538d80-7d94-11ea-919b-ba4cca683f65.png">

**Comment by roikoren755** [comment]
If you give typescript the chance to infer the types, it should work, but you need a function for that.

About the question, once you do `const container = createContainer()`, `container.cradle`'s type is any, and you cannot pass any registration const you have created as a parameter, meaning the cradle's type cannot be inferred from registration. This means that you must pass a type to the createContainer call (`createContainer<SomeTypeHere>()`). The type that needs to be passed is the type you expect to have on the cradle, not the `container.register` method's parameter type.

This means that the call to `createContainer` should be typed. That type is not obvious to create without duplicating the definition of the registration const, though the method you showed in the first comment on the issue does work.

**Comment by moltar** [comment]
> one that returns a typed container is probably more useful than one that returns a typed registration.

I just wanted to make sure that the registration object is being type checked, that is why I added `createRegistrations` function. Because you can call `register` multiple times, but if you return a ready-made containers, then you can no longer type the new registrations.

E.g.:

```ts
const container = create({})

container.register({
  // this param is not being type checked
})

// while if I did
container.register(createRegistrations({
  // this param is now type checked
}))
```

> About the question, once you do const container = createContainer(), container.cradle's type is any, and you cannot pass any registration const you have created as a parameter, meaning the cradle's type cannot be inferred from registration. This means that you must pass a type to the createContainer call (createContainer<SomeTypeHere>()). The type that needs to be passed is the type you expect to have on the cradle, not the container.register method's parameter type.

But that was the point of my original post. I have figured out a way to infer the type from the registration itself. If you try the code from my original post, you'll see that cradle is in fact typed.

I am giving it a generic param type `Container`, which is inferred from the `registration` contents.

**Comment by roikoren755** [comment]
> But that was the point of my original post. I have figured out a way to infer the type from the registration itself. If you try the code from my original post, you'll see that cradle is in fact typed.
> 
> I am giving it a generic param type `Container`, which is inferred from the `registration` contents.

As I said, what you did does the trick.

About subsequent calls not being type-checked, that's true, but in your example, the type of `container.cradle` is any. In fact, unless you create a type that includes everything you plan on registering and use it when creating the container, you won't ever get the right type

**Comment by jeffijoe** [comment]
Closing as it's not an issue per se.

**Comment by moltar** [comment]
Hey Jeff, would you be open to integrating any of these ideas into the project?

**Comment by jeffijoe** [comment]
I’d be happy to accept a PR for a section in the readme with the preferred approach, whichever one you two decide that is. I don’t think adding it to core makes much sense since loadModules will never be typed and it seems most people use autoloading.

**Comment by roikoren755** [comment]
Thanks for listening to my input on the subject. I have no objection against @moltar 's solution. I will however describe our use case a little bit better.
In small containers, like all the ones in the examples in this issue, there is no need to duplicate the registration definition, as pointed out. In our use case, however, we have around 10-15 services, each with its own container. Each container has between 5-20 different fields on the cradle, each defined in a separate file, some reaching a couple of hundreds lines of code. Most of these are registered `asFunction`, with a simple function type defined in a common interfaces file, that defines both the type of the cradle and a create function, that provides typings for the regitration function.
For example -

```
// interfaces.ts
export interface ICradle {
  foo: number;
  bar: string;
  baz: boolean;
}

export type Create<T> = (cradle: ICradle) => T;

// foo.ts
export const createFoo: Create<number> = () => 6;

// bar.ts
export const createBar: Create<string> = ({ foo }) => foo > 5 ? 'foo' : 'bar'; // foo is known to be a number here

// baz.ts
export const createBaz: Create<boolean> = ({ foo, bar }) => foo % 2 === 0 && bar === 'foo'; // foo is known to be a number, bar is known to be a string
```

In each `create*` function, all parameters are properly typed. Using @moltar 's method, the cradle will not be typed when passed as a parameter to these functions, as that will lead to circular dependency, having to import a type from a file that uses these functions.

**Comment by moltar** [comment]
FYI I didn't mean to modify anything existing. I thought we could maybe add a helper factory function(s) that can be use optionally.

**Comment by jeffijoe** [comment]
Still, I'd rather not add anything to the library that indicates it's a TS-only thing. If you want to create an `awilix-ts-helpers` package be my guest though. 😄
