### ISSUE TITLE
createScope should return container type by default

### ISSUE THREAD

**Issue by moltar** [jeffijoe/awilix#178]
https://github.com/jeffijoe/awilix/blob/7625dd94e6697621aad21d295afa13c0331db2bf/src/container.ts#L45

If you create a scoped container without a generic type, the return type of the new container is `any`

```ts
interface Foo {
  foo: string
}
const container = createContainer<Foo>()

// scoped has AwilixContainer<any> type
const scoped = container.createScope()
```

I think the type should be:

```ts
createScope<T extends object = {}>(): AwilixContainer<Cradle & T>
```

**Comment by jeffijoe** [comment]
I'm ok with that. Feel free to submit a PR.

**Comment by moltar** [comment]
Will do tomorrow.
