### ISSUE TITLE
[Question] Using loadModules(), when are modules actually resolved?

### ISSUE THREAD

**Issue by TdyP** [jeffijoe/awilix#18]
Hi,
I've one question about this wonderful lib:
I load most of my modules using `loadModules()`. All these modules are functions returning an object.
In some of these modules, I call a function to init some stuff, like this:
```javascript
module.exports = ({ someDeps }) => {
    
    initStuff();

    return { /* Modules properties... */ };
}
```

When all modules are loaded, I'd like to call a function which needs all the `initStuff()` calls to be done.
```javascript
container.loadModules([
    'server/services/**/!(*.spec).js'
], {
    formatName: 'camelCase',
    registrationOptions: {
        lifetime: awilix.Lifetime.SINGLETON
    }
});

doSomethingUsingStuff(); // This one needs all modules to be loaded
```

From my tests, `doSomethingUsingStuff()` is called before the modules' functions are actually called.
So, my question is: when are the modules resolved? Is it when `loadModules()` is called or later, when it's injected somewhere?

Hope my question makes sense :)

Thanks!

**Comment by jeffijoe** [comment]
Modules are only _loaded into_ the container so they are ready to be instantiated when needed.

Let's take the following as an example:

```js
// userService.js
module.exports = ({ userRepository }) => {
  return {
    createUser: (data) => userRepository.create(data)
  }
}

// userRepository.js
module.exports = ({ userRepository }) => {
  return {
    create: (data) => ... save data somehow
  }
}
```

When you use `loadModules`, the modules are registered with the container, _ready to be instantiated on demand_.

```js
const service = container.resolve('userService') // creates userService and userRepository
```

Or..

```js
const service = container.cradle.userService // creates userService and userRepository
```

Does that help?

**Comment by TdyP** [comment]
Yes, this helps and answers my question :)

Thank you!

**Comment by jeffijoe** [comment]
You are most welcome!
