### ISSUE TITLE
Destructuring injection in scope

### ISSUE THREAD

**Issue by AlanFonderflick** [jeffijoe/awilix#183]
Hi,

As a newcomer in DI, I'm very enthousiast to avoid all my ./index.js files with it. However, I'm still confuse for this user case :

I wait to log my requestId in my logger. A scoped container seems to be the best solution, as a requestId is created each request. 
However, I don't understand how to instanciate the scoped container in my controllers. 

```js
//Sample of app.js
container.loadModules([
	['models/**/*.js', {
           register: asValue,
           lifetime: Lifetime.SINGLETON,
        }],	
       ['utils/**/*.js', {
          register: asValue
        }],
	**'controllers/**/*.js',**
	'routes/**/*.js',
	'config/**/*.js',
	'loaders/**/*.js',
	'services/**/*.js'], {
  resolverOptions: {
    formatName: 'camelCase',
    injectionMode: InjectionMode.PROXY,
    lifetime: Lifetime.SCOPED
  }
});

//Setting a middleware
app.use((req, res, next) => {
  const requestContainer = container.createScope();
  const requestId = uuidv4();
  requestContainer.register('requestId', asValue(requestId))
  return next()
});

//userController.js
class UserController {

  constructor({userService, requestId}) {
    this.userService = userService;
    this.requestId = requestId;
  }

//...
}
module.exports = UserController ;
```
Obviously, I'm getting a `AwilixResolutionError: Could not resolve 'requestId'.`. I'm not sure how to create properly my scope and use destructuring to use my requestId in my files (or with my logger configurations). I guess I could use a `req.scope`as explained in some other examples, and resolve it, but is it really the only way or am I missing something ?

Thanks a lot :)

**Comment by jeffijoe** [comment]
If you use `awilix-express` it will do this for you. Otherwise you need to `container.build(UserController)` on every request (use `asClass` and cache that in a scope). That's basically what `awilix-express` does.

**Comment by AlanFonderflick** [comment]
Hi,

Thank you for responding. It's a work in progress.
However, I'm really wondering what is the meaning of Lifetime.SCOPED ?
I thought it was the key for container scoping but it turns that it is not finally not required in my code. I guess I may miss something ?

I'm also having trouble with .scoped(), `asValue(requestId).scoped()` seems to not be a function, I'm wondering why.

**Comment by jeffijoe** [comment]
Please [see the docs around scoped lifetime.](https://github.com/jeffijoe/awilix#scoped-lifetime)

`asValue` does not have `.scoped()` (or any lifetime choices) because it is by nature always going to return the same value, so there's no point in assigning it a lifetime.
