### ISSUE TITLE
Loadmodule not working with models

### ISSUE THREAD

**Issue by talbuquerque** [jeffijoe/awilix#184]
Hi, thank you in advance for your time. Very good library!

I'm having trouble with loadModules when registering a simple model. 
`module.exports = {
  name: "parameters",
  collectionName: "parameters",
  type: "object",
  properties: {
    gateway: { type: "string", minLength: 4, maxLength: 50 },
  },
  required: ["gateway"],
  additionalProperties: false,
};`

`
  container.loadModules(
    [
      [
        `../parameter/*Model.js`,
        {
          register: asValue,
          lifetime: Lifetime.SINGLETON,
        },
      ],
    ],
    {
      cwd: __dirname,
    }
  );`

If I use listModules, it shows up. If I registry it directly with container.register, it works aswell.

Would you be kind to give me some light? I'm stuck!

**Comment by JamieCorkhill** [comment]
Could you share a picture or some other representation of your file structure so I can check the Glob Pattern?

Are your seeing any errors or is the module simply not being injected/resolved/registered?

Thank you.

**Comment by jeffijoe** [comment]
`loadModules` only loads functions and classes by design.

https://github.com/jeffijoe/awilix/blob/994ed7b270de9d12a7d1513e562d80c0a7475671/src/load-modules.ts#L106-L126

**Comment by talbuquerque** [comment]
May I suggest you to put that in readme? 

There's an example there that has a path to 'models/**/*.js', beign registered asValue

Anyway, is there any reason why wouldn't it be allowed to be loaded automatically?

**Comment by jeffijoe** [comment]
The model in that example is a class which _does_ get registered.

**Comment by talbuquerque** [comment]
Ok... Would you consider an update to support it? I could work on that...

**Comment by jeffijoe** [comment]
This would likely result in a bunch of files being registered that shouldn't (helpers/config). An update to the docs stating this behavior would make sense though. If you really want to register these automatically, you can wrap them in functions quite easily.

**Comment by talbuquerque** [comment]
I did that. But I don't think that it should be a concern to awilix. If it works as glob pattern, that means that I'm able to "src/**/*.js" and load base classes, my container registration and others. I think it should be a concern of the developer. Maybe a warning if the container is bloated with objects... Anyway, I don't think an application would have that much helpers/config. I think it will have much more models that are plain objects than others.

**Comment by jeffijoe** [comment]
I've actually never seen models be plain objects that never need instantiation like you are doing here.
