### ISSUE TITLE
AwilixResolutionError: Could not resolve 'config'. Cyclic dependencies detected.

### ISSUE THREAD

**Issue by moltar** [jeffijoe/awilix#185]
Repro: https://github.com/moltar/awilix-cyclic-dep-repro/blob/master/index.ts

I have a single dependency. So I am not sure how this can be cyclic?

Any ideas?

Thanks.

---

To test:

```sh
git clone git@github.com:moltar/awilix-cyclic-dep-repro.git
cd awilix-cyclic-dep-repro
npm i
npm start
```

**Comment by moltar** [comment]
A workaround via `asFunction` seems to work:

```ts
container.register({
  config: asFunction(() => new Config()).singleton(),
})
```

**Comment by jeffijoe** [comment]
I can't view the link.

**Comment by moltar** [comment]
Oops, sorry, created a private repo by mistake.

Fixed and made it public!

**Comment by jeffijoe** [comment]
I would imagine `BaseConfig` has a constructor that takes a `config` param. Declaring an empty constructor in `Config` will fix it.

**Comment by moltar** [comment]
BaseConfig takes an argument, but not a Config. It’s basically a copy of process.env:


export class BaseConfig {
  public constructor(private readonly environment = environmentDefaults()) {

**Comment by jeffijoe** [comment]
Seems base config does some object mapping on the cradle. Look at the stack trace, its trying to pull every possible value from the cradle, so it makes sense that it throws this error.

**Comment by moltar** [comment]
Ok, thanks, I think I understand now!
