### ISSUE TITLE
How to type a container that has a factory function returning a Promise?

### ISSUE THREAD

**Issue by moltar** [jeffijoe/awilix#186]
It is my understanding that `awilix` will do the right thing and resolve the `Promise` before resolving the dependency.

Am I assumption correct?

In, which case it is not clear how to type this without failing type checks:

```ts
import { asFunction, createContainer } from 'awilix'

interface Container {
  foo: boolean
}

const factory = () =>
  new Promise<boolean>((resolve) => {
    return resolve(true)
  })

const container = createContainer<Container>()

container.register({
  // this fails
  foo: asFunction(factory),
})
```

In this case, `foo` in registration is failing the type check:

```
Type 'BuildResolver<Promise<boolean>> & DisposableResolver<Promise<boolean>>' is not assignable to type 'Resolver<boolean> | undefined'.
  Type 'BuildResolver<Promise<boolean>> & DisposableResolver<Promise<boolean>>' is not assignable to type 'Resolver<boolean>'.
    The types returned by 'resolve(...)' are incompatible between these types.
      Type 'Promise<boolean>' is not assignable to type 'boolean'.
```

**Comment by jeffijoe** [comment]
No, Awilix does not do anything async, what you register is what you get.

**Comment by moltar** [comment]
Yeah, just came here to post this :D Thanks for the quick response!

**Comment by moltar** [comment]
In which case, what is a good pattern for getting the resolved value, rather than the Promise itself?

**Comment by jeffijoe** [comment]
You can await the promise, that will work. I would suggest not having async factories though.

**Comment by moltar** [comment]
How would you handle a database connection? It’s always async.

**Comment by jeffijoe** [comment]
I don't use any DB connections where the factory/constructor is async. `pg`, `knex`, etc. Good libs will manage the connection for you.

Alternatively, I suggest you do something like:

```ts
class MyDb {
  constructor() {
    this.connect = _.once(this.connect.bind(this))
  }

  private async connect(): Promise<DbConnection> {
    //
  }

  async query() {
    const conn = await this.connect()
    // ...
  }
}
```

**Comment by moltar** [comment]
Unfortunately TypeORM has an async connection factory.

Wrapping that into a class would be a bad DX, because everything hangs off of the connection.

**Comment by moltar** [comment]
Maybe a good feature would be a modifier that resolves the dependency?

Example:

```ts
container.register({
  databaseConnection: asFunction(databaseConnection).resolve().singleton(),
})
```

**Comment by moltar** [comment]
In the meantime I have figured out how to trick TypeORM:

```ts
export function databaseConnection({ databaseConnectionOptions }: Container) {
  // this is an async function
  createConnection(databaseConnectionOptions)

  // and "getConnection" is a sync function
  return getConnection(databaseConnectionOptions.name)
}
```

**Comment by jeffijoe** [comment]
You can use a `Proxy` that does the above trick I mentioned on every getter.

**Comment by jeffijoe** [comment]
Alternatively:

```js
async function configureContainer () {
  // returns a promise
  const connection = await connectToDb({
    host: process.env.DB_HOST,
    user: process.env.DB_NAME
  })

  return createContainer()
    .register({ connection: asValue(connection) })
}

// in some main file
configureContainer().then(container => {
  // You're ready!
})
```

**Comment by moltar** [comment]
I'm going to close this as I settled on the async factory function, like you suggested. Thanks.

**Comment by gnimmelf** [comment]
FYI, on Node you can use [DeAsync](https://www.npmjs.com/package/deasync), either plain or a promise wrapper, e.g

```
const { loopWhile } = require('deasync')

exports.deasync = (asyncFn) => {
  let done = false
  let err
  let retVal

  return (...params) => {
    asyncFn(...params)
      .then(res => {
        retVal = res
        done = true
      })
      .catch(e => {
        done = true;
        err = e;
      });

    loopWhile(() => !done)

    if (err) throw err;
    return retVal
  }
}
```

@jeffijoe this was a PIA to discover. I think the reason was that I just expected it to be resolved due to awilix being a superior thing, so for future users, I suggest maybe add a notice about *no async resolving* it in the docs, and list a few workarounds... 

Cheers!

**Comment by jeffijoe** [comment]
I don't think _any_ container supports async dependencies?

**Comment by gnimmelf** [comment]
You're probably right, so then maybe just state that? 

However I do resonate with the rationale for DeAsync as stated in their readme =)

/flemming
