### ISSUE TITLE
loadModules ignore glob

### ISSUE THREAD

**Issue by t3h2mas** [jeffijoe/awilix#188]
Is there a way to pass the ignore property to node-glob?

I would like to autoload modules in a directory, but exclude `thing.spec.js` named tests.

Alternatively, we could use a specific convention to add to the glob, but I would rather blacklist tests instead of whitelisting specific modules

**Comment by jeffijoe** [comment]
I usually solve this with a convention like `*-service.js`. Can you not do `*(!.spec).js` or something?

**Comment by t3h2mas** [comment]
@jeffijoe It does not look like `*(!.spec).js` `*!(.spec).js` etc work as desired

We can work around it using the convention

**Comment by jeffijoe** [comment]
Also if you keep your test files in a `__tests__` dir, the single-level `*` should also work fine.
