### ISSUE TITLE
Using Awilix autoloading together with a bundler like webpack?

### ISSUE THREAD

**Issue by ivarvh** [jeffijoe/awilix#19]
Hey,

This is more of a question than an issue, but when you are using a bundler like webpack, is there still a way to do autoloading? I understand that it's not going to work, because the paths you pass to it are only valid in the source folder. Any idea how this could be resolved?

**Comment by jeffijoe** [comment]
A PR by @ewrogers #10 added webpack compat, but not sure if that includes loadModules. I have never used awilix with webpack so i'm not sure

**Comment by ewrogers** [comment]
It likely would not work from what I can tell. Personally I'd recommend **against** webpacking backend code unless you have a very specific need to do so. At my day job we currently do it but I've started to migrate away from that approach.

It's easier to use babel and have it output your transpiled code to a dist folder and be able to use loadModules.

**Comment by ivarvh** [comment]
Yeah, I was wondering about that. Does bundling backend code give any noteworthy performance improvements? Bundling seems logical in the frontend because you want to reduce file sizes sent to the client, but I'm not sure what the advantages would be in the backend, nonetheless I have seen it recommended a few times and didn't really question it until now.

**Comment by jeffijoe** [comment]
@ivarvh I don't think it does, if anything it'll make it worse by adding the extra Webpack runtime.

**Comment by jeffijoe** [comment]
I don't think we can get webpack autoloading to work within the context of Awilix since it would require (no pun intended) `require.context` which I don't think should be used from within libraries.

What you could do, is something like **(not tested, probably needs work)**:

```js
const isClass = require('is-class')
const ctx = require.context('./services', true)
const { createContainer } = require('awilix')
const path = require('path')

const container = createContainer()

ctx.keys().forEach(k => {
  const v = ctx(k)
  const name = path.basename(k)
  if (isClass(v)) {
    container.registerClass({ [name]: v })
  } else {
    container.registerFunction({ [name]: v })
  }
})
```

**Comment by jeffijoe** [comment]
Closing this for now. 😄
