### ISSUE TITLE
String in inject function causes type error?

### ISSUE THREAD

**Issue by dkpark95** [jeffijoe/awilix#190]
Trying to build a controller that has a router property and getter function but the `inject` class seems to throw an error if you pass a string into it.

```javascript
export default class UsersController {
  get router() {
    const router = Router();

    router.use(inject('createUser'))
  }
}
```
I've seen other examples doing the same thing, but is this a wrong approach? Here's the error: 
```javascript
Argument of type '"createUser"' is not assignable to parameter of type 'FunctionReturning<any> | Constructor<any> | Resolver<any>'.ts(2345)
```

**Comment by jeffijoe** [comment]
I don't know where people are getting this information. That was the old signature from over 2 years ago. `inject` takes a factory function for a middleware. https://github.com/talyssonoc/awilix-express#api

**Comment by dkpark95** [comment]
I see, might've been a dumb question. I was looking at a boilerplate that implements this lib and it might be outdated.

**Comment by dkpark95** [comment]
Appreciate the speedy responses from you, amazing lib!

**Comment by jeffijoe** [comment]
Happy to help 😄
