### ISSUE TITLE
Inheritance classes

### ISSUE THREAD

**Issue by dankkomcg** [jeffijoe/awilix#192]
Hello,

I'm trying to resolve class inheritance reading this issue #107 , but doesn't work.
I have two classes: AnotherClass.js, BaseClass.js. I'm registering the classes on container:

```
// BaseClass.js
class BaseClass {
  constructor() {}
}

// AnotherClass.js
class AnotherClass extends BaseClass {
  constructor() {
    super();
    // do something...
  }
}
```

```
// Container.js
Container
    .register({
        BaseClass: asClass(BaseClass).singleton(),
        AnotherClass: asClass(AnotherClass).singleton(),
    });
```

Only works when i import the class BaseClass on file AnotherClass.js... Inheritance doesn't work when i registered the class vía container? I'm use the default injection. I have done with classic injection but doesn't work too. 
Not typescript but i'm using babel compiler.

Thanks.

**Comment by jeffijoe** [comment]
Why are you expecting to be able to omit the import of your base class?

**Comment by dankkomcg** [comment]
Im triying to implement DDD over the most clean form as possible. I don't wanr any import if is not neccesary.

**Comment by jeffijoe** [comment]
Imports are okay, some things have no place in the container such as utilities. You need to import the class you are extending.

**Comment by dankkomcg** [comment]
Ok, thanks
