### ISSUE TITLE
Applying resolver middleware?

### ISSUE THREAD

**Issue by robodude666** [jeffijoe/awilix#193]
Howdy,

Is it possible to apply a middleware that gets called on the resolved value? For example:

```js
class MailService {}
container.register({
  mailService: asClass(MailService).singleton()
})

function afterResolved(resolved) {
  // resolved contains reference to mailService
}
```

Some way of called `afterResolved(mailService)`.  Use case would be applying Aspects to all resolved classes.

Thanks,
-robodude666

**Comment by jeffijoe** [comment]
You can wrap another resolver, but I would avoid the magic that aspects usually require personally.

**Comment by robodude666** [comment]
@jeffijoe That was my first idea, but was curious if there was a way to hook into the resolution process.

Regarding your comment on aspects, what do you mean by magic? They're basically before/after decorators. How else would I add logging/tracing to an application without adding a bunch code to every class and littering constructors?

**Comment by jeffijoe** [comment]
See [this talk](https://www.infoq.com/presentations/8-lines-code-refactoring/).

Basically, that boilerplate isn't bad, it lets anybody reason about what is going on, there's no hidden magic that only a select few know how strings things together. If all that stuff becomes unwieldy to do manually, it's usually a symptom of the wrong design.
