### ISSUE TITLE
throw new errors_1.AwilixTypeError('asClass', 'Type', 'class', Type);

### ISSUE THREAD

**Issue by AryanChothani** [jeffijoe/awilix#194]
H:\node-api-boilerplate-master\node_modules\awilix\lib\resolvers.js:77
        throw new errors_1.AwilixTypeError('asClass', 'Type', 'class', Type);
        ^

AwilixTypeError: asClass: expected Type to be class, but got undefined.
    at asClass (H:\node-api-boilerplate-master\node_modules\awilix\lib\resolvers.js:77:15)
    at Object.<anonymous> (H:\node-api-boilerplate-master\src\container.js:81:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (H:\node-api-boilerplate-master\index.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

i am adding todo & todoitrems in this boilerplate

index.js
`const container = require('./src/container');

const app = container.resolve('app');

app
  .start()
  .catch((error) => {
    app.logger.error(error.stack);
    process.exit();
  });`

container.js

`const { createContainer, asClass, asFunction, asValue } = require('awilix');
const { scopePerRequest } = require('awilix-express');

const config = require('../config');
const Application = require('./app/Application');
const {
  CreateUser,
  GetAllUsers,
  GetUser,
  UpdateUser,
  DeleteUser,
  CreateTodo,
  DeleteTodo,
  UpdateTodo
} = require('./app/user');

const UserSerializer = require('./interfaces/http/user/UserSerializer');
const TodoSerializer = require('./interfaces/http/todo/TodoSerializer');

const Server = require('./interfaces/http/Server');
const router = require('./interfaces/http/router');
const loggerMiddleware = require('./interfaces/http/logging/loggerMiddleware');
const errorHandler = require('./interfaces/http/errors/errorHandler');
const devErrorHandler = require('./interfaces/http/errors/devErrorHandler');
const swaggerMiddleware = require('./interfaces/http/swagger/swaggerMiddleware');

const logger = require('./infra/logging/logger');
const SequelizeUsersRepository = require('./infra/user/SequelizeUsersRepository');
const SequelizeTodoRepository = require('./infra/todo/SequelizeTodoRepository');
const { database, Todo: TodoModel } = require('./infra/database/models');
const { databasetodo, User: UserModel } = require('./infra/database/models');

const container = createContainer();

// System
container
  .register({
    app: asClass(Application).singleton(),
    server: asClass(Server).singleton()
  })
  .register({
    router: asFunction(router).singleton(),
    logger: asFunction(logger).singleton()
  })
  .register({
    config: asValue(config)
  });

// Middlewares
container
  .register({
    loggerMiddleware: asFunction(loggerMiddleware).singleton()
  })
  .register({
    containerMiddleware: asValue(scopePerRequest(container)),
    errorHandler: asValue(config.production ? errorHandler : devErrorHandler),
    swaggerMiddleware: asValue([swaggerMiddleware])
  });

// Repositories
container.register({
  usersRepository: asClass(SequelizeUsersRepository).singleton(),
  todoRepository: asClass(SequelizeTodoRepository).singleton()
});

// Database
container.register({
  database: asValue(database),
  UserModel: asValue(UserModel),
  databasetodo: asValue(databasetodo),
  TodoModel: asValue(TodoModel)
});

// Operations
container.register({
  createUser: asClass(CreateUser),
  getAllUsers: asClass(GetAllUsers),
  getUser: asClass(GetUser),
  updateUser: asClass(UpdateUser),
  deleteUser: asClass(DeleteUser),
  createTodo: asClass(CreateTodo),
  deletetodos: asClass(DeleteTodo),
  updateTodo: asClass(UpdateTodo)
});

// Serializers
container.register({
  userSerializer: asValue(UserSerializer),
  TodoSerializer: asValue(TodoSerializer)

});

module.exports = container;
`

**Comment by JamieCorkhill** [comment]
Can you double check that everything you're registering `asClass` is indeed a class or constructable function?

From the error, it looks like you're attempting to register something that is `undefined`.

Can you double check your imports into `container.js` and your exports from the relevant files? Make sure there aren't any issues that might cause one of the values you're registering to be `undefined`. It could be something as simple as a spelling error.

**Comment by AryanChothani** [comment]
thanks for suggestion but i have check all the spellings but there is no problem this is the link of boilerplate i am using "https://github.com/talyssonoc/node-api-boilerplate"

**Comment by AryanChothani** [comment]
> Can you double check that everything you're registering `asClass` is indeed a class or constructable function?
> 
> From the error, it looks like you're attempting to register something that is `undefined`.
> 
> Can you double check your imports into `container.js` and your exports from the relevant files? Make sure there aren't any issues that might cause one of the values you're registering to be `undefined`. It could be something as simple as a spelling error or maybe a named vs. default export, etc. Based on the boilerplate you're following, I have an inkling that the issue could lie in one of your CRUD Ops classes or the index file that batch exports them, but I don't know that for sure.

thanks for suggestion but i have check all the spellings but there is no problem this is the link of boilerplate i am using "https://github.com/talyssonoc/node-api-boilerplate"

**Comment by JamieCorkhill** [comment]
Thanks, but I'm familiar with that boilerplate and you've extended it with new features in the issue you describe here. 

Did the error you're experiencing come _after_ you made modifications to the boilerplate or before? 

If after, can I see your local codebase that includes the changes you have made? Thanks.

**Comment by JamieCorkhill** [comment]
For example, all the code you've added to handle todos was not in the original boilerplate. In the code you post here, your classes that handle todos are being imported from `./app/user/index`. Are sure that's correct? Has the exported object from that index file been updated to contain the todo classes too?

**Comment by AryanChothani** [comment]
> For example, all the code you've added to handle todos was not in the original boilerplate. In the code you post here, your classes that handle todos are being imported from `./app/user/index`. Are sure that's correct?
> 
> _(I ask because `app/user` is a peculiar place to put todos-related logic, and in other parts of the registration file, you do have a directory based separation between users and todos, but there, you don't.)_
> 
> Has the exported object from that index file been updated to contain the todo classes too or do you mean to import them from `/app/todos` instead?

thank you for all suggestions problem is solved

**Comment by JamieCorkhill** [comment]
You're welcome. I'm glad it's solved.

**Comment by AryanChothani** [comment]
> You're welcome. I'm glad it's solved.

(node:11708) UnhandledPromiseRejectionWarning: TypeError: Object.defineProperty called on non-object
    at defineProperty (<anonymous>)
    at new decorator (H:\node_boilerplate\node_modules\structure\src\attributes\decorator.js:45:5)
    at CreateTodo.execute (H:\node_boilerplate\src\app\todo\CreateTodo.js:13:18)
    at create (H:\node_boilerplate\src\interfaces\http\todo\TodosController.js:33:16)
    at Layer.handle [as handle_request] (H:\node_boilerplate\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\node_boilerplate\node_modules\express\lib\router\route.js:137:13)
    at injectMiddleware (H:\node_boilerplate\node_modules\awilix-express\lib\inject.js:11:12)
    at Layer.handle [as handle_request] (H:\node_boilerplate\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\node_boilerplate\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\node_boilerplate\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (H:\node_boilerplate\node_modules\express\lib\router\layer.js:95:5)
    at H:\node_boilerplate\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (H:\node_boilerplate\node_modules\express\lib\router\index.js:335:12)
    at next (H:\node_boilerplate\node_modules\express\lib\router\index.js:275:10)
    at injectMiddleware (H:\node_boilerplate\node_modules\awilix-express\lib\inject.js:11:12)
    at Layer.handle [as handle_request] (H:\node_boilerplate\node_modules\express\lib\router\layer.js:95:5)
(node:11708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`TodosController.js


const { Router } = require('express');
const { inject } = require('awilix-express');
const Status = require('http-status');

const TodosController = {
  get router() {
    const router = Router();

    router.use(inject('todoSerializer'));

    router.post('/', inject('createTodo'), this.create);
    return router;
  },

  create(req, res, next) {
    const { createTodo, todoSerializer } = req;
    const { SUCCESS, ERROR, VALIDATION_ERROR } = createTodo.outputs;

    createTodo
      .on(SUCCESS, (todo) => {
        res
          .status(Status.CREATED)
          .json(todoSerializer.serialize(todo));
      })
      .on(VALIDATION_ERROR, (error) => {
        res.status(Status.BAD_REQUEST).json({
          type: 'ValidationError',
          details: error.details
        });
      })
      .on(ERROR, next);

    createTodo.execute(req.body);
  },
};

module.exports = TodosController;
`

CreateTodo.js

`const Operation = require('src/app/Operation');
const Todo = require('src/domain/todo/Todo');

class CreateTodo extends Operation {
  constructor({ todosRepository }) {
    super();
    this.todosRepository = todosRepository;
  }

  async execute(todoData) {
    const { SUCCESS, ERROR, VALIDATION_ERROR } = this.outputs;

    const todo = new Todo(todoData);

    try {
      const newTodo = await this.todosRepository.add(todo);

      this.emit(SUCCESS, newTodo);
    } catch(error) {
      if(error.message === 'ValidationError') {
        return this.emit(VALIDATION_ERROR, error);
      }

      this.emit(ERROR, error);
    }
  }
}

CreateTodo.setOutputs(['SUCCESS', 'ERROR', 'VALIDATION_ERROR']);

module.exports = CreateTodo;`

**Comment by jeffijoe** [comment]
That does not look related to Awilix. Also, please refrain from posting (unformatted) code and errors with no explanation.
