### ISSUE TITLE
Integration with Flow

### ISSUE THREAD

**Issue by gadld** [jeffijoe/awilix#196]
Is there a way to integrate Awilix with https://flow.org/
I mean a way in which flow can detect which function is being injected and detect the correct types?

**Comment by jeffijoe** [comment]
Flow inference only works within a module as far as I know

**Comment by gadld** [comment]
Thank you, do you have any advice on type checking?

BTW
I love Awilix!!

**Comment by jeffijoe** [comment]
Just declare the depencies and try to register the right things lol

There’s not much Awilix can do in terms of type checking since its runtime only.
