### ISSUE TITLE
Unable to resolve parameterless subclass

### ISSUE THREAD

**Issue by harindaka** [jeffijoe/awilix#198]
Let's say I have a base class and a subclass as follows

```
class MyBaseClass {
    #collectionName;

    constructor(collectionName) {
        this.#collectionName = collectionName;
    }

    getCollection() {
        return this.#collection;
    }
}

class MySubClass extends MyBaseClass {
    constructor() {
        super("users");
    }
}
```

I use `awilix.InjectionMode.CLASSIC`. When I try to resolve and instance of `MySubClass`, I get a resolution error which basically says `Could not resolve 'collectionName'`. `MySubClass` does not need constructor parameters to be passed in order to be instantiated. What gives?

**Comment by jeffijoe** [comment]
That’s probably a bug. I think empty ctor is treated like no ctor which is not the same.

**Comment by harindaka** [comment]
I'll try to whip up a code snippet to reproduce this today. Could it possibly be related to https://github.com/jeffijoe/awilix/issues/107? I'll also try an older version.

**Comment by jeffijoe** [comment]
Yes that was the change that introduced the behavior.

**Comment by harindaka** [comment]
Does this mean that this bug would not be fixed in the long run since it would break features introduced in https://github.com/jeffijoe/awilix/issues/107 ?

**Comment by jeffijoe** [comment]
I don’t know which behavior would be preferred by the majority. In your case you can make it work by adding `= undefined` in the base ctor. Params with default initializers won’t throw resolution errors.

**Comment by harindaka** [comment]
I wouldn't change the behavior before the next major version. But i'd say go with the most intuitive way for anyone adopting this library anew. Do what majority of the DI frameworks out there in the typesafe world are doing unless its not possible due to the dynamic nature of js. I'd argue in that sense the most intuitive way would be to support the scenario above. Would love to hear opposing views. I wonder if its technically possible to support both ways and let consuming developers specify which method to use explicitly when setting up the composition root.

**Comment by jeffijoe** [comment]
I’m not a fan of adding more config bloat.

Hoping others will chime in here to get an idea. I personally don’t use base classes so I don’t have this problem.

**Comment by linusnorton** [comment]
I hit this issue today. I would prefer have it work out of the box as I don't use `super(...arguments)`. Is there a work around other than having a default value of undefined in the parent class?

**Comment by jeffijoe** [comment]
Yes you can register the params too, that will work

**Comment by bosconian-dynamics** [comment]
I'll add my voice to the proponents for supporting truncated sub-class args out-of-the-box. I think the ability to more definitively and intuitively map ctor args from child to a parent-class is more valuable than the convenience of passing them all up positionally with a spread... In my work, I feel the situation which the former arrangement solves occurs far, far more frequently than those which the latter addresses - but I don't claim to have any measurable experience with DI.

**Comment by jeffijoe** [comment]
Yeah, I think it makes sense.
