### ISSUE TITLE
loadModules typescript cradle support

### ISSUE THREAD

**Issue by pragmaticivan** [jeffijoe/awilix#199]
Howdy! 

Is there a way to auto-populate a Cradle interface from container `loadModules` somehow?

That way I could auto-complete some stuff with Typescript.

**Comment by jeffijoe** [comment]
No since there is no type info at runtime.

**Comment by gustawdaniel** [comment]
![Zrzut ekranu z 2023-09-01 22-16-27](https://github.com/jeffijoe/awilix/assets/16663028/24ad034a-30ce-4a3a-8afc-55e1467a70c9)

is there any option to remove these `any` and make it work with typescript?

**Comment by jeffijoe** [comment]
@gustawdaniel you can use a typed container, but you need to specify the types yourself. Additionally, I wouldn't recommend working with the cradle directly, rather use `.resolve`.

See [this comment](https://github.com/jeffijoe/awilix/issues/334#issuecomment-1654596206) for an example on how to add types.
