### ISSUE TITLE
Support for multiple dependency implementations

### ISSUE THREAD

**Issue by kibertoad** [jeffijoe/awilix#200]
Currently it doesn't seem to be possible to register multiple resolvers for the same dependency. Possible use-cases for this are:

* Priority-based injection, so that you could introduce an alternative dependency with a higher priority to override one module in tests, for an example;
* Metadata-based injection, so that you could tag alternative dependencies with additional fields, which can be specified during resolution in order to pick one out of multiple. Example usage: different Strategy entities being injected based on request country, or process.env-based dependency selection.

Obviously both cases can be handled by wrapping resolvers with a higher level resolvers, but it might be convenient to have this functionality out-of-the-box.

If you think that it makes sense, I can work on a PR.

**Comment by jeffijoe** [comment]
I think those are application-level concerns and should be treated as such rather than an infrastructure concern.

We recently had a case where we wanted to pick a storage backend based on the calling user's tenant. A Factory was the right answer (`await storageFactory.getStorageForTenant(tenantId)`).

**Comment by kibertoad** [comment]
@jeffijoe Fair enough. I've checked what happens if you register dependency twice - the one that was registered last is the one that wins. I think that addresses the use case of mocking dependencies in testing well enough.

**Comment by kibertoad** [comment]
@jeffijoe I'm curious, though, in your scenario, how did you handle the async nature of the factory? Doesn't that result in promise being passed to constructor, where you can't really await?

**Comment by jeffijoe** [comment]
You resolve as needed, not in the constructor, because the call (`upload(tenant, filename, stream): Promise<void>`) has the context needed.

**Comment by kibertoad** [comment]
Gotcha. So you bypassed the DI for this use-case altogether?

**Comment by jeffijoe** [comment]
I inject the factory, the factory can accept instances of the possible storage targets.

```js
function StorageFactory(tenantLookup, gcsStorage, s3Storage) {
  return {
    async getStorageForTenant(tenantId) {
      const tenant = await tenantLookup.get(tenantId)
      switch (tenant.config.storage) {
        case 'GCS': return gcsStorage
        case 'S3': return s3Storage
      }
    }
  }
}
```

**Comment by kibertoad** [comment]
Thanks for the tip!
