### ISSUE TITLE
non-DI'd fields in class config?

### ISSUE THREAD

**Issue by JeffSpies** [jeffijoe/awilix#202]
Hi, really digging what you've put together here. Excited to play with it more here.

I have two classes registered with my container and one that I'd like to be passed in manually (i.e., without DI).

````ts
class C {}
class B {}
class A {
  b: B
  c: C
  constructor(config) {
    this.b = config.b
    this.c = config.c
  }
}

container.register({
 a: asClass(A).scoped(),
 b: asClass(B).scoped()
})
`````

Is there a way to combine DI'd fields and non-DI'd fields in A's config and then create an instance of A? Thanks in advance!

EDIT: While I may be off on this, I'm assuming I could use a factory function that would have the DI'd elements proxied into it and then create the non registered A with that, but I'm not sure if this is the most direct option to achieve what I'm looking for.

**Comment by jeffijoe** [comment]
You can use .inject
