### ISSUE TITLE
How to add sequelize-typescript models which corresponding interface.

### ISSUE THREAD

**Issue by zebkailash** [jeffijoe/awilix#204]
I have an interface that represents a record in the table. I am using sequelize-typescript with decorators. eg

As a workaround, I have to add the models import and assign variable to that type which doesn't look decent.

**user.model.ts**
```js
@Table({
  tableName: 'user',
  timestamps: true,
})

export default class User extends Model<User> implements IUser {
}

```

```js
interface IUser { 
   id: number; 
   name: string; 
}
```
``` js
//modelFactory.ts
 export default (container, sequelize) => {
      for (const model in sequelize.models) {
          container.register({
                [model]: asValue(sequelize.models(model))
           })
      }
  }
```
In my service.js

```js
  const someFunc = () {
       const userModel = container.resolve<IUser>('modelName');
       // error no findOne does not exist on IUser
  }
```

**Comment by jeffijoe** [comment]
I don't understand your question.

**Comment by zebkailash** [comment]
I want to access sequelize models added to the container using asValue API. eg

``` js
   container.register('user', sequelize.models['user']);
```

Now when I try to access the models it is not type inferred correctly.

```middleware.ts
   const userModel = req.container.resolve<User>('user');
   userModel.findOne() // Error no findOne exist on userModel
```

Hope that makes my point.

**Comment by jeffijoe** [comment]
Your snippets from your original post and your comment are different.

**Comment by zebkailash** [comment]
@JamieCorkhill That's helpful. Much Appreciated. Just a thought if we can add an example related to it.

**Comment by JamieCorkhill** [comment]
I'm glad it's helpful. 

Do you mean adding an example pertaining to Sequelize in the Awilix docs? Awilix is an Inversion of Control Container - it doesn't assume any data access method (it doesn't even assume you have a data store). I'm not sure a Sequelize-specific section of the docs would be particularly relevant, especially since only a limited number of Awilix users will gain any value out of it.

**Comment by zebkailash** [comment]
Sounds cool. Thank you.
