### ISSUE TITLE
Can not stub awilix since version 4.2.7

### ISSUE THREAD

**Issue by ET-CS** [jeffijoe/awilix#207]
Hey!

Thank you for awilix. it's amazing DI and I use it a lot.

Since version 4.2.7, my unit tests are breaking so I can't upgrade awilix to latest.

I have simple mocha/sinon test to test that I create the container.

```
import * as awilix from "awilix";
import sinon, {fake} from "sinon";
import chai, {expect} from "chai";
import sinonChai from "sinon-chai";
import createContainer from "../../src/create_container";

chai.use(sinonChai);

const sandbox = sinon.createSandbox();

describe("container", function () {
  let mockContainer;

  beforeEach(function () {
    mockContainer = {register: fake()};
    sandbox.stub(awilix, "createContainer").returns(mockContainer);
  });

  afterEach(function () {
    mockContainer = null;
    sandbox.restore();
  });

  it("should create container and register dependencies", function () {
    const serviceName = "favorites-service";
    const container = createContainer(serviceName);
    expect(awilix.createContainer).to.be.calledOnceWith({
      injectionMode: awilix.InjectionMode.PROXY
    });
    expect(container.register).to.be.calledOnce;
  });
});

```

Now, in 4.2.7 it's breaking with:
```
TypeError: [Function: createContainer] is not a spy or a call to a spy!
    at assertCanWorkWith (node_modules\sinon-chai\lib\sinon-chai.js:53:19)
    at Proxy.<anonymous> (node_modules\sinon-chai\lib\sinon-chai.js:98:13)
    at Proxy.calledOnceWith (node_modules\chai\lib\chai\utils\addMethod.js:57:25)
    at Context.<anonymous> (test\unit\/container_test.js:32:42)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
```

as if sinon is stubing the incorrect `createContainer` function,
but looking at the changes in this version, Ican't see anything that can result in this change, but yet, when I downgrade to 4.2.6 my test work again.

any idea maybe why it's happening in 4.2.7? and how to workaround it?

**Comment by jeffijoe** [comment]
See the changelog, basically just updated packages and fixed a bug around resolution errors.

You shouldn't be stubbing the container anyway, I don't think tests like that provide any value.

**Comment by ET-CS** [comment]
Yeah, was looking on that and not sure what was changed to affected this. It still blocks me from upgrade.
I do think that this test provides value in that I test my app that it's calling awilix and creating the container, and registering what it should.

**Comment by jeffijoe** [comment]
I still wouldn’t recommend module stubbing for this very reason; it’s fragile. If you insist on testing this, pass in the container to the module.

**Comment by ET-CS** [comment]
Thank you very much. I will look if and how I can fix this issue at my side, but since I can't see any change in recent version that affect this I will close this issue.

Thanks a lot for amazing product!
