### ISSUE TITLE
How to change dependency implementation at runtime?

### ISSUE THREAD

**Issue by piavgh** [jeffijoe/awilix#212]
Hi @jeffijoe ,

I'm using Typescript with your library.

Let's say I have a `CompanyService` that has dependency on a `CompanyRepositoryInterface`

```ts
export default class CompanyService {
  companyRepository: CompanyRepositoryInterface;

  constructor(companyRepository: CompanyRepositoryInterface) {
    this.companyRepository = companyRepository;
  }

  ...
}
```

I have 2 concrete implementations of this `CompanyRepositoryInterface`:
1. `MongoCompanyRepository` implements `CompanyRepositoryInterface`
2. `PostgreCompanyRepository`  implements `CompanyRepositoryInterface`

Is there a way that I can bind the implementation at runtime with Awilix?

At the moment, I did this:

```ts
  container.register({
    companyController: asClass(CompanyController),
    companyService: asClass(CompanyService),
    companyRepository: asClass(MongoCompanyRepository),
  });
```

This registration happens when the server starts only, and if I wish to switch to PostgreSQL, I need to change it to 

```ts
  container.register({
    companyController: asClass(CompanyController),
    companyService: asClass(CompanyService),
    companyRepository: asClass(PostgreCompanyRepository),
  });
```

and restart the server.

With IoC in other languages, such as PHP: https://laravel.com/docs/8.x/container#contextual-binding, I can bind the implementation to the interface at runtime

I also saw this issue https://github.com/jeffijoe/awilix/issues/135, but I just want to be sure if it's unable to do that with Awilix/Javascript, or is there any workaround.

Thanks.

**Comment by jeffijoe** [comment]
You can if you use a scope. It’s how we inject the user context.

**Comment by piavgh** [comment]
Thank you. I will close this issue
