### ISSUE TITLE
Support for JSON registrations via loadModules

### ISSUE THREAD

**Issue by overflowz** [jeffijoe/awilix#213]
Hi, I have modules and each module contains a JSON file (exported by default), but digging into the source, it seems that I cannot register via the `loadModules` API.

i.e., assuming we have folders like this:
```
foo/
bar/
baz/
```

and each folder contains *.actions.(ts/js/json) file with the following content:
```ts
export default {
  foo: 'bar',
};
```

**Expectations**: when I call the `loadModules` API with the `asValue` registration, it should be registered.
**Actual**: They're being ignored.

I'm not sure if it's overcomplication or not, but can Awilix support it (at least for the `asValue` registrations)?
Thank you.

**Comment by jeffijoe** [comment]
The reason it doesn't work is because `loadModules` only looks at functions and constructors. The easiest thing to do is to export a function that returns your object.

To be honest though, I don't think you should be injecting these const-type objects, there's no real benefit here.

**Comment by overflowz** [comment]
understood, thanks a lot!
