### ISSUE TITLE
Injector option is not available for loadModules

### ISSUE THREAD

**Issue by overflowz** [jeffijoe/awilix#214]
When using the `loadModules` API, by trying to provide the `injector` property, typescript fails with the following:
```Object literal may only specify known properties, and 'injector' does not exist in type 'ResolverOptions<any>'```

only `lifetime`, `name` and `register` props are available.

```ts
container.loadModules([
  ['', { injector: () => ({}) }], // fails
]);
```

using typescript 4.0.3
awilix: 4.3.0

**Comment by jeffijoe** [comment]
That’s because not all resolvers support inject. Why do you need to do this? Why not just register whatever you were trying to inject in the container?

**Comment by overflowz** [comment]
The documentation says that the injector is available for `loadModules` too (https://github.com/jeffijoe/awilix#per-module-local-injections) that's why I'm asking.

**Comment by overflowz** [comment]
also, if I run that without typescript, the injection works, which is kinda odd to me.

**Comment by jeffijoe** [comment]
Yeah my bad, its supported at runtime because it passes the options straight to whatever resolver is used but TypeScript can’t figure it out using just the base resolver options. Will have to update the typings then.

**Comment by jeffijoe** [comment]
@overflowz try v4.3.1, I changed the typing to use `BuildResolverOptions`.
