### ISSUE TITLE
Injecting dependencies in functions

### ISSUE THREAD

**Issue by disapointmntPanda** [jeffijoe/awilix#218]
https://user-images.githubusercontent.com/63898013/104413806-03f7ed80-5595-11eb-8e20-e36c035d104f.mp4

I have been following component based strucutre for my projects and I have clone the repo for this purpose listed [here][1]

Everything is fine and testable except services.

So I decided to use [awilix][2] to inject dependencies in services.

This is what I tried.

I created a `container.js` file in the `loaders`.
```
const awilix = require('awilix');

const db = require('../db');
const AuthService = require('../components/auth/auth.service');

const container = awilix.createContainer({
  injectionMode: awilix.InjectionMode.PROXY,
});

function setup() {
  container.register({
    db: awilix.asValue(db),
    doGetAllService: awilix.asValue(AuthService.doRegister),
  });
}

module.exports = {
  container,
  setup,
};
```

I invoked this container in `app.js` as below.

```
const express = require('express');

const app = express();

const cors = require('cors');

// load environment config variables
require('dotenv').config();
require('./loaders/container').setup();
...
```
In the doc it says, the first argument will be injected dependencies. But when I do `console.log` I still get undefined.

```
const doRegister = async (opts, { username, password }) => {
  console.log(opts);
  const user = await User.create({
    username,
    password,
    role_id: 1, // assign role id here
  });
   return user;
};
```

For entire folder structure and source conde please go through the repo.

  [1]: https://github.com/sujeet-agrahari/node-express-clean-architecture
  [2]: https://www.npmjs.com/package/awilix

**Comment by jeffijoe** [comment]
Please check the docs for the resolver types. You are using asValue, you probably want asFunction

**Comment by disapointmntPanda** [comment]
@jeffijoe  I tried using `asFunction` as well, but still get undefined.

**Comment by jeffijoe** [comment]
You haven't provided enough info to debug this, and the repo you linked does not even have awilix installed.

My guess is you are also missing the Express middleware and wrapping your handlers in `inject` or using the controller feature. See the docs for the [Express middleware](https://github.com/talyssonoc/awilix-express).

**Comment by disapointmntPanda** [comment]
@jeffijoe Thanks, but what's wrong with this one, I still get undefined.
```
const awilix = require('awilix')

const container = awilix.createContainer({
  injectionMode: awilix.InjectionMode.PROXY
})

const db = {
  User: 'User',
  Post: 'Post',
};

function getUser({ db }) {
  console.log(db.User);
}

container.register({
  db: awilix.asValue(db),
  getUser: awilix.asValue(getUser),
})


getUser(opts);
```

**Comment by jeffijoe** [comment]
`getUser` should return a function, you are using it wrong.

```js
const awilix = require("awilix");

const container = awilix.createContainer({
  injectionMode: awilix.InjectionMode.PROXY
});

const db = {
  User: "User",
  Post: "Post"
};

function createGetUser({ db }) {
  return (id) => {
    console.log("Get", id, "from", db.User);
    return { id };
  };
}

container.register({
  db: awilix.asValue(db),
  getUser: awilix.asFunction(createGetUser)
});

const getUser = container.resolve("getUser");

console.log("Got", getUser("jeffijoe"));
```
