### ISSUE TITLE
multi-injector

### ISSUE THREAD

**Issue by SrHuevo** [jeffijoe/awilix#219]
I need to use a multi-injector, but I can't find anything in the documentation. Is it possible?

**Comment by jeffijoe** [comment]
I dont know what that means.

**Comment by SrHuevo** [comment]
something like this: https://github.com/inversify/InversifyJS/blob/master/wiki/multi_injection.md

**Comment by jeffijoe** [comment]
You can [create a resolver](https://github.com/jeffijoe/awilix/issues/80#issuecomment-365033070) that does this.
