### ISSUE TITLE
Performance implications for Request Scoped Injections

### ISSUE THREAD

**Issue by klausXR** [jeffijoe/awilix#220]
Are there any performance implications when using the Request Scope lifetime option as opposed to singletons? I was going over the docs for `nestjs`, and they mentioned that DI with request scope can reduce the overall throughput of the server.

Is this also an issue with `awilix`, and if so, what is it based on? The amount of registered dependencies in the container, or the amount consumed during the lifecycle of a request? 

If I have registered, lets say, a 100 services within the container, but a single request is unlikely to use more than 3-5, does that matter for performance? Is there a way to not initialize all of them eagerly, or is it done like  that automatically?

**Comment by jeffijoe** [comment]
Singleton will always be faster, but the overhead of request scope is negligible unless your business model is serving Hello World HTTP requests as fast as possible.

When a scope is created, it rolls up the registrations into a map, so it would be based on the amount of registrations. I haven’t benchmarked it myself, but its fast enough, I don’t think this will be the bottleneck of your application. With that said, I would be interested in seeing a benchmark.

The most important thing for performance with Awilix is ensuring you don’t parse classes/functions more often than necessary. Any asClass or asFunction should preferably be done only once. Singleton what you can, though.

**Comment by klausXR** [comment]
I will try to do that, unfortunately, very few of the injections seem to be fit for singletons. I need to inject the user from the request into each service, as it is very important to have access to it for my domain. So, the choice is to either pass it to each method, which really clutters the code, or to inject it in the constructor, which is cleaner, but also makes the services not fit for singletons. 

If the overhead is little, I would prefer to have a cleaner API to work with and try to optimize something else that does not sacrifice DX instead, to make up the difference, I just didn't have an idea exactly how much that overhead is.

I thought that the cradle might have getters defined for each service, that returns a new or a cached instance, only when the property is accessed.

Thank you for work and the informative and quick answer during the weekend.

**Comment by jeffijoe** [comment]
The cradle is just a proxy that does `resolve('key')` under the hood.

You will get the best performance with `CLASSIC` mode since there is no overhead from the proxy.
