### ISSUE TITLE
Found possible vulnerability through rollup-plugin-copy dependency

### ISSUE THREAD

**Issue by gonzaloplaza** [jeffijoe/awilix#223]
Snyk is notifying a possible vulnerability introduced through **rollup-plugin-copy** dependency. 

Link: https://snyk.io/test/github/jeffijoe/awilix

And here details about this issue:

```
Vulnerable module: glob-parent

Introduced through: rollup-plugin-copy@3.3.0

Detailed paths:

Introduced through: awilix@jeffijoe/awilix#7489ef56ff2bd832ee8c62975c87fd819e42bbaf › rollup-plugin-copy@3.3.0 › globby@10.0.1 › fast-glob@3.2.5 › glob-parent@5.1.1
```

Could you check it updating npm dependencies?

**Comment by jeffijoe** [comment]
Rollup is a dev dependency so it doesn’t affect consumers. With that said I’ll update when I can
