### ISSUE TITLE
Got undefined _this_ when invoking class method.

### ISSUE THREAD

**Issue by hd-diegocortez** [jeffijoe/awilix#224]
Hi, I'm using v4.3.1
Here is my code set up:
_conatiner.js_
```
exports.createDependenciesContainer = () => {
  const container = createContainer({
    injectionMode: InjectionMode.PROXY,
  });
  container.register({
    myController: asClass(MyController).inject(() => {
      return { myModel: Model };
    }),
    myService: asClass(MyService).inject(() => {
      return { otherModel: OtherModel };
    }),
  });

  return container;
};

```
When I try to:
_router.js_

```
const container = createDependenciesContainer();
router.get(`/myroute`, container.resolve(`myController`).getAllData);
```
Inside my `getAllData` class method I got that _this_ is undefined so I can't use actually the dependencies. Not sure what is wrong, seems that the class constructor is called and I received `myService` dependency with no problem but when `getAllData` is invoked is like there is no instance at all.

**Comment by jeffijoe** [comment]
Because you are passing just the method without binding it. Wrap it in a closure or make your controller not depend on context. This is not Awilix-specific.

**Comment by hd-diegocortez** [comment]
I see that, is there a cleaner way to bind my context without ` const controller = container.resolve(`myController`); controller. getAllData.bind(controller)` ?

**Comment by jeffijoe** [comment]
I suggest using awilix-koa or awilix-express depending on what lib you use
