### ISSUE TITLE
loadModules error when using sequelize-cli

### ISSUE THREAD

**Issue by fajardm** [jeffijoe/awilix#23]
i have structure like this
-apps
---user
-----model.js
---container.js

code at container.js
`container.loadModules([
  './**/controller.js',
  './**/service.js',
  './**/model.js',
], {
  formatName: (name, descriptor) => {
    const splat = descriptor.path.split('/');
    const namespace = splat[splat.length - 2];
    const fileName = _.upperFirst(name);
    return namespace + fileName;
  },
  registrationOptions: {
    lifetime: awilix.Lifetime.SINGLETON,
  },
});`
 
error like this
`node_modules/sequelize-cli/lib/assets/models/model.js:4
  var <%= names %> = sequelize.define('<%= names %>', {
      ^
SyntaxError: Unexpected token <`

When I rename the model name to another name it's not error.
How to solve this issue?

**Comment by fajardm** [comment]
solved, just add arg cwd

**Comment by jeffijoe** [comment]
Yeah it must have tried to scan your node modules as well. Glad you figured it out 😀
