### ISSUE TITLE
When should I not do container.resolve()?

### ISSUE THREAD

**Issue by disapointmntPanda** [jeffijoe/awilix#230]
In the blow example some dependency being register in the container and it is being resolved explicitely.
```
const awilix = require('awilix')

const container = awilix.createContainer({
  injectionMode: awilix.InjectionMode.PROXY
})

class UserController {
  constructor(opts) {
    this.userService = opts.userService
  }
  getUser(ctx) {
    return this.userService.getUser(ctx.params.id)
  }
}

container.register({
  userController: awilix.asClass(UserController)
})

const makeUserService = ({ db }) => {
  return {
    getUser: id => {
      return db.query(`select * from users where id=${id}`)
    }
  }
}

router.get('/api/users/:id', container.resolve('userController').getUser)
router.get('/api/users/:id', container.cradle.userController.getUser)
```
But this [repo ](https://github.com/talyssonoc/node-api-boilerplate)uses awilix heavily, and I found that it is not using `contianer.resolve()` that often.

```
class Application {
  constructor({ server, database, logger }) {
    this.server = server;
    this.database = database;
    this.logger = logger;

    if(database && database.options.logging) {
      database.options.logging = logger.info.bind(logger);
    }
  }

  async start() {
    if(this.database) {
      await this.database.authenticate();
    }

    await this.server.start();
  }
}

module.exports = Application;

```
So if two things are registered with the container and they depend mutually; I don't need to do `container.resolve()` and it will be injected auto?

Because there is no `container.resolve` for database and other injected dependencies, then how they are being injected?

**Comment by jeffijoe** [comment]
You only need to `resolve` the root module. The `awilix-koa`, `awilix-express`, etc, packages do this for you.

**Comment by disapointmntPanda** [comment]
@jeffijoe Thanks for the response. Can you please show me an example? Or poin me to some page where it have been mentioned?

**Comment by jeffijoe** [comment]
The docs and the Medium articles (part 3) explains how to use the library so I am not sure what else you might be looking for?

You want to know how the library works internally?

**Comment by disapointmntPanda** [comment]
Not at all @jeffijoe , look at this code.
```
const awilix = require('awilix')

const container = awilix.createContainer({
  injectionMode: awilix.InjectionMode.PROXY
})

const db = {
  User: 'User',
  Post: 'Post',
};

function userService({ db }) {
  return {
    get: () => {
      console.log(db.User);
    }
  }
}

container.register({
  db: awilix.asValue(db),
  userService: awilix.asValue(userService),
})


userService({ db: container.resolve('db') }).get();
```
It works. But what if I don't want to do `container.resolve('db')` instead `userService({ opts ])`.
Why it doesn't inject dependencies auto as opts?

**Comment by jeffijoe** [comment]
If you do `userService({ ops })` then Awilix does absolutely nothing.

If you want to construct it yourself but still supply dependencies from the container, you can do `userService(container.cradle)` but that only works in Proxy mode, which is described in details in the docs.

At some point you have to resolve the top level object, it has to start somewhere.

**Comment by disapointmntPanda** [comment]
This made me believe so,
```
class Application {
  constructor({ server, database, logger }) {
    this.server = server;
    this.database = database;
    this.logger = logger;

    if(database && database.options.logging) {
      database.options.logging = logger.info.bind(logger);
    }
  }

  async start() {
    if(this.database) {
      await this.database.authenticate();
    }

    await this.server.start();
  }
}

module.exports = Application
```
How awilix figure it out what to inject here? There is no `container.resolve()` for databaes and others.

**Comment by jeffijoe** [comment]
Because somewhere else that application class is being built by Awilix. I didn’t write that boilerplate but why don’t you search for where that class is being referenced and find out?

**Comment by disapointmntPanda** [comment]
Sure, thanks @jeffijoe

**Comment by jeffijoe** [comment]
Here it is https://github.com/talyssonoc/node-api-boilerplate/blob/master/index.js
