### ISSUE TITLE
Vulnerability in packages dependencies

### ISSUE THREAD

**Issue by konfer-be** [jeffijoe/awilix#231]
awilix@4.3.3 › rollup-plugin-copy@3.4.0 › globby@10.0.1 › fast-glob@3.2.5 › glob-parent@5.1.1

Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS). The enclosure regex used to check for strings ending in enclosure containing path separator.

**Comment by jeffijoe** [comment]
Rollup was wrongfully placed in dependencies which has been fixed.
