### ISSUE TITLE
Inheriting Mongoose Discriminators

### ISSUE THREAD

**Issue by cantoramann** [jeffijoe/awilix#234]
When I load Mongoose models using `() => `, then for inherited models they look like the following:

`module.exports = () => Parent().discriminator('ChildA', childASchema);
`
`module.exports = () => Parent().discriminator('ChildB', childBSchema);
`
...

But I get `Discriminator with name "Child" already exists` error.

My understanding of the problem is that:
When I want to call these models in multiple places, the child model gets loaded again from a 'new' parent, triggering the error.

What kind of a methodology should I follow to fix this issue?

**Comment by jeffijoe** [comment]
Why are you injecting your models? I see a lot of people trying to do this and I just don't understand why.

**Comment by cantoramann** [comment]
Actually, I see no crucial need for injecting models. I just required them and now all are fine. Thank you.
