### ISSUE TITLE
Jest - awilix - node.js memory leak

### ISSUE THREAD

**Issue by hamidhmz** [jeffijoe/awilix#235]
I am writing a big server application in Node.js, and using awilix, Jest, typescript and supertest.

I faced a memory leak issue, which I believe is caused by Awilix, and then my tests will stop. Furthermore, I tried to increase Node.js heap size which can handle it, but it is not permanent solution I search a lot and couldn't find anything useful. I dispose everything after all, but I believe the awilix itself is the memory leak cause, because when I run empty node project with awilix and simple API and turn on Jest --detectleaks it returns memory leak Error. Any ideas?

**Comment by jeffijoe** [comment]
Can you describe how you arrived at this conclusion? What is leaking?

**Comment by hamidhmz** [comment]
I don't know
but when i work with jest and awilix even in empty container Jest --detectleaks  will detect it as a memory leak,
and after each test, the heap size becomes bigger and bigger.
i face this issue after writing the 400 integration test.
jest cannot run all of 400 tests because apparently awilix is leaking and jest cannot handle it.
i don't know what jest is doing behind the scene, and why this thing happened just with awilix.
but I switch to mocha.
i saw that, node.js developers who use awilix. they use mocha except for jest.
i actually didn't solve problem, I just try to hide problem in my application.
I don't know maybe mocha will face this issue too after my application become bigger and having more tests.

**Comment by jeffijoe** [comment]
We are using Jest and Awilix and have been for years without issues, however Jest’ leak and open handle detection usually don’t work.
