### ISSUE TITLE
Dynamically update asValue property in container

### ISSUE THREAD

**Issue by sujai1009** [jeffijoe/awilix#237]
Hi Team, 

i have a scope of setting/updating some value in the container.
ex: to define the host name url https:<SOME_HOST_NAME>:<SOME_PORT>

i have container registered as 

container.register({
	HOST_ENV_URL : awilix.asValue("<>SOME_DUMMY_VALUE"),
});

when i call the first request to server.

router.login(req, res) => {
    var hostNameURL = req.protocol + rep.hostname + req.port
    // update this value into container.
}

how to dynamically do this?

**Comment by jeffijoe** [comment]
Do you want to register it in the global container? Just do the same, `container.register` again.

**Comment by sujai1009** [comment]
But i am in different file.
Containfer defined in ==> global-ioc-containers.js
Now update will happen in user-controller.js

how will i access the container object from gic.js in controller.js
```
constructor({ cradle }) {
		this.cradle = cradle;
	}

getUsers(req, res) {
	container.register({
	  HOST_ENV_URL: asValue(<NEW_VALUE>),
	})
}
```

**Comment by jeffijoe** [comment]
Use a middleware to attach the container? You should probably be using a scope, too.

**Comment by sujai1009** [comment]
Hi Jeff can you provide some sample code links im new to this.

**Comment by jeffijoe** [comment]
Have you checked the documentation and the [examples](https://github.com/jeffijoe/awilix/tree/master/examples) folder?

**Comment by sujai1009** [comment]
Hi jeff, i looked in the koa sample(i guess you refered that as middleware). il update once my testing is completed.
