### ISSUE TITLE
resolve inner object inside container

### ISSUE THREAD

**Issue by sujai1009** [jeffijoe/awilix#238]
Hi Jeff,

1. Is it possible to regisger value like "logLevel" from loggerConfig class
2. Is it possible to es6 class method asFunction like "logMethod"  from loggerConfig class

container.register({
	loggerConfig: awilix.asClass(LoggerConfig),
	logLevel: awilix.asValue(loggerConfig.LEVEL),
	logMethod: awilix.asFunction(loggerConfig.logMessage),
});

**Comment by jeffijoe** [comment]
1. `logLevel: awilix.asFunction((loggerConfig) => loggerConfig.LEVEL`
2. `logMethod: awilix.asFunction((loggerConfig) => loggerConfig.logMessage)` (don't forget to bind the function)

**Comment by sujai1009** [comment]
my pseudo code

class LoggerConfig {
	constructor({ cradle }) {
                 this.LEVEL = "warn";
		this.getConfig = this.getConfig().bind(this);
	}

	getConfig() {
		return { "name" : "console"};
	}
}

// awilix containers
container.register({
	loggerConfigClass: awilix.asClass(LoggerConfig),
	loggerConfig: awilix.asFunction((loggerConfigClass) => loggerConfigClass.getConfig),  --- error in this line
});

ERROR:
weblogger/node_modules/awilix/lib/container.js:288
            throw err;
            ^
AwilixResolutionError: Could not resolve 'getConfig'.

**Comment by jeffijoe** [comment]
Oh you are using the proxy, just add braces to the parameters then

**Comment by sujai1009** [comment]
Thanks jeff it worked like a CHARM... i like this framework. Thanks for the support.
