### ISSUE TITLE
Return list of loaded modules in `container.loadModules()`

### ISSUE THREAD

**Issue by axelrindle** [jeffijoe/awilix#246]
I'm currently using `awilix` to load a bunch of services and manually call an `init` function afterwards on all of the loaded services. While it's currently hardcoded which services need initialization, it would be a helpful addition when `container.loadModules()` returns a list of the modules it has loaded, like the following:

```typescript
const loaded: string[] = container.loadModules(...); // e.g. ['database', 'redis', 'auth']

// initialize services
for (const service of loaded) {
    try {
        await container.resolve(service).init();
    } catch (error) {
        console.error(error);
    }
}
```

**Comment by jeffijoe** [comment]
You can iterate `container.registrations` afterwards.

**Comment by axelrindle** [comment]
Works, thank you :+1:
