### ISSUE TITLE
[Question] - Resolve by class reference

### ISSUE THREAD

**Issue by klausXR** [jeffijoe/awilix#248]
Is it possible to not provide a name to the registration and instead use the class reference to get an instance, for example

```js
class MyClass {
  constructor(...) {}
}

container.register(MyClass, { lifetime: Lifetime.SCOPED });

// Then, in another file, get an instance of the class, pointed by reference
container.resolve(MyClass)
```

I'm trying to implement something similar to NestJS's event system and the subscriber classes are registered in the DI container, so that their dependencies can be resolved automatically.

This causes a little bit of an issue with naming conflicts ( can only use `OrderCreatedListener` once ) and I think it would be better if I was able to use a reference to the class as a key and not deal with naming collisions.

[Example of NestJS Registration](https://github.com/nestjs/nest/blob/master/sample/30-event-emitter/src/orders/orders.module.ts)

**Comment by jeffijoe** [comment]
Not like that, but you _could_ do something like

```js
class MyClass {
  static name = Symbol('My Class')

  constructor(...) {}
}

container.register(MyClass.name, { lifetime: Lifetime.SCOPED });

container.resolve(MyClass.name)
```

**Comment by klausXR** [comment]
Thanks for the quick answer. Yes, I figured that solution myself, but I didn't really like the API for this specific use-case.

I know that this type of registration cannot work through the cradle directly, one would only be able to resolve a reference like this through `container.resolve(MyClass)`, but I'm fine with that.

Is there an easy way for me to extend the container class so that this becomes possible in my project or is it too coupled with the internals of the library?

**Comment by jeffijoe** [comment]
If you don't care about lifetime, then you could skip registration and just do `container.build(asClass(MyClass))`

If you do, then you can wrap the container and keep a map like this.

```ts
// DISCLAIMER: I didn't test or compile this
function MyContainer(container: AwilixContainer) {
  const symbols = new Map<Function, Symbol>()
  return {
    register(Class) {
      const sym = Symbol('registration')
      symbols.set(Class, sym)
      container.register(sym, asClass(Class).scoped())
    },
    resolve(Class) {
      const sym = symbols.get(Class)
      return container.resolve(sym)
    }
  }
}
```

**Comment by Toinouze** [comment]
I couldn't make the example work, the container still tries to resolve by property name. Is there any other way to resolve by class ?

**Comment by jeffijoe** [comment]
Are you on the latest version?

Also, it’s only going to work when calling resolve manually. You are trying to bend it in a way it was never intended to, and IMO it’s more trouble than its worth.
