### ISSUE TITLE
I Can't request method, like GET, POST, ETC..., using jest and supertest

### ISSUE THREAD

**Issue by godtaehee** [jeffijoe/awilix#252]
Hello, @jeffijoe 

Thank you for your awesome Dependency Injection Tool

before I talk about my Issue, I'm korean, So I can't fluently write english

Currently, I make some API with your tool

And I also write test code with jest and supertest

But, I can't request method, like GET, POST, ETC...

I make an effort to find why I can't request method

First, I register a controller in testcode typescript file

Second, I resolve this controller in awilixContainer

Third, the method in this **controller**(not container) is mockFunction

So, that's why I can't request any method

Can I overwhelm this Issue??

I could be that I'm not good at jest and supertest

This is my async method in resolved controller

![스크린샷 2021-08-13 오후 7 35 01](https://user-images.githubusercontent.com/44861205/129349057-2f2ee83c-ccb1-475f-b7d3-3f83f54d3c93.png)

I need your advice for this Issue

Thank you for reading my Issue

**Comment by jeffijoe** [comment]
Hi @godtaehee,

I'm sorry but I don't think I understand what your issue is. Are you using `awilix-koa`?

I suggest taking a look at [this repo](https://github.com/jeffijoe/koa-es7-boilerplate) for a working setup.

**Comment by godtaehee** [comment]
Thanks for your comment.

The skill in my project is awilix(not `awilix-koa`) which is in this repo and Express and TypeScript

Briefly, I use `awilixContainer` In my test code which written in typescript using `jest` and `supertest`.

And I resolve some method, This method is `Mock Function`

This method can't request HTTP Method.

Because This method Implementation is empty 

So, Can I get real Method? , not Mock Function

Sorry for not good at english

**Comment by jeffijoe** [comment]
If you register a mock function, you'll get the mock function back when you resolve it.

**Comment by godtaehee** [comment]
This is my project structure: 

![스크린샷 2021-08-13 오후 11 15 40](https://user-images.githubusercontent.com/44861205/129370723-7ba3a68f-6b88-4a63-87a0-ef2ea4b4d74f.png)

When I logging using `console.log` in src folder which is`dev` environment, not `test` Environment.

As you can see in above Screen shot, Resolved method is not `Mock Function` which contains real code Implementation.

This method is made by me.

I also want to use it in my `test` Environment << This is my purpose

![스크린샷 2021-08-13 오후 11 11 32](https://user-images.githubusercontent.com/44861205/129370206-9770ac68-8d38-46fc-bca6-1ff134d36c79.png)

On the other hand, below Screen shot is the situation which is logging also using `console.log` in `test` environment.

As you can see in below Screen shot, Resolved method is `Mock Function` which contains `Empty` Implementation

So I think that this empty method can do nothing

Because of this reason I can't use any HTTP Request.

![KakaoTalk_Photo_2021-08-13-23-18-28](https://user-images.githubusercontent.com/44861205/129371164-41cafa00-03c6-4842-8458-b742221fc683.png)

**Comment by jeffijoe** [comment]
I would need to see your code to better help you.

**Comment by godtaehee** [comment]
Yes!! Thank you for your kindness Comment

I think so. But This project is private task for getting a job

That's why I only contains limited screen shot. Sorry for @jeffijoe 

Can I comment one week later or two weeks later ??

When I finished this project, I will make some example about this Issue! 🙏

**Comment by jeffijoe** [comment]
Closing as this does not seem to be an issue with Awilix itself.
