### ISSUE TITLE
Supporting optionals in `PROXY` mode

### ISSUE THREAD

**Issue by richardsimko** [jeffijoe/awilix#269]
This is more of an RFP than an issue. I was trying to think of a way to be able to make DI arguments optional even in Proxy mode (We use it for the named params which decouples tests from param order).

Would it perhaps be possible to do this in a similar way to [loading non-default](https://github.com/jeffijoe/awilix#auto-loading-modules) modules?

```js
import { OPTIONAL } from 'awilix';

const fooModule = ({ foo, bar }) => {
    const run = () => {
        if(!foo) {
            // foo was optional
        }
    };
    return { run };
};

fooModule[OPTIONAL] = ['foo'];

export default fooModule;
```

I'm happy to submit a PR for this but I wanted to get some feedback on the idea first to see if it's feasible or if it's been discarded previously for some reason.

**Comment by jeffijoe** [comment]
[Here](https://github.com/jeffijoe/awilix/blob/0c4ee7de838aad451503be08c0d00498b408bc2d/src/resolvers.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L463-L483) is the point where to check the injection mode, and based on that resolve the dependencies and instantiate the target. Currently, if no local injections are configured, we use the container proxy rather than creating a new one.

> CLASSIC already has a way of doing optionals I thought? But now I can't find it in the docs. But yeah, my idea was that this would only apply to PROXY.

Correct, but I am concerned that it would be confusing for the `OPTIONAL` symbol to only affect `PROXY`.

**Comment by jeffijoe** [comment]
I have done the same as you; `null` = "I want it to be null".

Which one should we go with?

**Comment by richardsimko** [comment]
I think making `null` an explicit definition sounds like a good balance, this allows for supplying nullable arguments without treating `undefined`/not present differently.

**Comment by jeffijoe** [comment]
Then again, allowing the following would be nice:

```ts
class Foo {
  constructor({ db, timeout = 10_000 }) {
    console.log(timeout) // 10000
  }
}
```

Do you happen to know if we were to use `undefined` explicitly if that would work?

**Comment by richardsimko** [comment]
If you explicitly supply `undefined` to that constructor it will default to `10000`. I guess a good argument could be made for `undefined` as default in the `defaultArgs` hash being taken as meaning "Default will be provided in the constructor and if not leave me alone, I know what I'm doing".

Another option would be to have a separate option for ignoring unresolved:

```js
container.register({
  fooModule: asClass(FooModule)
    .withDefaultArgs({ foo: undefined })
    .ignoreUnresolved(['timeout'])
})
```

With the equivalent in the `RESOLVER` hash:

```js
fooModule[RESOLVER] = {
  defaultArgs: {
    foo: 'bar'
  },
  ignoreUnresolved: ['timeout']
}
```

Where they can both be used either together or `ignoreUnresolved` can be used to specify all the defaults in the constructor.

**Comment by jeffijoe** [comment]
I think `withDefaultArgs` with `undefined` makes sense then.

**Comment by richardsimko** [comment]
Sounds good! I will try to get a PR in during the weekend

**Comment by jeffijoe** [comment]
Closing, see discussion in #273. Basically, the use case can be solved with `.inject`.
