### ISSUE TITLE
The `disposer` is not called when not resolved in root container

### ISSUE THREAD

**Issue by moltar** [jeffijoe/awilix#275]
Not sure if this is a bug, or if this is supposed to work this way.

But `disposer` is never called, if a dependency was _not_ resolved in the root, but only in the scoped container.

Here are the tests:

```ts
import { asFunction, AwilixContainer, createContainer } from 'awilix'

describe('awilix', () => {
  let container: AwilixContainer
  let disposer: any

  beforeEach(() => {
    disposer = jest.fn().mockResolvedValue(true)

    container = createContainer()

    container.register({
      name: asFunction(() => 1)
        .scoped()
        .disposer(disposer),
    })
  })

  it('should dispose when scoped - fails', async () => {
    expect.assertions(2)

    const scope = container.createScope()

    // needs to resolve first for dispose to be called
    expect(scope.cradle.name).toBe(1) // force to resolve

    await container.dispose()

    expect(disposer).toHaveBeenCalledTimes(1) // <--- FAILS
  })

  it('should dispose when scoped - works', async () => {
    expect.assertions(3)

    const scope = container.createScope()

    // needs to resolve first for dispose to be called
    expect(container.cradle.name).toBe(1) // force to resolve root
    expect(scope.cradle.name).toBe(1) // force to resolve scope

    await container.dispose()

    expect(disposer).toHaveBeenCalledTimes(1)
  })
})
```

**Comment by jeffijoe** [comment]
This is expected. From the [docs](https://github.com/jeffijoe/awilix#:~:text=Important%3A%20the%20container%20being%20disposed%20will%20not%20dispose%20its%27%20scopes.%20It%20only%20disposes%20values%20in%20it%27s%20own%20cache.):

> Important: the container being disposed will not dispose its' scopes. It only disposes values in it's own cache.

**Comment by moltar** [comment]
Yeah, I now see that. This does not feel intuitive. We discussed this inside our team, and maybe it's due to the naming?

The docs use both "scope" and "parent/child" terminology.

In both cases, familiar paradigms dictate that destroying the outer layer destroys the inner layer(s).

- Scoped variables get destroyed and garbage-collected automatically, when the scope is destroyed.
- In OOP when you destroy an object, all inner held values get destroyed _(unless they have outside references)_.
- In DOM when the parent element is destroyed, child elements are also destroyed.

What Awilix does is more akin to "cloning". Where resulting containers are actually more like siblings, just with an added bonus of caching some of the references. Is that more accurate?

**Comment by jeffijoe** [comment]
It wouldn’t be possible to do without tracking scopes, and if one forgets to dispose the scope then it’ll result in a memory leak, and at that point if you are already disposing scopes correctly then disposing the root wouldn’t be disposing any scoped resources anyway.
