### ISSUE TITLE
Inline resolver name ignores loadModules formatName option

### ISSUE THREAD

**Issue by simonrenoult** [jeffijoe/awilix#279]
Hi,

Given this setup:

```js
// user-service.js
const {RESOLVER} = require("awilix");

class UserService {
}

UserService[RESOLVER] = {
    name: 'UserService'
}

module.exports = UserService

// container.js
const awilix = require('awilix')

const container = awilix.createContainer()

container.loadModules(
    ['user-service.js'],
    { formatName: 'camelCase'}
);
```

I expected `UserService` to be available under `container.cradle.userService` instead of `container.cradle.UserService` since `formatName: 'camelCase'` is provided. But it seems like the inline resolver name takes precedence over the loadModules options which I did not expect and didn't see any mention in the doc.

Not sure if a bug or feature but I thought it was worth mentioning.

**Comment by jeffijoe** [comment]
> it seems like the inline resolver name takes precedence

Yes, inline options always take precedence since they are more specific and targeted at a particular module. Kind of like CSS selectors. 😉 

>  didn't see any mention in the doc.

It's [right here](https://github.com/jeffijoe/awilix#:~:text=Additionally%2C%20if%20we%20add%20a%20name%20field%20and%20use%20loadModules%2C%20the%20name%20is%20used%20for%20registration.).

**Comment by simonrenoult** [comment]
> It's right here.

Thanks for the pointer. I read that part of the documentation. I meant that the precedence rule is never mentioned explicitly. And since I was taken by surprise and asked you if it was a bug or not, I figured others would be too. A few words in the documentation would have helped me.

Like:

> Additionally, if we add a name field and use loadModules, the name is used for registration.
> Additionally, if we add a name field and use loadModules, the name is used for registration (ignoring `formatName` if provided).

I'd be happy to do it if that's OK with you. Otherwise have a good day.

Cheers.

**Comment by jeffijoe** [comment]
Yeah that'd be a good change, feel free to open a PR. 😄
