### ISSUE TITLE
Deno Support

### ISSUE THREAD

**Issue by KnorpelSenf** [jeffijoe/awilix#281]
This amazing project has served me well on Node.js.

Recently, Deno became good enough that I personally prefer to develop for it rather than for Node. It would be great to have awilix available there, too, with all its maturity.

Are you planning on adding support for Deno yourself?

I am maintaining/overviewing around 20 hybrid projects that target both runtimes, and while I'm not planning on becoming a long-term contributor to awilix, I can certainly imagine to help with this particular effort. Are you willing to accept pull requests which will allow this project to be published at https://deno.land/x?

**Comment by jeffijoe** [comment]
I would be willing to accept a pull request adding support for this if you would be able to provide help with maintaining it as I have never used Deno myself.

**Comment by KnorpelSenf** [comment]
There are three mutually exclusive ways to go about this.

1. Convert the node module to Deno automatically. This has proven to be very hard, because Node is funky and does not comply with a lot of web APIs. There are things like the (unstable) project denoify, but they do not work reliably on all npm modules. We may have a better chance here since there are not a lot of external dependencies, but I would prefer not to give another try.
2. Manually port the code to Deno (takes an afternoon), and compile the Deno module back to JS. This is an approach that looks a lot like building a regular Node module with a different, Deno-aware `tsc`. You still have your `package.json` file and generally the same setup. It's the least disruptive change. It's what I chose for most projects I've worked with, and it is a reliable and straightforward solution.
3. Manually port the code to Deno, delete all traces of Node.js, and compile what's left back to obtain the entire npm package. This approach not only generates the JS which can in turn be shipped, but it generates the complete npm module with all contained files such as README, `package.json`, and all the other things that should be packaged up. It is required to write a custom TS file which acts as build script and which can only be run by the Deno CLI. Personally, I do not consider this a good idea, but the reason why you may want to consider this is because it would use a library called `dnt`. It is developed by the Deno team.

I would go with approach 2. Does this work for you?

Feel free if you have any questions about this. I do not mind to elaborate.

**Comment by jeffijoe** [comment]
What goes into maintaining option 2?

**Comment by KnorpelSenf** [comment]
That depends a bit on how much you would like to change about the current setup of the repo.

It is possible to change almost nothing about it. If I'm not mistaken, the Node tools should be able to work on Deno code, too. (I have not tried this myself, though.) The only real difference in the source code is that you import dependencies via URLs instead of module identifiers. That's why I assume ESLint etc can handle it.

There will be a single point where external dependencies are included. You may want to choose different deps per platform. A trivial example setup for this is in the repo at https://github.com/grammyjs/router/tree/main/src. You can see that the whole code base is a single file, and it imports dependencies from a file called `./deps.deno.ts`. During compilation, the import will be rewritten to use `./deps.node.ts`. That way, you can have platform-specific code, and hence platform-specific imports, assuming they provide the same API.

However, it could also be possible that Deno provides the same libraries as Node with identical behaviour, so in that case the tooling will do this automatically, correctly, and transparently, so no platform-specific code is required. I'd have to investigate this and will describe it in the PR.

Hence, due to this potential doubling of import specifiers, you may perhaps have to update dependencies twice when you bump their versions, once per runtime.

That's about the largest maintenance burden I can think of.

The rollup config will probably need to be changed and operate on JS instead of TS, since the compilation is already performed before. I am not too familiar with rollup, but I assume this will rather make it easier, since rollup does not need TS config anymore? One could argue that it's a disadvantage to first compile the code with one tool and then bundle it with another one, but I do not really see why this could become a problem.

Otherwise, there are a few things that are not necessary to do, but that will ultimately _reduce_ the maintenance substantially, so it would make sense. You'd end up with less maintenance than you have to do now. (At least that's my experience, and it's part of the reason why I like Deno a lot.) Deno comes with a built-in formatter, linter, test runner, and bundler. These things are all written in Rust. That means that e.g. formatting a project with 100 files and 15K lines takes less than 100 ms. These tools work without any config and with reasonable defaults. For example, it may make sense to align the formatting with the Deno conventions, and run `deno fmt` to format the code. You can also add that as npm script. That way, you can get rid of your complete formatting config.

The same is true for linting and testing. I do not understand the bundling well enough yet, this may be more effort to port, and since your setup is already working, you might as well leave it with Node tooling, but that ought to be investigated.

**Comment by jeffijoe** [comment]
My primary concern would be that supporting Deno might prevent me from doing some things that aren't possible in Deno but are in Node — I have no idea what that could be since I am not familiar with it, but I just thought I would mention it. What are the biggest limitations/compatibility issues you have seen?

**Comment by KnorpelSenf** [comment]
This may have been the case some time ago, but at this point I am not worries that this could become an issue.

I already ported the complete code base of awilix to Deno (started after my last post) just to see how difficult it would be, and the only remaining challenge is that Deno cannot import via `require`. It uses dynamic `import` statements. Modules cannot be imported synchronously, since they are allowed to contain top-level awaits.

The options are:
1. refactor `listModules` to be synchronous on Node and async on Deno, requires a few duplicate lines here and there
2. branch out at runtime (check `typeof Deno !== 'undefined') and either return a promise if on Deno, or not if on Node
3. make a breaking change, and always return a promise

I'll try to come up with something pretty (or at least not ugly). Node 12 does not support dynamic imports, but we could end up with ESM support if we do this right.

**Comment by jeffijoe** [comment]
We already have ESM support for `loadModules` I think? There should be an option that makes it use ESM and Promise.

**Comment by KnorpelSenf** [comment]
Ohhh right! Sorry, I missed that, saw it now. Will push my WIP soon.

**Comment by KnorpelSenf** [comment]
Please check out the pull request. There are a number of things missing, this is early and incomplete work :)

You can still run `npm run build` to compile the library for Node.

You can run `deno cache src/awilix.ts` to type-check the Deno version.

I think I will need your help with some parts of the other config. For example, the rollup config never works for me, also not in a fresh clone of this repo. In other words, this does not work:
```bash
cd /tmp
git clone git@github.com:jeffijoe/awilix.git
cd awilix
npm i
npm run build
```
There are more things, but I'll try to fix these things myself before asking concrete questions.

**Comment by KnorpelSenf** [comment]
By "does not work", I mean this error:
```
> awilix@6.0.0 build
> rimraf lib && tsc -p tsconfig.build.json && rollup -c

Error loading `tslib` helper library.
[!] Error: Package subpath './package.json' is not defined by "exports" in /tmp/awilix/node_modules/rollup-plugin-typescript2/node_modules/tslib/package.json
Error: Package subpath './package.json' is not defined by "exports" in /tmp/awilix/node_modules/rollup-plugin-typescript2/node_modules/tslib/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/awilix/node_modules/rollup-plugin-typescript2/src/tslib.ts:11:23)
```
System info:
```bash
$ uname -srv && node -v && npm -v
Linux 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18)
v17.3.0
8.3.0

```

**Comment by jeffijoe** [comment]
Awesome!
