### ISSUE TITLE
Use faster glob library

### ISSUE THREAD

**Issue by sebaplaza** [jeffijoe/awilix#283]
Hello,

There is a chance to use a fastest glob library like :

- https://github.com/mrmlnc/fast-glob
- https://github.com/sindresorhus/globby

This could help to improve loading times when we have a lot of paths to analyse.

**Comment by jeffijoe** [comment]
I would be open to it. Are there compatibility issues?

/cc @KnorpelSenf Would any of those work on Deno?

**Comment by KnorpelSenf** [comment]
I can investigate that once I start work on the new attempt.

Either way there's no problem with using them on Node.

**Comment by KnorpelSenf** [comment]
It looks like globby forces awilix to drop CJS support.

**Comment by jeffijoe** [comment]
I don't think dropping CJS is an option yet.

**Comment by KnorpelSenf** [comment]
I agree.

@sebaplaza are there patterns which fast-glob doesn't support but glob does? What about result order, could this ever matter? In other words: would this optimisation be a breaking change for anyone using this library?

**Comment by sebaplaza** [comment]
Yes, in theory we should not have a breaking change.

-`glob` is based on `minimatch`
-`fast-glob` is based on `micromatch`

`micromatch` supports all of the same matching features as minimatch and multimatch

https://github.com/micromatch/micromatch#why-use-micromatch

I can propose a PR if you want

**Comment by sebaplaza** [comment]
I just made a PR to test the change, everything seems to work fine.

It's a drop-in replacement.
