### ISSUE TITLE
Incompatibility with ES5-Shim

### ISSUE THREAD

**Issue by sobrinho** [jeffijoe/awilix#286]
Cross-posting from https://github.com/es-shims/es5-shim/issues/480

> <img alt="Screen Shot 2022-03-08 at 22 11 15" width="770" src="https://user-images.githubusercontent.com/26460/157352966-2bf6dd8f-86df-49b6-a741-418f947f80ee.png">
> 
> <img alt="Screen Shot 2022-03-08 at 22 11 22" width="267" src="https://user-images.githubusercontent.com/26460/157352967-836e2ed6-06ec-48c6-af55-ca56b2dd6ba6.png">
> 
> Pinned the issue to spreading an object that without es5-shim does work.

**Comment by ljharb** [comment]
What seems like is happening is that awilix is reflecting on a Module Namespace object using Object.keys or similar, and is passing the result into `require`, but failing to filter out Symbols (like `Symbol.toStringTag`).

**Comment by ljharb** [comment]
Symbols are valid keys, but not a valid require path in node or bundlers.

**Comment by jeffijoe** [comment]
It's not calling `require` though. The error that is thrown is not related to `require`, it's indicating a missing registration in the container.

**Comment by ljharb** [comment]
aha, thanks, that was what i was confused about. appreciate the fix.

**Comment by jeffijoe** [comment]
Fixed in v7.0.0 which has been released to `npm`.
