### ISSUE TITLE
"Error.captureStackTrace is not a function" in non V8 browser using browser bundle

### ISSUE THREAD

**Issue by simonvizzini** [jeffijoe/awilix#288]
I'm using the browser bundle of awilix and when I try to resolve something that hasn't been registered it throws a `Error.captureStackTrace is not a function` error in non V8 browsers, like Firefox and Safari. Works fine in Chromium based browsers.

Problem is that `Error.captureStackTrace` is a V8 only non-standard function, see here on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#static_methods

It is being used here: https://github.com/jeffijoe/awilix/blob/master/src/errors.ts#L33

Maybe `Error.prototype.stack` could be used instead? It is also a non-standard property but at least supported by all browsers: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack
As far as I understood the stack property should be populated as soon as an Error is thrown.

**Comment by jeffijoe** [comment]
Uh-oh!

I suppose checking `if 'captureStackTrace' in Error` before using it makes sense? I'd rather have a bad stack trace than blowing up! 😅

**Comment by simonvizzini** [comment]
Yeah totally agree it would make sense to check it before using it :smile:

**Comment by jeffijoe** [comment]
Fixed and released in v7.0.1 😄
