### ISSUE TITLE
Resolver syntax broken by reactivity wrapping

### ISSUE THREAD

**Issue by cacampbell** [jeffijoe/awilix#290]
Hello, 

I recently ran into this issue working with vite, vue, and pinia to provide a services container for an app. 

main.ts
```
const app = createApp(App);
const services = createServices();
const store = createPinia();

store.use(() => {
  return { services: toRaw(services) };
});

app.use(store);
app.use(router);

app.mount("#app");
```

store code
```
...
    async doThing() {
      // Works
      this._stuff = await this.services.resolve("thingsService").getThings();
      // Doesn't work
      this._stuff = await this.services.cradle.thingsService.getThings()
    },
...
```

In console:
```
Error: Could not resolve '__v_isRef'.
```

I suspect that somehow the __v_isRef is being treated as the name of the service in the container, so calling `this.services.cradle` from the pinia store causes an incorrect `this.services.resolve("__v_isRef")` call.

**Comment by jeffijoe** [comment]
I am not familiar with any of those things, but it sounds like something is attempting to access a property on the cradle which will result in an attempted resolution due to the proxy.

Can you mark the container as something that should skip the reactivity check?

**Comment by cacampbell** [comment]
Yeah that's kindof what I was trying to do with the `toRaw` (this comes from Vue and is supposed to tell it to leave that object alone), but no dice! I think that marking it as non-reactive is still modifying stuff to have property `__v_isRef` set to `false`. 

:shrug: using `resolve("name")` is fine

**Comment by cacampbell** [comment]
oh hey I managed to do something similar today:

```
    formatUsdc(amount: BigNumber): string {
      return this.services.resolve("format")(amount.toNumber());
    },
```

```
vue-router.esm-browser.js:3285 Error: Could not resolve 'Symbol(Symbol.toPrimitive)'.

Resolution path: format -> Symbol(Symbol.toPrimitive)
```

**Comment by jeffijoe** [comment]
How is format registered?

**Comment by cacampbell** [comment]
```
    format: asFunction(formatRoundLocale, { lifetime: Lifetime.TRANSIENT }),
```

**Comment by jeffijoe** [comment]
You probably want `asValue(formatRoundLocale)`.

**Comment by cacampbell** [comment]
oh interesting! 

yeah I ended up just replacing this whole "service" with Intl.NumberFormat but good to know
