### ISSUE TITLE
container.loadModules no work on windows11

### ISSUE THREAD

**Issue by Roading** [jeffijoe/awilix#291]
When I use the `container.loadModules` on windows11,  the result of `console.log(container.registrations) ` is `{}`. The same code works on Ubuntu. I try to change the version of `awilix` and `awilix-koa` from v6 to v7, The problem still exisit.

the `app.ts` code is below:
```typescript
import { createContainer, Lifetime } from 'awilix'
import { scopePerRequest, loadControllers } from 'awilix-koa'
import Koa from 'koa'

const container = createContainer()
const app = new Koa()

container.loadModules([`${__dirname}/services/*.ts`], {
  formatName: 'camelCase',
  resolverOptions: {
    lifetime: Lifetime.SCOPED
  }
  // esModules: true
})
app.use(scopePerRequest(container))

app.use(loadControllers(`${__dirname}/routers/*.ts`))

console.log(container.registrations) // result is {}

app.listen(8080, () => {
  console.log('the server is started')
})
```
the `services/ApiService.ts` code is below
```typescript
import { IApi } from '../interfaces/IApi'
import { IData } from '../interfaces/IData'

export class ApiService implements IApi {
  getInfo(): Promise<IData> {
    return new Promise<IData>((resolve, reject) => {
      resolve({
        title: 'value from backend service',
        results: ['results item1', 'results item2', 'results item3']
      })
    })
  }
}

export default ApiService
```
the start command in `package.json` is blow:
```
"dev": "ts-node-dev --respawn --transpile-only ./src/app.ts",
```

**Comment by jeffijoe** [comment]
I wonder, what if you replace / with \ in the globs? I thought Node would normalize but its worth a shot.

**Comment by jeffijoe** [comment]
It could also be the fact that we are using fast-glob since #284 

@sebaplaza any idea if fast-glob has issues on Windows? Maybe we need to switch back.

**Comment by Roading** [comment]
> I wonder, what if you replace / with \ in the globs? I thought Node would normalize but its worth a shot.

I tried, but it didn't work. The `fast-glob` should be OK, because the routes was worked with `app.use(loadControllers("${__dirname}/routers/*.ts"))`.

**Comment by jeffijoe** [comment]
What if you use process.cwd() as the base instead of dirname? I think it may be the default even.

**Comment by jeffijoe** [comment]
The third example `services/*.ts` should work if the `cwd` option is used correctly as well.
