### ISSUE TITLE
container.loadModules formatName - module value is present in the descriptor parameter but not in the related type

### ISSUE THREAD

**Issue by drouian-m** [jeffijoe/awilix#294]
Hello, 

I juste find something strange in the container.loadModules formatName function.

The module value is present in the descriptor parameter but not in the ModuleDescriptor related type.

<img width="873" alt="Screenshot 2022-05-02 at 10 32 56" src="https://user-images.githubusercontent.com/1223419/166212037-77016310-060f-4901-bb9c-84c04da1a5c2.png">

Is it wanted ? If not, I can propose a PR to fix the ModuleDescriptior type if you want.

**Comment by jeffijoe** [comment]
Changed the parameter type to `LoadedModuleDescriptor`, shipped in 7.0.3.
