### ISSUE TITLE
Grouping registrations

### ISSUE THREAD

**Issue by cbernard73** [jeffijoe/awilix#296]
The challenge is that I register a bunch of event listeners that I need to resolve as the app is starting up (and before it receives a request) so that they are listening. At the moment to solve this challenge I am creating a `container` within the `container` that I use to store the listeners, but it's a bit of hack job. Any thoughts on how better to accomplish this?

```
const container = awilix.createContainer({
  injectionMode: awilix.InjectionMode.PROXY,
})

const listeners = awilix.createContainer()
listeners.loadModules(['./listeners/*.js'], { formatName: 'camelCase' })
container.register({ listeners: awilix.asValue(listeners) })

 container.loadModules(
    [
      ['./providers/*.js', Lifetime.SINGLETON],
      './listeners/*.js',
      './controllers/*.js',
    ],
    {
      formatName: 'camelCase',
    }
  )
```

and then in the bootstrapping code:

```
const container = require('./container')
const listeners = container.resolve('listeners')

for (const listener in listeners.registrations) {
  container.resolve(listener)
}

```

**Comment by jeffijoe** [comment]
You can use `listModules` and `container.build` instead. That way you won't need to register the listeners.
