### ISSUE TITLE
Best practices with Awilix (and DI in general)

### ISSUE THREAD

**Issue by orgalaf** [jeffijoe/awilix#297]
Not really an issue but thought this could be a good place to get input on best practice.
Here's a question that came up during our usage of awilix:
Consider that we have a service completely based on DI - service A.
We also have a lib which uses DI internally just because it's a better way of writing code. Let's call it lib B.
Service A imports lib B as a dependency and they don't explicitly share any resources.
Is it considered good practice to pass service A's DI container into lib B rather than lib B creating its own DI container?
Thanks

**Comment by jeffijoe** [comment]
I would personally close off `lib B`. If anything in B can be customized, it should be explicit. I wouldn't force a DI container on the consumer of my library.

**Comment by orgalaf** [comment]
Thanks!
