### ISSUE TITLE
Classic resolution mode fails to resolve single parameter arrow function

### ISSUE THREAD

**Issue by niyoko** [jeffijoe/awilix#30]
Awilix dependencies parser fails to detect factory function that is declared using arrow function with single parameter and no bracket enclosing the parameter.

How to reproduce:
Using `CLASSIC` resolution mode, declare following service. It will fail to parse the dependencies.

    module.exports = config => {
        return {
            a: (b, c) => b
        };
    }

But service below will work (notice brackets that enclose the parameter):

    module.exports = (config) => {
        return {
            a: (b, c) => b
        };
    }

I suspect this line causes the problem.

    const DEPS_EXPR = /(\(\s*([^)]+?)\s*\)|\(\))/

Awilix version: 2.6.0
Node version: 8.2.1

**Comment by jeffijoe** [comment]
Thanks for reporting! I'll look into this ASAP.

**Comment by jeffijoe** [comment]
I wrote a parser to substitute the regex and released the fix as 2.6.1. Please reopen if this does not fix your issue. Thanks!

**Comment by niyoko** [comment]
Thanks for the quick response!
I will update it to version 2.6.1 and see if this fixes my issue.

**Comment by niyoko** [comment]
Well, it successfully parse following function:

    const fn = a => {
        return {};
    };

    const fn = (a, b) => {
        return {};
    };

But it fails to parse old-school function declaration:

    const fn = function(a){
        return {};
    }; 

    function fn(a){
        return {};
    }

It returns `[ 'a', '{', 'return', '{};' ]`. It should return `['a']` only.

**Comment by jeffijoe** [comment]
Damn, I even have a test for that! I'll look into it, thanks for reporting back so quickly.

**Comment by jeffijoe** [comment]
Try 2.6.2 😄
