### ISSUE TITLE
How to change DI object for tests to a mock?

### ISSUE THREAD

**Issue by Chaz0r** [jeffijoe/awilix#301]
Hey folks,

I'm using awilix together with fastify and I'm pretty new to both technologies :D
I built a fastify application that completely works with dependency injection. In this case I use the classic constructor injection.

I register my dependencies like this into the diContainer that is provided by the fastify awilix plugin:

```
fastify.diContainer.register({
    config: asClass(Config).classic()
    configHandler: asClass(ConfigHandler).classic()
})
```

The Config class has a simple function that returns a string:

```
export class Config {
    getTest(): string {
        return "test"
    }
}
```

Then I have a route that maps to a function of the configHandler. The function itself only returns the value of getTest() as e response. And this completely works. The Handler looks like this:

```
export class ConfigurationHandler {

    private config: Config

    constructor(config: Config, fastify: FastifyInstance) {
        console.log(fastify.diContainer.registrations)
        this.config = config
    }

    async getConfiguration(request: FastifyRequest, reply: FastifyReply): Promise<string> {
        return this.config.getTest()
    }
}
```

Now I'm coming to the tests.
If I call the route of my tests with the methods fastify provides, everything works fine also. For example like this:

```
const reply = fastify.inject({
    method: 'GET',
    url: '/ping',
    headers: 
})
```

If I check this reply, it is the result of the getTest function. So also very nice!

Now I want to change the config in the DI to a config with a mocked function. I do the mocking with sinon like this:

```
const config = fastify.diContainer.resolve("config")

const spy = sinon.stub(config, 'getTest').callsFake(function () {
    return "someMockedValue"
})
```

If I then call `config.getTest()` the result is not "test" anymore, it is "someMockedValue". So this also works.

Now I want to override the existing config with the mocked version. How am I doing this?
I tried to re-register it and to me it looks like it actually gets replaced. If I log `fastify.diContainer`into my console, I can actually see that the container changes.

To me it looks like the problem is how and when dependencies get resolved. As you can see in the ConfigurationHandler above, I log the container registrations in the constructor. And what I figured out is that the log is only called exactly once. Even if I do more than one request, I can only see the log once. So the solution may be that I have to refresh the container somehow? 

Any ideas how I can achieve, what I want?

Thanks in advance!

**Comment by jeffijoe** [comment]
Not sure I can be of any help here since I don't know how the fastify plugin works. However if the dependency tree is resolved and cached before you get to replace the registration, then only subsequent resolves will get the new value, assuming you are using the default transient lifetime.

I would suggest constructing your app by passing in a container that you can modify before the app starts (resolves your handler).

**Comment by Chaz0r** [comment]
Okay, in the first place the issue is really completely about how fastify itself behaves. For other people who have problems like this and want to change the dependencies in tests during runtime: This is actually not possible. Fastify resolves everything during the server start. So during the start the DI container gets resolved and the result is what you get. No changing possible.

What I did now is to add a changeDependency function to my TestSuite. Inside my test, that extends an abstract TestSuite class, I do a fastify request like this:

```
const beforeMockResponse = await this.fastify.inject({
    method: 'GET',
    url: '/ping
})
t.equal(beforeMockResponse.body, this.config.getTest(), "Result should be the unmocked value")
```

Now I create a spy with sinon (every other mocking lib should also work)
```

const config: Config = this.fastify.diContainer.resolve("config")
    const spy = sinon.stub(config, 'getTest').callsFake(function () {
        return mockValueForTesting
})
```
Then I call my change Dependency method where I pass my dependency directly the way like Awilix would await it for registering:

```
await this.changeDependencies({
    config: asValue(config)
})
```

the changeDependencies method now does a few things:
At first I close the current fastify instance and create a new one.

```
this.fastify.close()
this.fastify = fastify()
await this.beforeStart(true)
```

beforeStarts resolves everything the app needs. It registers plugins, registers the dependencies into the awilix container and registers the router. In this case the "true" parameter says that registering the router should be ignored.
The reason is that we create the regular default dependency container again and if the router gets resolved all handlers have the unmocked, regular dependencies again. So we won nothing if we would register the routes here.

So after that I register my dependencies, that I pass into this function and then resolve the router manually:
```
this.fastify.diContainer.register(nameAndRegistrationPair)
await this.registerRouter()
```

after this I call ```this.fastify.ready()``` again so everything is finished

After this I have a new instance of fastify with new dependencies that include my mock and this test works:

```
const afterMockResponse = await this.fastify.inject({
    method: 'GET',
    url: '/ping
})
t.equal(afterMockResponse.body, mockedValue, "Result should be the mocked value")
```
