### ISSUE TITLE
How to merge containers

### ISSUE THREAD

**Issue by nguyentoanit** [jeffijoe/awilix#302]
Hi,

Is there a better way to merge containers into single container?

I'm trying to get registrations from the source container and register in target container like this:
```ts
import { asFunction, asValue, createContainer } from 'awilix'

const container1 = createContainer()
container1.register({
  name: asValue('container1'),
  value: asValue('1'),
  doSomething: asFunction(() => 'Function 1 is running'),
})

const container2 = createContainer()
container2.register({
  ...container1.registrations,
  doSomething: asFunction(() => 'Function 2 is running'),
})

console.log(container1.cradle.doSomething) // Function 1 is running
console.log(container2.cradle.doSomething)// Function 2 is running
console.log(container2.cradle.value) // container1
```

Thanks.

**Comment by jeffijoe** [comment]
That is pretty much how you'd do it. However keep in mind that each container maintains its' own resolution cache (singleton lifetimes) and also will attempt to dispose any configured disposables. What is your use case?

**Comment by nguyentoanit** [comment]
I want create containers which support for modularity.

At the moment, I have only one shared container.
And this will be shared for all modules in my application.

I want to split up this shared container by functionality (Database, Logger, API, etc).
And modules just import and merge containers into single container. 🤔 

Any suggestion?

**Comment by jeffijoe** [comment]
I think just using a single container would be best, I don't think you get any benefits from merging.
