### ISSUE TITLE
Make `useValue()` resolver disposable

### ISSUE THREAD

**Issue by cyantree** [jeffijoe/awilix#305]
I'm trying to combine async created services like database connections with application lifecycle management. That means that the service already is spin up before container configuration and should be disposed when the container gets disposed.

Currently I'm using this little workaround:
```js
const db = await getDbConnection();
container.register('db', asFunction(() => db).singleton().disposer((service) => service.close());
container.resolve('db');
```

So I immediately resolve the service to make sure it is cached and gets picked up by `.dispose()`.

However in my opinion making `asValue()` resolvers disposable would simplify this:
```js
container.register('db', asValue(await getDbConnection()).disposer((service) => service.close());
container.resolve('db');
```
In this case value services should also persisted into the cache immediately.

Or which common patterns do exist for this usecase?

**Comment by jeffijoe** [comment]
The idea is that the container should really only have to be responsible for disposing what it creates.

Your approach is fine if you are intent on creating the connections before registering them, but what if constructing the container fails?

**Comment by jeffijoe** [comment]
Well if I am passed in a thing that needs to be disposed, then I expect the outer code to manage that, so that would probably be in a `try finally`. But generally I try to not use async factories.

**Comment by cyantree** [comment]
Thanks for your point of view.

**Comment by jeffijoe** [comment]
Disposers are only run if the registration has been accessed via resolution. I would suggest resolving it immediately after registration to enroll in disposal.

**Comment by jeffijoe** [comment]
I generally use a utility like this for managing disposal:

```ts
import { MakeErrorClass } from 'fejl'

/**
 * Disposer
 */
export interface Disposer {
  addDisposer(fn: () => any): Disposer
  dispose(): Promise<void>
}

/**
 * Can be used as a callback when you don't want to expose
 * the whole disposer.
 */
export type AddDisposerDelegate = (fn: () => any) => unknown

/**
 * Controls how the disposers are called.
 */
export const enum DisposeConcurrency {
  /**
   * One at a time in reverse order (last in, first out). This is the default.
   */
  SerialLIFO,
  /**
   * Parallel in reverse order.
   */
  ParallelLIFO,
}

/**
 * Easy way to manage disposers.
 */
export function Disposer(
  concurrency = DisposeConcurrency.SerialLIFO,
): Disposer {
  let disposers: Array<() => Promise<any>> = []
  const disposer: Disposer = {
    /**
     * Add a disposer function.
     * @param fn
     */
    addDisposer(fn: () => any) {
      disposers.push(fn)
      return disposer
    },
    /**
     * Calls all disposers serially in First In Last Out order.
     */
    async dispose() {
      const copy = disposers.slice()
      disposers = []
      switch (concurrency) {
        case DisposeConcurrency.ParallelLIFO: {
          await Promise.all(copy.reverse().map((f) => f()))
          return
        }
        default: {
          const len = copy.length
          for (let i = len - 1; i >= 0; i--) {
            await copy[i]()
          }
        }
      }
    },
  }
  return disposer
}
```
