### ISSUE TITLE
extract param-parser as a library

### ISSUE THREAD

**Issue by sebaplaza** [jeffijoe/awilix#307]
Hello,

I was looking for a way to parse Class and functions parameters, and i was not able to find a good/stable library to do it ([lib1](https://github.com/plumier/plumier/tree/master/packages/reflect) , [lib2](https://github.com/captemulation/get-parameter-names#readme)).

I've been using awilix for a long time, without any issues. 

I think `param-parser` is a nice piece of code that we could extract as an external library (maybe create a awilix monorepo ?)

https://github.com/jeffijoe/awilix/blob/master/src/param-parser.ts

what do you think ?

**Comment by jeffijoe** [comment]
Awilix is MIT licensed so you are free to copy those bits and use them in your project as long as you include attribution 👍 

I don't plan to make Awilix a mono-repo right now, but I might in the future. If so then I would probably extract the parser into a library. 😄

**Comment by sebaplaza** [comment]
@jeffijoe just for information https://github.com/sebaplaza/paramsifier

thanks!

**Comment by jeffijoe** [comment]
Please put my name in the `LICENSE` file, as it's still my original code.

**Comment by sebaplaza** [comment]
done !
