### ISSUE TITLE
Support for async initializers

### ISSUE THREAD

**Issue by kibertoad** [jeffijoe/awilix#311]
Resolvers are synchronous by design, which is great, but sometimes modules are unusable until certain asynchronous logic is executed.

It would be great if we could register initializers for singleton modules, which would first call a resolver, and then execute provided async logic.

How it could be used: container would have a new method .asyncInit(), which would invoke initializers for all modules which have them. Then all future injections will provide fully initialized modules.

If this is approved, I can provide a PR.

**Comment by jeffijoe** [comment]
In the same spirit as [the request for eager-loading](https://github.com/jeffijoe/awilix/issues/310#issuecomment-1374428712), I think this is something that is so simple to do in user-land code with `.resolve` that it probably doesn't warrant expanding the API surface. As mentioned in the other issue, I would like to keep the scope to DI, whereas this sounds more like a hosting concern.

However, if we were to do this, then it sounds like this + #310 would cover the same use case, no? And how would registrations opt-in to this? Would it only affect singleton registrations? If so, then the lifetime requirement might cause confusion when opting into initialization and it not happening. That's also why I think doing this manually is probably the best call.

**Comment by kibertoad** [comment]
Similarly to the eager-loading one, while it is technically possible to do so, it requires having second configuration for what conceptually is a part of DI, resulting in worse developer experience and less clean code.

Awilix already has the concept of DI lifecycle, which currently has two phases - creation and disposal. It is quite traditional for DI engines to support additional lifecycle phases, e. g. see PostConstruct in Java: https://stackoverflow.com/questions/3469073/something-in-spring-like-init-method-but-called-after-dependencies-are-injecte

Inversify handles similar cases by using Providers: https://github.com/inversify/InversifyJS/blob/master/wiki/provider_injection.md

API suggestion:
```
    permissionConsumer: asClass(PermissionConsumer, {
      initializer: () => {
      // execute some async logic
    },
    }),
```

Use-case is different between this and eager resolution. Eager resolution is synchronous. Initializer is asynchronous.

Registrations opt-in by defining an initializer, if they don't have it, they do nothing on `.asyncInit()` call on Container.

Considering that resolve operation is synchronous, I don't think it's particularly confusing that asynchronous operations are not resolved for new instances created that way. Support for non-singletons can also be added, but would require invoking a new resolveAsync method. In order to reduce confusion, synchronous resolve can be throwing an error if someone would invoke it on a Resolver with initializer field defined.

**Comment by jeffijoe** [comment]
Closing as out of scope for Awilix, see [this comment](https://github.com/jeffijoe/awilix/issues/310#issuecomment-1375445068) for perspective.

**Comment by kibertoad** [comment]
If someone found this in 2024 - [awilix-manager](https://github.com/kibertoad/awilix-manager) is the solution.
