### ISSUE TITLE
Grouped registrations

### ISSUE THREAD

**Issue by FowiFlowi** [jeffijoe/awilix#314]
Hi! First of all, thank you for your work 💪

I'm sharing here the use case to talk about possible solutions.
Let's say we have two types of registrations (`actions` and `event listeners`) located in different folders, which I load using the `loadModules` method. And then, when I need only `actions` I have no convenient ways to resolve them using some common tag. The only way is to manage some prefixes literally in registration names and aggregate them manually through a separate registration.

A possible solution could be an option for the `loadModules` method, which will aggregate all modules under one registration as an array

**Comment by jeffijoe** [comment]
It sounds like you know how those modules would be laid out, so you could use `listModules` and create the resolvers, then register a single one that just calls `container.build()` on each.

**Comment by FowiFlowi** [comment]
Hmm, so I can replace loadModules with listModules using my custom logic. Ok, thank you!
