### ISSUE TITLE
Auto loading modules customization

### ISSUE THREAD

**Issue by mcarrf90-bz** [jeffijoe/awilix#316]
I have the following structure for example for my user folder:

- services
- controllers
- models
- tests

What I'm trying to do is auto loadModules with 
`container.loadModules(['src/user/**/*.js'], {
  formatName: 'camelCase',
  resolverOptions: {
    injectionMode: InjectionMode.PROXY,
    register: asClass,
  },
});`

My issues are the following:

- I want my models to have formatName of PascalCase, not camelCase
- I want to leave the tests folder out of the injection to the container

Any help will be really appreciated

**Comment by jeffijoe** [comment]
Then you will need to break up your globs.

```js
import { pascalCase } from 'pascal-case'

container.loadModules(['src/user/{services,controllers}/*.js'], { 
  formatName: 'camelCase', 
  resolverOptions: { injectionMode: InjectionMode.PROXY, register: asClass, }
});

container.loadModules(['src/user/models/*.js'], { 
  formatName: name => pascalCase(name), 
  resolverOptions: { injectionMode: InjectionMode.PROXY, register: asClass, }
});
```

**Comment by mcarrf90-bz** [comment]
Excellent! Thanks for your response, I have a semantical question. If I do
```

container.loadModules(['src/**/controllers/*.js'], { 
  formatName: 'camelCase', 
  resolverOptions: { injectionMode: InjectionMode.PROXY, register: asClass, }
});

```

Will this inject every controller for each folder inside the src folder?

**Comment by jeffijoe** [comment]
That should work

**Comment by jeffijoe** [comment]
You want to specify the `cwd` option rather than using `src` in your glob.

**Comment by mcarrf90-bz** [comment]
Hi Jeff, is there a chance you could be more explicit? Not sure how to implement what you are mentioning me,

Thanks in advance!

**Comment by jeffijoe** [comment]
Specify a relative `cwd` based on the location of your container creation module. For example, if your container is in `app.js` and your structure is:

```
- src/foo/services/my-service.js
- app.js
```

```js
container.loadModules(
  [
    'src/**/services/*.js',
    ...etc
  ],
  {
    cwd: __dirname,
    ...etc
  },
);
```
