### ISSUE TITLE
Clear, Concrete introduction in README.md needed.

### ISSUE THREAD

**Issue by swithrow** [jeffijoe/awilix#320]
Note: I'm writing this in response to my initial reaction to visiting the project on GitHub.

The phrase "Make IoC great again" may be off-putting to users considering adopting Awilix into their project, and should be removed. The phrase may come across as overly gimmicky or flippant, which could undermine the credibility of Awilix as a serious and reliable tool for developers. It's important to present the benefits of Awilix in a clear, straightforward manner. And it calls to mind the "Make America Great Again" movement, which is an association the project may not want to have.

My suggestion is to replace the exclamation in `README.md` with a more informative introduction to the benefits of using Awilix, and dependency injection in general. For example:

"Awilix is an exceptional Dependency Injection container for large codebases that offers several practical benefits. It simplifies complex code, making it easier to manage and update over time. The container promotes modular and scalable code architecture, allowing you to create more efficient and maintainable code. It enhances the testability of your codebase, making it easier to identify and fix bugs. Additionally, Awilix promotes code reusability, which helps reduce duplication and increases efficiency in your development process. Overall, adopting Awilix can significantly streamline your development process and improve the quality of your codebase"

Someone else with more familiarity with the project could probably write something better.

**Comment by juicemia** [comment]
Note: I'm writing this in response to my initial reaction to your comment.

Well, I guess we'll have to settle for making IoC slightly above average then.

**Comment by jeffijoe** [comment]
@swithrow I have made the change. 

The phrase was indeed a play on "Make America Great Again", but it was made apolitically and in jest. It has been in the same spot in the README for the past 7 years, and Awilix has grown a lot on its own since then, so I doubt people were reading into it. It was just a way to poke fun at the (back then) sad state of DI in JavaScript.
