### ISSUE TITLE
Awilix is not creating instance of the class i pass as an dependency

### ISSUE THREAD

**Issue by kiratxsinghx** [jeffijoe/awilix#322]
hi jeff im am new to Awilix hope you could help :)
 
what i am doing is i am passing a registering a restUtil as a dependency in my container and i am destructing it in a constructor where i want to use it but it is giving me the error of 

AwilixResolutionError: Could not resolve 'Symbol(Symbol.toPrimitive)'.

here is my code :::

class OauthUtil {
    constructor({config, RestUtil, CommonUtil, MessageUtil}) {
        console.log("here in the oath Util")
        this.config = config;
        this.CommonUtil = CommonUtil;
        this.restUtil =  RestUtil;
        this.MessageUtil = MessageUtil;
        this.mongoose = new MONGOOSEDB();
        this.getAccessToken = this.getAccessToken.bind(this);
        this.createAccessToken = this.createAccessToken.bind(this);
        this.getAuthorizationAccessToken = this.getAuthorizationAccessToken.bind(this);
        this.createAuthorizationAccessToken = this.createAuthorizationAccessToken.bind(this);
    }

and the code where i am using a restutil

    async createAccessToken(type, update_time) {
        try {
            let data = {
                "client_id": this.config.get('client_id'),
                "client_secret": this.config.get('client_secret'),
                "audience": `${this.config.get('audience_management_api')}`,
                "grant_type": "client_credentials"
            };
            let options = {
                headers: { 'content-type': 'application/json' },
            }
            let url = this.config.get('oauth:token_url');
            let response = await this.restUtil.postRequest(url, data, options);
            this.storeAccessToken(type, response.data, update_time, this.MessageUtil.info().oauth_token.management)
            return response.data;
        } catch (err) {
            console.log("err createAcceessToken:::", err)
            throw new Error(err);
        }
    }

i am calling the method of Oauth.createAccessToken from my authentication controller and but im not able to call restutil function postRequest i dont know why 

have any suggestion for me

**Comment by jeffijoe** [comment]
It looks like you are mixing injection modes, but its hard to tell without your container configuration

**Comment by kiratxsinghx** [comment]
thanks for your reply 

here are my container configuration 

const container = awilix.createContainer();
class Container {
    constructor(keys) {
        container.register({
            config: awilix.asClass(config).setInjectionMode(awilix.InjectionMode.CLASSIC).singleton(),
            // CheckJWT: awilix.asClass(CheckJWT).setInjectionMode(awilix.InjectionMode.CLASSIC).singleton(),
            authenticationService : awilix.asClass(AuthenticationService),
            authenticationController : awilix.asClass(AuthenticationController),
            DateUtil : awilix.asValue(DateUtil),
            RestUtil : awilix.asClass(RestUtil),
            CommonUtil : awilix.asValue(CommonUtil),
            MailUtil : awilix.asValue(MailUtil),
            MessageUtil : awilix.asValue(MessageUtil),
            OauthUtil : awilix.asClass(OauthUtil),
        }),
        this.resolve = this.resolve.bind(this);
    }
    resolve(key) {
        return container.resolve(key);
    }
}

module.exports = Container;

**Comment by jeffijoe** [comment]
Yes, as I suspected, you are mixing injection modes which I don’t recommend. One of your modules are likely treating a parameter as some other module but in reality its the container cradle (proxy).

**Comment by kiratxsinghx** [comment]
SO what i can do any suggestions

**Comment by jeffijoe** [comment]
Either avoid mixing injection modes or find the module that is assuming `CLASSIC` but is actually using `PROXY` (default).

**Comment by jeffijoe** [comment]
What are you resolving first?

**Comment by kiratxsinghx** [comment]
i am resoling authenticationController in my authenticationRouter module

`const Container = require("../container") ;
const ContainerINST = new Container() ;
const AUTHENTICATIONCONTROLLERINST = ContainerINST.resolve("authenticationController"`

**Comment by jeffijoe** [comment]
Then look at the constructor of `AuthenticationController`, you are likely treating it as `CLASSIC` even though it's registered as `PROXY`.

**Comment by kiratxsinghx** [comment]
here is the constructor of authentication controller 
```

class AuthenticationController {
  constructor({authenticationService, config, DateUtil,RestUtil, CommonUtil, MessageUtil, OauthUtil}) {
    this.DateUtil = DateUtil ;
    this.config = config ;
    // console.log("config here:::::::::::", this.config)
    this.authService = authenticationService;
    // this.authService = new AUTHENTICATIONSERVICE(config);
    this.rbacController = new RBACCONTROLLER(this.config);
    this.restUtil = RestUtil;
    this.OauthUtil = OauthUtil;
    this.CommonUtil = CommonUtil;
    this.MessageUtil = MessageUtil ;
```

**Comment by jeffijoe** [comment]
What is the full stack trace of the error?

**Comment by kiratxsinghx** [comment]
so what im doing is im resolving the `AuthentiationController` from the` AuthenticationRoute ` 
```
const Container = require("../container") ;
const ContainerINST = new Container() ;
const AUTHENTICATIONCONTROLLERINST = ContainerINST.resolve("authenticationController") ;
```
then im calling `FindUserByEmailForLogin` function from the `AuthentiationController` 
`
router.get("/login/:email",checkJwt, AUTHENTICATIONVALIDATIONINST.findUserByEmailForLogin(), result_validator, AUTHENTICATIONCONTROLLERINST.findUserByEmailForLogin);`

and then in `AuthentiationController` constructor im destructing the dependcies

```
class AuthenticationController {
  constructor({authenticationService, config, DateUtil,RestUtil, CommonUtil, MessageUtil, OauthUtil}) {
    this.DateUtil = DateUtil ;
    this.config = config ;
    // console.log("config here:::::::::::", this.config)
    this.authService = authenticationService;
    // this.authService = new AUTHENTICATIONSERVICE(config);
    this.rbacController = new RBACCONTROLLER(this.config);
    this.restUtil = RestUtil;
    this.OauthUtil = OauthUtil;
    this.CommonUtil = CommonUtil;
    this.MessageUtil = MessageUtil ;

```
and In `FindUserByEmailForLogin` im calling a function from `OauthUtil` (i pass `OauthUtil` as dependency in `AuthentiationController`)
```
class OauthUtil {
    constructor({config, RestUtil, CommonUtil, MessageUtil}) {
        console.log("here in the oath Util")
        this.config = config;
        this.CommonUtil = CommonUtil;
        this.restUtil =  RestUtil;
        this.MessageUtil = MessageUtil;
        this.mongoose = new MONGOOSEDB();
```

and then In `OauthUtil` 's Function `CreateAccessToken` I am using `RestUtil` which i pass as an dependency in `OauthUtil`'s constructor 

 ```
   async createAccessToken(type, update_time) {
        try {
            let data = {
                "client_id": this.config.get('client_id'),
                "client_secret": this.config.get('client_secret'),
                "audience": `${this.config.get('audience_management_api')}`,
                "grant_type": "client_credentials"
            };
            let options = {
                headers: { 'content-type': 'application/json' },
            }
            let url = this.config.get('oauth:token_url');
            let response = await this.restUtil.postRequest(url, data, options);
            this.storeAccessToken(type, response.data, update_time, this.MessageUtil.info().oauth_token.management)
            return response.data;
        } catch (err) {
            console.log("err createAcceessToken:::", err)
            throw new Error(err);
        }
    }
```


when i `restUtil` Try to call its function `PostRequest` its is giving me an error

**Comment by kiratxsinghx** [comment]
```
createAcceessToken::: AwilixResolutionError: Could not resolve 'Symbol(Symbol.toPrimitive)'.

Resolution path: Symbol(Symbol.toPrimitive)
    at resolve (/home/kirat/microservices/authentication_managing_microservice/backend/microservice/authentication/node_modules/awilix/lib/container.js:252:23)
    at Object.get (/home/kirat/microservices/authentication_managing_microservice/backend/microservice/authentication/node_modules/awilix/lib/container.js:66:33)
    at parseInt (<anonymous>)
    at dispatchHttpRequest (/home/kirat/microservices/authentication_managing_microservice/backend/node_modules/axios/lib/adapters/http.js:342:21)
    at new Promise (<anonymous>)
    at httpAdapter (/home/kirat/microservices/authentication_managing_microservice/backend/node_modules/axios/lib/adapters/http.js:48:10)
    at dispatchRequest (/home/kirat/microservices/authentication_managing_microservice/backend/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/kirat/microservices/authentication_managing_microservice/backend/node_modules/axios/lib/core/Axios.js:108:15)
    at Axios.<computed> [as post] (/home/kirat/microservices/authentication_managing_microservice/backend/node_modules/axios/lib/core/Axios.js:140:17)
    at Function.wrap [as post] (/home/kirat/microservices/authentication_managing_microservice/backend/node_modules/axios/lib/helpers/bind.js:9:15)
errr::::::::: Error: AwilixResolutionError: Could not resolve 'Symbol(Symbol.toPrimitive)'.

Resolution path: Symbol(Symbol.toPrimitive)
    at OauthUtil.createAccessToken (/home/kirat/microservices/authentication_managing_microservice/backend/common/utils/Oauth-util.js:61:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async OauthUtil.getAccessToken (/home/kirat/microservices/authentication_managing_microservice/backend/common/utils/Oauth-util.js:31:29)
    at async AuthenticationController.findUserByEmailForLogin (/home/kirat/microservices/authentication_managing_microservice/backend/microservice/authentication/controller/authentication-controller.js:692:19)
undefined Error: Error: AwilixResolutionError: Could not resolve 'Symbol(Symbol.toPrimitive)'.

Resolution path: Symbol(Symbol.toPrimitive)
    at OauthUtil.getAccessToken (/home/kirat/microservices/authentication_managing_microservice/backend/common/utils/Oauth-util.js:40:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AuthenticationController.findUserByEmailForLogin (/home/kirat/microservices/authentication_managing_microservice/backend/microservice/authentication/controller/authentication-controller.js:692:19)

```

**Comment by jeffijoe** [comment]
If you look at the stack trace, it'll give you some hints. For example, Axios' `dispatchHttpRequest` is somehow triggering `resolve` in Awilix. This likely means you passed in the `cradle` somewhere to Axios, likely in your `restUtil`.

**Comment by kiratxsinghx** [comment]
hi jeff thanks for your help my pervious error got resolved..
now what i m trying to do is register dependencies using `loadModules` 

but `loadModules` is not working as it is not registering any dependencies

my code :

` .loadModules([
            "service/**/*",
            "controller/**/*",
            "routes/**/*",
        ],
            {
                resolverOptions: {
                    lifetime: awilix.Lifetime.SCOPED,
                    register: awilix.asClass,
                },
                formatName: 'camelCase'
            }
        )
        this.resolve = this.resolve.bind(this);
        console.log("In the container.js",container.registrations )
    }`

app structure::

-->app
         -->service
                       ->userService
                       ->anyotherservice
           -->controller
                       ->userController
                       ->anyotherController
          -->routes
                       ->userRoutes
                       ->anyotherRoutes
         -->Contanier.js


ERROR : ` AwilixResolutionError: Could not resolve 'authenticationRoute'.
`
any Suggestions or advice :)

**Comment by jeffijoe** [comment]
Have you [followed the documentation](https://github.com/jeffijoe/awilix#auto-loading-modules) for how to set up your modules for auto-loading?

**Comment by jeffijoe** [comment]
Closing this since it's not an issue.
