### ISSUE TITLE
Shouldn't `asClass` type-check the constructor parameters?

### ISSUE THREAD

**Issue by moltar** [jeffijoe/awilix#326]
Been a happy user for a while, but one thing I still don't get is the lack of type-checking support.

Am I holding it wrong?

---

[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAQwM5IKazgMyhEcDkyas+AUKJBgN6JIDCANkQDS0BqCDArqqwMZRUCGKjoQAdjATBx6OAF8sOPIQDuwBsAAeZcpPSYEfVHDpwqpOHABunAFxxxXEACN0luH058Hdb1yYYaFJ5UlI+JhRTf0Docw9BJACYBydXdw8AekyrXLy4QF4NwHEdwB4NwG-90wkkGCguPiCoODAEKAQQVBFG4CRHCHg+XGaYYBcGVA8B8Wra+ugACgQHaZkAcwBKeLyYAAtugDpE5LgAXkQ9sfEVnbgAKjgAJg9Q0PCq-pPPQWFRCSkZdAAPHQAHxzNZhPgHVArbqdOYWKy2BgOZAcbioOb3NbMLI5YrlOAAFV2PWaKFQPR2JhgAE8wCY+NtUHwANasVDWVDiOCqJncqmeN4zBpwCCYaIMPgBYRxbpwGQDcDCEZjCbeFH0SJIOZ+SXShrYkLg0hEdAwPaoACOXE4c0hAgQABMxnsvJKoUkGDBWFjSEA)

---

```ts
import assert from 'assert'
import { asClass, asValue, createContainer } from 'awilix'

interface C {
  val: number
  calc: Calculator
}

class Calculator {
  result: number

  //          👇🏻 Constructor parameter is not compatible
  constructor(a: string) {
    this.result = a.length * 2
  }
}

const c = createContainer<C>()

c.register({
  val: asValue(2),
  // 👇🏻 This passes the type check, even when the constructor of Calculator is incompatible
  calc: asClass(Calculator),
})

assert.equal(c.cradle.calc.result, 2)
```

**Comment by jeffijoe** [comment]
This isn't possible. TypeScript does not provide a way to get _named_ parameters from functions, and even so, there is no way that I know of to build a function type dynamically based on the registrations.

**Comment by moltar** [comment]
Sorry for not being clear. I actually did _not_ want it to be a positional parameter. It _should be_ an object (i.e. cradle). My example was showing how it is _not_ an object. But I understand it was confusing and you thought I was trying to show the classic injection. But, no, I am still using a proxy injection.

**Comment by moltar** [comment]
Here's a better example:

[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAQwM5IKazgMyhEcDkyas+AUKJBgN6JIDCANkQDS0BqCDArqqwMZRUCGKjoQAdjATBx6OAF8sOPIQDuwBsAAeZcpPSYEfVHDpwqpOHABunAFxxxXEACN0luH058Hdb1yYYaFJ5Uj0RKENjU39A6AAFHDAkcw8EByQYKBkAcxCwviYUGIY+AOFoVKtBJACYBydXdw8AeharDs64QF4NwHEdwB4NwG-90wlMqC4+IKg4MAQoBBBUCLhgFPEIeD5cWZhgFwZUDy3xMYmpgAoaBAVfWIqoRIhkgEoqjpgAC1WAOhq6uAAvIhvgdxDlPnAAFRwABMHlCoVIx0ynkBnkEwlEEikMnQAB46AA+c7PAq-VA5VYRS4eWwMBzIDjcVDnGHPZitdp9IZwAAqXxSsxQqBSnxMMAAnmATHwPqg+ABrVioayocRwVRy9VizyjLJnSoQTAlMpxaarFbiLbgYR7A5HbwM+hFJDnPylcpTdkhUmkIjoGDfVAARy4nHOfG+AgQABMDlHvOTagwYKw2aQgA)

**Comment by jeffijoe** [comment]
I see, that makes sense, however I still don't think it's possible because `asClass` and friends need to work for both proxy injection as well as classic.
