### ISSUE TITLE
Whiteboard pattern

### ISSUE THREAD

**Issue by vincesp** [jeffijoe/awilix#329]
Hi Jeff,

What is the best way to implement the "Whiteboard Pattern" in awilix?

In its simplest form this means I can inject all dependencies that follow a certain name pattern, or that implement the same base class.

```js
module.exports = function(resolveByRegex) {
    const mimeTypeHandlers = resolveByRegex(/MimeType$/)
    console.log('The following mime type handlers have been registered:')
    const map = {}
    for (mimeTypeHandler of mimeTypeHandlers) {
        console.log(mimeTypeHandler.type)
        map[mimeTypeHandler.type] = mimeTypeHandler
    }

    function renderFile(mimeType, file) {
        map[mimeType].render(file)
    }
    
    return {
        renderFile
    }
}
```

How could `resolveByRegex()` and `resolveByInstanceOf()` work in awilix?

(Partly inspired by `spur-ioc`'s [`$injector.getRegex()`](/opentable/spur-ioc/blob/main/API.md#injectorgetregexregex-to-match-dependencies), see also OSGi's Whiteboard Pattern.)

**Comment by jeffijoe** [comment]
You can iterate `.registrations` to get the keys and check if they match your regex, then use `.resolve(key)`.

**Comment by vincesp** [comment]
How would I inject the container as dependency into the service?

**Comment by jeffijoe** [comment]
```js
container.register({
  resolveByRegex: {
    resolve: c => regex => console.log('container:', c)
  }
})
```

**Comment by vincesp** [comment]
`c` then is the cradle, not the container.

**Comment by jeffijoe** [comment]
No, `c` is the container.

**Comment by vincesp** [comment]
@vincesp wrote:

> `c` then is the cradle, not the container, and it only works in PROXY mode.

@jeffijoe wrote:

> No, `c` is the container.

Note the difference:

```js
container.register({
  resolveByRegex2: {
    resolve: c => console.log('resolve:', c, c === container)
  },
})
```

vs.

```js
module.exports = function (c) {
  console.log('module:', c)
}
```

Output:

```
resolve: [AwilixContainer (registrations: 7)] true
module: [object AwilixContainerCradle]
```

**Comment by jeffijoe** [comment]
The parameter passed to `resolve` is the container instance used; this can be the root container or a scoped container, so I recommend you use the one passed in.

The following would work and be preferred:

```ts
container.register({
  resolveByRegex: {
    resolve(c) {
      return function (regex) {
        const r = []
        for (const key of c.cradle) {
          if (key.match(regex)) {
            r.push(c.cradle[key])
          }
        }
        return r
      }
    }
  },
})
```
