### ISSUE TITLE
[Question] Support for assisted inject

### ISSUE THREAD

**Issue by piotrglebocki** [jeffijoe/awilix#330]
Does Awilix support a kind of assisted injection mechanism?  What I would basically need is a possibility for passing dynamic constructor parameters during `resolve`.

```
class DependencyA {}

class DependencyB {
    constructor(dependencyA: DependencyA, additionalParam: string) {
    // ...
}

container.register({
    dependencyA: asClass(DependencyA),
    dependencyB: asClass(DependencyB),
});

const depB = container.resolve('DependencyB') // need to pass dynamic additionalParam to constructor
```

To solve this problem I can basically implement a kind of proxy class e.g. DependencyBProvider which injects necessary dependencies inside and create an object with an additional parameter. But I am curious if Awilix provides a simpler solution for that.

**Comment by jeffijoe** [comment]
This use case is best solved with a factory (or as you called it, a provider).

You can create one pretty easily like so. This just uses a function:

```ts
// This is the signature for the provider.
type DependencyBProvider = (additionalParam: string) => DependencyB

const createDependencyB: DependencyBProvider = (dependencyA: DependencyA) => (
  (additionalParam) => new DependencyB(dependencyA)
)

// Register the provider.
container.register({ createDependencyB: asFunction(createDependencyB) })

// Use it
container.resolve('createDependencyB')('hello')
```

**Comment by piotrglebocki** [comment]
Thanks @jeffijoe
Already did something like this. Thanks for the confirmation. 
I am closing the ticket
