### ISSUE TITLE
Support for ESM modules

### ISSUE THREAD

**Issue by nedavniat** [jeffijoe/awilix#333]
I'm trying to migrate to esm modules and it turned out that awilix is not compatible throwing error:

` /usr/src/app/node_modules/awilix/lib/container.js:349
 |                     return require(uri);
 |                            ^
 | 
 | Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/src/app/dist/src/controllers/auth/controller.js from /usr/src/app/node_modules/awilix/lib/container.js not supported.
| Instead change the require of controller.js in /usr/src/app/node_modules/awilix/lib/container.js to a dynamic import() which is available in all CommonJS modules.
| at _loadModulesDeps.require (/usr/src/app/node_modules/awilix/lib/container.js:349:28)
| at /usr/src/app/node_modules/awilix/lib/load-modules.js:60:41
|     at Array.map (<anonymous>)
|     at loadModules (/usr/src/app/node_modules/awilix/lib/load-modules.js:59:32)`

using awilix 8.0.1
node 20
npm 9

**Comment by jeffijoe** [comment]
You need to use `esModules: true` + `await` for `loadModules` in order to use `import()` instead of `require()`.

```
await container.loadModules("./mods/*.mjs", {
  esModules: true,
});
```

**Comment by nedavniat** [comment]
Thank you! Would you mind me submitting MR for readme update. This is very useful tip!

**Comment by jeffijoe** [comment]
I linked to the `loadModules` documentation in the readme which explains this, but if you think it can be improved feel free to open a PR. 👍🏼️

<img width="955" alt="image" src="https://github.com/jeffijoe/awilix/assets/2505474/fd1753f0-578c-45dd-99fd-4c910843ef20">
