### ISSUE TITLE
Can't resolve

### ISSUE THREAD

**Issue by kapolos** [jeffijoe/awilix#335]
I am trying to use `asValue` and it seems I'm missing something. This code:

```
import { createContainer, asFunction, asValue } from 'awilix'

const defaultFooConfig = {
  value: 1
}

const fooService = (fooConfig) => {
  const _print = (ctx) => {
    return ctx.value  
  }
  
  return {
    print: () => _print(fooConfig)
  }
}


const container = createContainer()

container.register({
  fooConfig: asValue(defaultFooConfig),
  fooService: asFunction(fooService),
  // fooService: asFunction(() => fooService(defaultFooConfig))
})

// console.log(Object.keys(container.cradle.fooService))

const res = container.cradle.fooService.print()
console.log(res)
```

![image](https://github.com/jeffijoe/awilix/assets/10794126/e17d2e2c-a7ce-4df9-ab8c-93af186bdeca)

returns:

![image](https://github.com/jeffijoe/awilix/assets/10794126/805aaa54-3662-4386-9f84-d61d3bf8995a)

If I use `fooService: asFunction(() => fooService(defaultFooConfig))` instead, then it works as expected.

**Comment by jeffijoe** [comment]
You are writing your modules as if you are using classic injection, but the default for the container is proxy mode.

Change the injection mode to `CLASSIC`:

```js
import { createContainer, asFunction, asValue, InjectionMode } from 'awilix'

const container = createContainer({ injectionMode: InjectionMode.CLASSIC })
```

**Comment by kapolos** [comment]
@jeffijoe Thank you for looking into this. I would like to figure out how it works with PROXY mode, since it's the default.

Looking at this example that uses PROXY mode:
![image](https://github.com/jeffijoe/awilix/assets/10794126/7e29813f-1ce5-4c75-a8f8-fc0c0e88fba5)

I updated the code like this:
```
import { createContainer, asFunction, asValue } from 'awilix'

const defaultFooConfig = {
  value: 1
}

const fooService = ({ value }) => {
  const _print = (ctx) => {
    return ctx.value  
  }
  
  return {
    print: (value) => _print({ value })
  }
}

const container = createContainer()

container.register({
  fooConfig: asValue(defaultFooConfig),
  fooService: asFunction(fooService),
})

const res = container.cradle.fooService.print()
console.log(res)
```
![image](https://github.com/jeffijoe/awilix/assets/10794126/874949fa-0bf2-440e-9ccb-c08387a08116)

But it still gives me the same error:
![image](https://github.com/jeffijoe/awilix/assets/10794126/f259afeb-d8be-407b-a95d-5addc09560ee)

What am I doing wrong?

**Comment by kapolos** [comment]
It worked, thank you! 🍻
