### ISSUE TITLE
Calling `loadModules` does not register all the file paths

### ISSUE THREAD

**Issue by steliosrammos** [jeffijoe/awilix#347]
I attempt to register all the UseCase dependencies in the following way:

```js
try {
        container.loadModules([
            `${__dirname}/../../modules/**/application/useCases/**/*.js`,
            `${__dirname}/../../modules/**/application/useCases/*.js`,
        ], {
            resolverOptions: {
                injectionMode: InjectionMode.CLASSIC,
                lifetime: Lifetime.SINGLETON,
                register: asClass,
            },
            formatName: (filename) => `${filename}UseCase`,
        })
    } catch (err) {
        console.error('ERROR LOADING USE CASES', err);
}
```

It registers some use cases and not others. It also seems any new use case that is added does not get registered either. 

However, running the following code does list all the files: 

```js
fs.readdir(`${__dirname}/../../modules/funding/application/useCases`, (_, files) => {
      files.forEach(file => {
              console.log('FILE IN DIR', file);
      });
});
```

The code runs inside a docker container, which I have tried re-creating making sure it does not use a cached instance just in case the build is cached somehow. But all other changes are picked up so that seems unlikely.

I've hit a bit of a dead end and started manually registering the dependencies instead, but I'd love to get to the bottom of this!

**Awilix Version:** 8.0.1

**Comment by jeffijoe** [comment]
Awilix uses `fast-glob`, and it passes your globs directly + a `cwd` option. Make sure your paths are relative to the `process.cwd()`, or pass in your own `cwd` to `loadModules`.

**Comment by steliosrammos** [comment]
Passing the path relative to `process.cwd()` within the build directory worked, thank you!
