### ISSUE TITLE
Is it possible to detect / error on singletons dependent on transient or scoped registrations?

### ISSUE THREAD

**Issue by fnimick** [jeffijoe/awilix#348]
This is highlighted as a developer error in https://github.com/jeffijoe/awilix#scoped-lifetime - yet this is hard to detect if you accidentally introduce a singleton dependency on a non-singleton registration. Doubly so if you don't use inline resolver options, so that a singleton's dependencies are defined in a different place from its singleton-ness, which is yet another different place from where its dependencies' lifetimes are defined.

Is there ever a use case for this (a singleton preserving a reference to a transient registration outside its registration lifetime) or is this always a bug? If it's a bug, is there a way to detect this in DI at runtime so that it can be easily detected in development?

EDIT: actually, a similar issue occurs when a scoped lifetime registration depends on a transient. Should it always be an error if a component with a longer lifetime depends on a component with a shorter lifetime?

**Comment by jeffijoe** [comment]
In case others are interested in this, the discussion is moving to the [PR](https://github.com/jeffijoe/awilix/pull/349#pullrequestreview-1799548958).
