### ISSUE TITLE
Awilix 10 type exposure

### ISSUE THREAD

**Issue by radahh-rest** [jeffijoe/awilix#352]
Awilix 10 through #349 has reduced the export surface, including types. Our code base used the `Resolver<T>` type to propogate type checks into our abstraction layer.

Minimal example:
```
export type Dependencies = {
  [K: string]: Resolver<any>;
};

const container: Dependencies = {
  goodStringValue: asValue('test'),
  goodNumberValue: asValue(1),
  goodStringFunction: asFunction(() => 'test'),
  badRegistration: 'chicken',
};
```
causing `Type 'string' is not assignable to type 'Resolver<any>'.ts(2322)`

![image](https://github.com/jeffijoe/awilix/assets/101619066/a2578518-3013-45fc-84ce-47bed933f496)

Short-term we are cheating with 
```
import type { Resolver } from 'awilix/lib/resolvers.js';
```

Are we doing it 'wrong'? Is there an alternate type that's exported for us to use?

**Comment by jeffijoe** [comment]
Hey @radahh-rest, I released 10.0.1 (#351) which re-adds back a bunch of them. That was an oversight on my part when I reviewed the PR which trimmed them down, apologies.
