### ISSUE TITLE
[QUESTION] Userland async initializers

### ISSUE THREAD

**Issue by marvinroger** [jeffijoe/awilix#353]
Hi, thanks for this great DI library! It helped us a lot. 😄

I have a use-case where want some modules to be initialized asynchronously, e.g.:

```typescript
class DatabaseClient {
  async init() {
    // Connect to the DB
  }

  async runMigrations() {
    // Run migrations
  }
}

class App {
  constructor(private readonly databaseClient: DatabaseClient) {}

  async init() {
    await this.databaseClient.runMigrations()
  }
}

container.register({
  databaseClient: awilix.asClass(DatabaseClient),
  app: awilix.asClass(App)
})

// What I'd like:

const app = container.resolve('app')
await init(app) // would init `DatabaseClient`, then `App`
```

I'm aware with #311 that you consider this to be out of scope of Awilix, and I completely agree with you on the fact that Awilix should be as simple as possible. However, you commented this:

> I think this is something that is so simple to do in user-land code with .resolve that it probably doesn't warrant expanding the API surface

I'm curious how you would implement this in user-land code?

-----

I though of multiple options:

**Initializing through a defined priority**

This is the approach adopted by https://github.com/kibertoad/awilix-manager, but I'd like to leverage the natural order of the dependency graph without having to specify an `asyncInitPriority` integer.

**Init the dependencies manually in the `init` function**

For instance, here, `App` would `init` `databaseClient` in its own `init`. While this would work, this leaves room for human errors so I'd like a more automatic approach

**Access the dependency graph and traverse it**

Because Awilix is aware of the dependency graph, I could just traverse the graph starting from the leafs and `init` everything going up. However, AFAIK, Awilix does not expose the dependency graph, so I cannot do that.

-----

Is what I'm asking technically doable? If so, how would you achieve this user-land?
Thanks for your time, and feel free to close this issue if you don't have time for these kind of questions! 😉

**Comment by jeffijoe** [comment]
I think the [`awilix-manager`](https://github.com/kibertoad/awilix-manager) library does what you are looking for.

**Comment by marvinroger** [comment]
Well, not really, as I wrote in the issue, `awilix-manager` runs the `init` functions based on a `asyncInitPriority` integer, but I'd like to leverage the natural order of the dependency graph, e.g. initializing the leafs first, then the parents, etc.

That's precisely where I get stuck. Would it be possible to access the dependency graph?

**Comment by jeffijoe** [comment]
Apologies, I read the sample code and immediately thought it was the same kind of request. 😅 

The dependency graph is not known until resolution occurs, this is because not every resolver or injection mode is capable of knowing what the dependencies of a module are. Even so, the graph is not saved anywhere post-resolution.

I usually just resolve the modules I need to initialize and then call the proper method.

**Comment by marvinroger** [comment]
No worries!

I would say that Initializing the modules manually in the correct order is as cumbersome as manually instantiating the modules, which is the problem that Awilix solves. I get that you want to limit the scope of Awilix to the "instantiation" phase, and not the "initialization" phase. Still, I think that "initializing" the modules in the correct order is a valid use-case, and is not particularly an exotic need.

I might have found a solution to implement what I need in user-land, by creating a wrapper over `asFunction`, `asClass` and `asValue`:

```typescript
const asyncInit = Symbol('asyncInit')
const asyncDispose = Symbol('asyncDispose')

function createAwilixAsyncInitDisposeManager() {
  const resolvedSet: Set<unknown> = new Set()

  function buildResolve<T = object>(resolver: Resolver<T>) {
    return {
      resolve<U extends object>(container: AwilixContainer<U>) {
        const resolved = resolver.resolve(container)
        resolvedSet.add(resolved)
        return resolved
      },
    }
  }

  function asClass<T = object>(
    Type: Constructor<T>,
    opts?: BuildResolverOptions<T>,
  ): BuildResolver<T> & DisposableResolver<T> {
    const resolver = awilixAsClass(Type, opts)

    return {
      ...resolver,
      ...buildResolve(resolver),
    }
  }

  function asFunction<T>(
    fn: FunctionReturning<T>,
    opts?: BuildResolverOptions<T>,
  ): BuildResolver<T> & DisposableResolver<T> {
    const resolver = awilixAsFunction(fn, opts)

    return {
      ...resolver,
      ...buildResolve(resolver),
    }
  }

  function asValue<T>(value: T): Resolver<T> {
    const resolver = awilixAsValue(value)

    return {
      ...resolver,
      ...buildResolve(resolver),
    }
  }

  async function initAsync() {
    for (const resolved of resolvedSet) {
      if (resolved == null || (typeof resolved !== 'object' && typeof resolved !== 'function')) continue
      if (!(asyncInit in resolved)) continue
      if (typeof resolved[asyncInit] !== 'function') continue

      await resolved[asyncInit]()
    }
  }

  async function disposeAsync() {
    for (const resolved of Array.from(resolvedSet).reverse()) {
      if (resolved == null || (typeof resolved !== 'object' && typeof resolved !== 'function')) continue
      if (!(asyncDispose in resolved)) continue
      if (typeof resolved[asyncDispose] !== 'function') continue

      await resolved[asyncDispose]()
    }
  }

  return { asClass, asFunction, asValue, initAsync, disposeAsync }
}

// Usage

const { asClass, initAsync, disposeAsync } = createAwilixAsyncInitDisposeManager()
container.register({
  databaseClient: awilix.asClass(DatabaseClient),
  app: awilix.asClass(App)
})
const app = container.resolve('app')
await initAsync()
await disposeAsync()
```

When something is resolved, the resolved value ends up in `resolvedSet`. Therefore, we have a `resolvedSet` with all the resolved value ordered in the natural order, on which we can call anything we want (e.g. `initAsync`).

From inside the `resolve`, I only have access to the resolved value. However, it would be great to have access to the original token and maybe the lifetime.

Therefore, I would suggest adding the following feature:

* Add an `onPostResolve({ token, value, lifetime })` hook to the `createContainer`'s`options`
* This hook would be called right after something is `resolve`'d

I think this would be trivial to do in terms of added code and maintenance burden, and it would unlock "advanced" use-cases like being able to generate a dependency graph or allow async init without having to wrap `asClass`, `asFunction` or `asValue`.

What do you think about this?

**Comment by marvinroger** [comment]
I did not think about the `Host` approach, thanks a lot for this!

Indeed it's more explicit, solves my use-case, and does it in a better way. Thanks again for your library and for your time, I appreciate it.

**Comment by jeffijoe** [comment]
Happy to help, and glad I was able to provide a solution. 😄

**Comment by KazimirPodolski** [comment]
Awilix lacking this built-in only leads to every user re-inventing their own flavour of a module init. Plus this is super idiomatic in DI in general.

And then there is `disposer` which is essentially the same just on the other end...
