### ISSUE TITLE
replace camel-case dependency

### ISSUE THREAD

**Issue by u873838** [jeffijoe/awilix#354]
From [npmjs.org](https://www.npmjs.com/package/camel-case):

> This package has been deprecated
>
> Author message:  
> `` Use `change-case` ``

**Comment by jeffijoe** [comment]
I had tried doing this earlier while doing another change but I ran into some problems so I dropped it for the time being. Feel free to take a stab at it.

**Comment by fnimick** [comment]
It's not possible without dropping CommonJS support for awilix. `change-case` as of v5.x is ESM only. Using the previous CommonJS compatible version v3.x has the exact same camelcase code and is similarly deprecated, except we'd be pulling in all other case transformation utilities as well for no reason.

**Comment by jeffijoe** [comment]
Thanks for your input @fnimick, I didn't know it was the exact same implementation. It would be nice if we could copy it over instead and fully own it to avoid this issue. I'll close this for now though as there are no open CVEs for this.
