### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by AlphaRomeoMike** [jeffijoe/awilix#357]
Is there a way to add types to Awilix resolved values? If yes, please lemme know so I can create a PR for this. I think the only thing that Awilix is missing is the types like TypeDI and others.

**Comment by jeffijoe** [comment]
You can pass a type to `createContainer` which describes your services.

```
interface Services {
  example: number
}

const container = createContainer<Services>()
container.register({ example: asValue(123) }) // type checked
container.resolve('example') // returns `number` type
```

**Comment by BCsabaEngine** [comment]
I really like the solution provided by lib. I also missed this type description in the whole thing. It also works fine with asValue and asFunction elements.

```
type Container = {
//system services
	logService: ReturnType<typeof LogService>,
	configService: ReturnType<typeof ConfigService>,
	databaseService: ReturnType<typeof DatabaseService>,

//business services
	productService: ReturnType<typeof ProductService>,

//scope variables
	traceId: string
	userId: number | undefined
}
```
