### ISSUE TITLE
[QUESTION] - Awilix Fails to Autoload Modules in Vitest Tests with TypeScript Setup

### ISSUE THREAD

**Issue by eskylake** [jeffijoe/awilix#359]
Hi, Tnx Awilix.

I know that this may not be an issue and its better to be asked in any stackoverflow-like media.
I already [asked one](https://stackoverflow.com/questions/78333437/awilix-fails-to-autoload-modules-in-vitest-tests-with-typescript-setup).

I am using:

```json
"typescript": "^5"
"vitest": "^1"
"awilix": "^8"
```

[loadModules()](https://github.com/jeffijoe/awilix?tab=readme-ov-file#auto-loading-modules) doesn't load modules while creating container through my tests.
Due to my research & other issues which I read here, I couldn't find any proper solution to the problem.
I don't wanna use `type: module` in `package.json` & I can't load `.ts` files directly into the container.

This won't work:

```typescript
  container.loadModules(
    [
      `${resolve(__dirname, '../Connection/*.ts')}`,
      `${resolve(__dirname, '../Connection/**/*.ts')}`,
    ],
    {
      resolverOptions: {
        lifetime: Lifetime.SINGLETON,
        register: asClass,
      },
    },
  );
```
I could fix it by including my `test` directory in both `tsconfig.json` and `vitest.config` files. But I'm not sure if this is correct.
Would you plz help me with this issue? Thanks in advance

**Comment by jeffijoe** [comment]
Awilix uses fast-glob to locate files. If this works outside vitest then I would suggest opening an issue there. I don’t use vitest so I’m not sure what it could be.
