### ISSUE TITLE
Inject dependency in koa route file

### ISSUE THREAD

**Issue by ddellamico** [jeffijoe/awilix#36]
First of all congratulations for this module, really simple and powerful!
Maybe a stupid question but, how can I inject dependencies into my koa route files?
For example, I would like to inject my controller in my route, like this :

```
import Router from 'koa-router';
const productsRoute = ({ productController }) => {
  const router = new Router({
    prefix: '/products',
  });
  router.get('/', productController.getProducts());
  return router;
};
```
It's possibile with **makeInvoker** from awilix-koa package ?
I'm using koa 2.3.0 and koa-router 7.2.1.

Many thanks,

Damien

**Comment by jeffijoe** [comment]
Thanks for the kind words!

Check out the [Usage section](https://github.com/jeffijoe/awilix-koa#usage) in `awilix-koa`. Basically, you want your route handler to resolve the controller for each request, that's how you can use "per request state".

Example:

```
import Router from 'koa-router'
import { makeClassInvoker } from 'awilix-koa'

class ProductController {
  constructor ({ productService }) {
    this.service = productService
  }

  async getProducts (ctx) {
    ctx.body = await this.service.getProducts()
  }
}

// Uses ´makeClassInvoker`, whenever the route gets hit, a new `ProductController` is created.
export default function createRouter () {
  const controller = makeClassInvoker(ProductController)
  const router = new Router()
  router.get('/products', controller('getProducts'))
  return router
}
```

Does this answer your question?

**Comment by ddellamico** [comment]
Thanks for the quick reply!
Your example is very clear and it's exactly how I did.
My question is: it's possible in some way to inject the controller or another service in "_createRouter_" function? Also, I would like to inject a middleware function in order to check authentication. Is it possible?

Regards,

Damien

**Comment by jeffijoe** [comment]
Sure you can, you can just pass it `container.cradle`, **but** if you do that you will get a single instance of anything you resolve for the entire process which is _probably_ not what you want.

To use dependencies in your middleware, you can access the container on the context using `ctx.state.container` and resolve your dependencies that way.

Example:

```js
function authenticate (ctx, next) {
  const userService = ctx.state.container.resolve('userService')
  // alternatively...
  const { userService } = ctx.state.container.cradle
  
  // use it...
  return next()
}

// somewhere else...
export default function createRouter () {
  const controller = makeClassInvoker(ProductController)
  const router = new Router()
  router.get('/products', authenticate, controller('getProducts'))
  return router
}
```

This way, the lifetime management works as you'd expect. 😄

**Comment by ddellamico** [comment]
Thanks, @jeffijoe !
Now I use makeInvoker to inject the middleware as you suggested.

Regards,

Damien

**Comment by jeffijoe** [comment]
Happy to help, and thanks for using Awilix! 😄
