### ISSUE TITLE
Support `loadModules` for apps running in the Browser (with Vite)

### ISSUE THREAD

**Issue by MathiasWP** [jeffijoe/awilix#363]
Awilix works great for enterprise applications running in the browser; but it's missing an API for automatically loading modules.

[Vite has an API for loading files which works in the browser](https://vitejs.dev/guide/features#glob-import). We're currently using this to implement our own version of `loadModules`, but it would be great to have first-class support for this through Awilix. 

Is this something to consider?

**Comment by jeffijoe** [comment]
Doesn’t Vite have to statically analyze the use of that method? If so then I don’t think it would work since Vite wouldn’t know to also look for that pattern. Also, wouldn’t doing this hurt code splitting? I have a feeling it comes at a cost.

I would be open to doing this though, as long as it can be agnostic to the use of Vite. Or, why not publish your solution as a library? There’s nothing special about the built-in Node version.

**Comment by MathiasWP** [comment]
Vite will transform 
```ts
const modules = import.meta.glob('./dir/*.js', { eager: true })
``` 
into
```ts
// code produced by vite
import * as __glob__0_0 from './dir/foo.js'
import * as __glob__0_1 from './dir/bar.js'
const modules = {
  './dir/foo.js': __glob__0_0,
  './dir/bar.js': __glob__0_1,
}
```
so it's quite easy to achieve the wanted behaviour from the transformed code. I'm currently doing this in our application and it works fine.

Because of the transformation I don't think it will hurt code-splitting, since the output is the same as if the code was written by hand.

Not sure how making the code agnostic to the use of Vite can be achieved. There's a lot of different build tools in the ecosystem, so the library would have to decide what tools to support anyways. And i'm not really sure if any other build tools support this atm. The solution could be available as a library, but i think it would be better for the community if it was available through Awilix. 
What about exposing it through a Vite specific import?

```ts
import { loadModules } from "awilix/vite"
```

And you're right that Vite has to statistically analyse the usage of `import.meta.glob`, so wrapping it in a method will not work as expected (see https://github.com/vitejs/vite/issues/15926). To solve this Awilix could either expose a vite-plugin to transform the code, or it could export a method that expects the result of `import.meta.glob` and transforms the object into the expected structure for Awilix:

```ts
import { registerModules } from "awilix/vite"

// Support non-eager glob
registerModules(import.meta.glob(["/glob/to/files/*.ts"])

// And also eager glob
registerModules(import.meta.glob(["/glob/to/files/*.ts"], { eager: true })
```

**Comment by jeffijoe** [comment]
In that case I think having that be a separate package makes sense, like:

```js
import { loadModules } from "awilix-vite”
```

We have the ecosystem section in the readme that we can add it to if you do decide to publish a package.

**Comment by MathiasWP** [comment]
> In that case I think having that be a separate package makes sense, like:
> 
> ```js
> import { loadModules } from "awilix-vite”
> ```
> 
> We have the ecosystem section in the readme that we can add it to if you do decide to publish a package.

Alright, that's fair! Where do you want me to notify you if i create this package?

**Comment by jeffijoe** [comment]
You can open a PR here adding a link in the ecosystem section 😄

**Comment by MathiasWP** [comment]
What do you think about this implementation? Any feedback?

https://github.com/kvist-no/awilix-vite

**Comment by MathiasWP** [comment]
> Looks good to me! Maybe document the use of promises and how lazy vs eager loading affects behavior.

Done, what do you think?

**Comment by jeffijoe** [comment]
I see, so in that case I would recommend not allowing lazy loading since it will effectively load them right away. Other than that looks good to me, nice work. Feel free to open a PR here adding it to the ecosystem list.

**Comment by MathiasWP** [comment]
> I see, so in that case I would recommend not allowing lazy loading since it will effectively load them right away. Other than that looks good to me, nice work. Feel free to open a PR here adding it to the ecosystem list.

Is it necessary to force users to set `eager: true` in the `import.meta.glob` method? There could be use cases where people actually want to load the modules lazily (e.g. a bit later in a session), but i would expect that in most use cases people want all modules loaded instantly.

**Comment by jeffijoe** [comment]
If you call `loadModules` immediately following the `import.meta.glob` method, then as you said in the documentation, it won't actually do anything different since `loadModules` will invoke the lazy methods immediately.

**Comment by MathiasWP** [comment]
> If you call `loadModules` immediately following the `import.meta.glob` method, then as you said in the documentation, it won't actually do anything different since `loadModules` will invoke the lazy methods immediately.

So is it better to throw an error telling the user to set eager to true?

**Comment by jeffijoe** [comment]
In my opinion, yes, since it forces the consumer to use it correctly, and reduces the API surface which IMO is a good thing.

**Comment by MathiasWP** [comment]
Created PR https://github.com/jeffijoe/awilix/pull/364
