### ISSUE TITLE
pass extra constructor argument in use asClass

### ISSUE THREAD

**Issue by wind4gis** [jeffijoe/awilix#365]
I have a store class which has a, b two args, a is register in awillx, but b will be injected in my business code. is there any thing like factory? or i should asFunction?

**Comment by jeffijoe** [comment]
This is a good use case for a factory.

**Comment by wind4gis** [comment]
ok...there is no asFactory, just use asFunction? thx

**Comment by jeffijoe** [comment]
Yes, use `asFunction`. 👍
