### ISSUE TITLE
New awilix version required including new version of fast-glob (due to vulnerability in micromatch)

### ISSUE THREAD

**Issue by MichelKor** [jeffijoe/awilix#366]
Dependency micromatch is vulnerable to Regular Expression Denial of Service (ReDoS). https://github.com/advisories/GHSA-952p-6rrq-rcjv (Not available yet)

The above dependency is included in the dependency fast-glob: https://github.com/mrmlnc/fast-glob/issues/454 (Not available yet)

**Comment by jeffijoe** [comment]
Happy to update the package when the fix is available, however, since usage of `fast-glob` is used in `listModules` (which is typically never an end-user-specified value), I'm not too concerned here.

**Comment by hauserkristof** [comment]
I have opened a PR https://github.com/micromatch/micromatch/pull/266 that fixes the issue in micromatch (https://github.com/micromatch/micromatch/issues/264), wating to be merged.

**Comment by MichelKor** [comment]
Fixed in fast-glob: https://github.com/mrmlnc/fast-glob/issues/454

**Comment by jeffijoe** [comment]
Does that mean no package update is necessary?

**Comment by MichelKor** [comment]
Yes, correct

**Comment by jeffijoe** [comment]
I'll be publishing a patch release soon anyway with updated dependencies just in case.
