### ISSUE TITLE
Cloudflare build fails due to Node APIs

### ISSUE THREAD

**Issue by QuentinDutot** [jeffijoe/awilix#368]
Importing only `createContainer` from awilix causes the build to crash.

It seems that `listModules` (which relies on `fast-glob`) is being implicitly included, **even when not used** which is a problem as Cloudflare Pages and Workers have limited support for Node.js APIs (with `nodejs_compat`).

---

Workaround : import from the browser build and manually assign the types
```js
import type { asFunction as asFunctionTyped, createContainer as createContainerTyped } from 'awilix'

// @ts-expect-error
import { asFunction as _asFunction, createContainer as _createContainer } from 'awilix/lib/awilix.browser.js'

const asFunction: typeof asFunctionTyped = _asFunction
const createContainer: typeof createContainerTyped = _createContainer
```

**Comment by jeffijoe** [comment]
Never used CF so I’m not familiar with their limitations. What do you suggest? Also, are you using esm?

**Comment by QuentinDutot** [comment]
Yes esm only, after some digging :

- `listModules` being exported from awilix is not the problem (it gets treeshaked)
- `listModules` being used in `container.loadModules` is the problem (it gets bundled)

**Comment by QuentinDutot** [comment]
Some ideas :

**1. "browser" is an "agnostic" export**
Same as now it uses no runtime specific features but it needs some changes: 
- `package.json` should have exports to easily use the agnostic version
- configure rollup to have the types built for this export too

**2. do not automatically load the modules**
`loadModules` should accept an array of modules that :
- could be loaded via listModules exposed in awilix
- could also be loaded via import.meta.glob in vite env
- could also be loaded via other ways in other envs (bun, deno, ...)

**Comment by jeffijoe** [comment]
For option 1, what would need to be added to `package.json`? Wrt types, if the package export is set up, wouldn't the types be loaded correctly?

Option 2 would be changing an API that has been stable for many years which I'm not too fond of, but it could be done - do you know if moving `loadModules` to a top-level function that accepts the container as the first parameter would work with CF as long as you don't explicitly import `loadModules`?

There's already [`awilix-vite`](https://www.npmjs.com/package/awilix-vite) which supplies a `loadModules` that is compatible with `import.meta.glob` for Vite.

**Comment by QuentinDutot** [comment]
**Option 1** I was thinking about this kind of `exports` in `package.json` :

```json
"exports": {
  ".": {
    "import": "./lib/awilix.js",
    "types": "./lib/awilix.d.ts"
  },
  "./browser": {
    "import": "./lib/awilix.browser.js",
    "types": "./lib/awilix.d.ts"
  }
},
```
```js
import { asFunction, createContainer } from 'awilix/browser'
```

**Option 2** Yes moving `loadModules` to a top-level function should work. Same as `listModules`, if not used it would get treeshaked.
Sounds like the best option as it would benefit not only CF env but also all non-Node envs

**Comment by jeffijoe** [comment]
It seems like Option 1 is backwards-compatible and solves the immediate problem, so I think we should go for that for the time being.

**Comment by ccremer** [comment]
Hi.
For me, it still doesn't work in Cloudflare Pages.
```console
20:30:26.159 | import { createContainer, asClass, asValue } from "awilix/browser";
-- | --
20:30:26.159 |                           ^^^^^^^
20:30:26.159 | SyntaxError: Named export 'asClass' not found. The requested module 'awilix/browser' is a CommonJS module, which may not support all module.exports as named exports.
20:30:26.159 | CommonJS modules can always be imported via the default export, for example using:
20:30:26.160 |  
20:30:26.160 | import pkg from 'awilix/browser';
20:30:26.160 | const { createContainer, asClass, asValue } = pkg;
```
I tried the suggestions from the above log, but that didn't fix it either.

**Comment by jeffijoe** [comment]
@ccremer is it possible that CF doesn’t like that its a .js rather than a .mjs? Like I said, I have no experience with CF so I’m gonna need some assistance from someone who does.

**Comment by ccremer** [comment]
I don't know either, I'm just using SvelteKit's adapter for Cloudflare builds.
Hm, it's not going to be easy. It's a classic "works on my machine" aka `npm run build` with adapter-cloudflare succeeds locally, but not in CF... I don't know if I can replicate CF's environment, anything else would be just trial-and-error.

**Comment by ccremer** [comment]
Without `awilix` (no browser) I get these build errors locally with adapter-cloudflare:
```
> Using @sveltejs/adapter-cloudflare
✘ [ERROR] Could not resolve "fs"

    node_modules/@nodelib/fs.scandir/out/adapters/fs.js:4:19:
      4 │ const fs = require("fs");
        │                    ~~~~
        ╵                    "./fs"

  Cannot use "fs" when deploying to Cloudflare.


✘ [ERROR] Could not resolve "fs"

    node_modules/@nodelib/fs.stat/out/adapters/fs.js:4:19:
      4 │ const fs = require("fs");
        │                    ~~~~
        ╵                    "./fs"

  Cannot use "fs" when deploying to Cloudflare.


✘ [ERROR] Could not resolve "url"

    node_modules/awilix/lib/awilix.module.mjs:6:30:
      6 │ import { pathToFileURL } from 'url';
        ╵                               ~~~~~

  Cannot use "url" when deploying to Cloudflare.


✘ [ERROR] Could not resolve "os"

    node_modules/fast-glob/node_modules/glob-parent/index.js:5:22:
      5 │ var isWin32 = require('os').platform() === 'win32';
        ╵                       ~~~~

  Cannot use "os" when deploying to Cloudflare.


✘ [ERROR] Could not resolve "fs"

    node_modules/fast-glob/out/settings.js:4:19:
      4 │ const fs = require("fs");
        ╵                    ~~~~

  Cannot use "fs" when deploying to Cloudflare.


✘ [ERROR] Could not resolve "os"

    node_modules/fast-glob/out/settings.js:5:19:
      5 │ const os = require("os");
        ╵                    ~~~~

  Cannot use "os" when deploying to Cloudflare.


✘ [ERROR] Could not resolve "os"

    node_modules/fast-glob/out/utils/path.js:4:19:
      4 │ const os = require("os");
        ╵                    ~~~~

  Cannot use "os" when deploying to Cloudflare.


error during build:
Error: Bundling with esbuild failed with 7 errors
```

**Comment by jeffijoe** [comment]
Yeah the default export references fast-glob and fs which are not supported in the browser, so thats expected

**Comment by ccremer** [comment]
Yeah, I'm just logging my debugging progress :)

So here's my build log with the suggestion from CF like
```ts
import awilix from 'awilix/browser';
const { asValue } = awilix;
...
```
(node:1066957) [MODULE_TYPELESS_PACKAGE_JSON] Warning: file://node_modules/awilix/lib/awilix.browser.js parsed as an ES module because module syntax was detected; to avoid the performance penalty of syntax detection, add "type": "module" to node_modules/awilix/package.json
(Use `node --trace-warnings ...` to show where the warning was created)

node_modules/wrangler/wrangler-dist/cli.js:29768
            throw a;
            ^
file://.svelte-kit/output/server/chunks/hooks.server.js:15
import awilix from "awilix/browser";
       ^^^^^^
SyntaxError: The requested module 'awilix/browser' does not provide an export named 'default'
```
There seems to be no default export. I'm going to try playing around with awilix' package.json

**Comment by jeffijoe** [comment]
What's your build tooling? Vite?

**Comment by ccremer** [comment]
Yes, basically `vite build`.

When I manually patch `export { AwilixError... }` in line 1360 in /node_modules/lib/awilix.browser.js to `export default {...}`, then the build works locally and both error and warning go away. Haven't managed to get it testing in CF yet.

**Comment by jeffijoe** [comment]
It's weird because [others have used Awilix with Vite before](https://github.com/jeffijoe/awilix/pull/364). 🤔 

If it works locally, then it does seem like it's the CF runtime that isn't resolving the correct export.

**Comment by ccremer** [comment]
yeah, it's weird. locally it works with vite even without default export, but not in CF...

**Comment by ccremer** [comment]
Ok, So I've found a workaround:
1. Patch `node_modules/awilix/lib/awilix.browser.js` so it has `export default`, e.g.
```
tmp_file=$(mktemp)
awk '{
    if ($1 == "export" && $2 == "{") {
        $1 = "export default";
        print;
    } else {
        print;
    }
}' node_modules/awilix/lib/awilix.browser.js > "$tmp_file"
mv "$tmp_file" node_modules/awilix/lib/awilix.browser.js
```
2. Patch package.json with "type":"module":
In my package.json:
```json
...
"scripts":
    "prebuild": "npx esrun patchAwilix.ts",
```
patchAwilix.ts:
```ts
import fs from 'node:fs';

function addTypeToPackageJson(filePath: string) {
  try {
    const packageJsonData = JSON.parse(fs.readFileSync(filePath, 'utf-8'));

    if (!packageJsonData.type) {
      packageJsonData.type = 'module';
      fs.writeFileSync(filePath, JSON.stringify(packageJsonData, null, 2));
      console.log(`Successfully added "type": "module" to ${filePath}`);
    } else {
      console.log(`"type" field already exists in ${filePath}`);
    }
  } catch (error) {
    console.error(`Error reading or writing ${filePath}:`, error);
  }
}

addTypeToPackageJson('node_modules/awilix/package.json');
```

**Comment by ccremer** [comment]
@jeffijoe what would it mean to add "type":"module" to your package, as well as adding the default export?
I'm not too familiar with node packaging shenanigans, I find this way too complicated :D

**Comment by jeffijoe** [comment]
I'm worried that `type: module` might break something 😅 

The `export default` should not be necessary at all, though. It should be perfectly fine for a module to only use named exports.

**Comment by jeffijoe** [comment]
What if you copy `awilix.browser.js` to `awilix.browser.mjs` and then update the export to point to that? 🤔

**Comment by ccremer** [comment]
> The export default should not be necessary at all, though. It should be perfectly fine for a module to only use named exports.

> What if you copy awilix.browser.js to awilix.browser.mjs and then update the export to point to that? 🤔

This fails with `SyntaxError: The requested module 'awilix/browser' does not provide an export named 'default'`, even locally. My guess is that it's still treated as commonjs

**Comment by jeffijoe** [comment]
What if you [add a `workerd` key](https://developers.cloudflare.com/workers/wrangler/bundling/#conditional-exports)?

**Comment by ccremer** [comment]
I edited my previous comment, I managed to get it building :tada:

**Comment by jeffijoe** [comment]
Does it still work even if you make the `default` use `.js`? And what about just adding the `workerd` key? If the `workerd` key works then that's the simplest solution!

**Comment by ccremer** [comment]
```json
 ".": {
   ....
   "workerd": "./lib/awilix.browser.js"
 }
```
fails in CF with
```console
23:14:14.016 | error during build:
-- | --
23:14:14.016 | [vite]: Rollup failed to resolve import "awilix/browser" from "/opt/buildhome/repo/src/hooks.server.ts".
```

```json
 ".": {
   ....
   "import": "./lib/awilix.browser.js",
   "default": "./lib/awilix.browser.js",
   "workerd": "./lib/awilix.browser.mjs"
 }
```
also fails with `Named export not found`, even if I have both .js and .mjs files.

**Comment by jeffijoe** [comment]
![image](https://github.com/user-attachments/assets/1eabc52d-5784-4ed6-b31e-925fe6cba661)

**Comment by jeffijoe** [comment]
Wait, `Rollup failed to resolve import "awilix/browser"` - did you use `import { ..} from 'awilix'` or `'awilix/browser'`? It should be the former since the key was added to the root export

**Comment by ccremer** [comment]
Ah wait, let me be more precise:
I always used `awilix/browser` for testing, otherwise CF fails with unsupported node APIs.
So my testing was done with
```ts
'./browser': {
        import: './lib/awilix.browser.js',
        types: './lib/awilix.d.ts',
        default: './lib/awilix.browser.js',
        workerd: './lib/awilix.browser.mjs',
      },
```
, not the root export.

**Comment by jeffijoe** [comment]
Gotcha, my hypothesis was that simply adding `"worked": "./lib/awilix.browser.js"` to `"."` should have been sufficient, as it tells CF to load the browser build even when importing the root.

**Comment by ccremer** [comment]
I thought as much :+1: 
Different error now (local build):
```ts
      '.': {
        import: './lib/awilix.module.mjs',
        types: './lib/awilix.d.ts',
        default: './lib/awilix.js',
        workerd: './lib/awilix.browser.js',
      },
```
results in
```
file://node_modules/awilix/lib/awilix.module.mjs:4
import { importModule } from './load-module-native.js';
         ^^^^^^^^^^^^
SyntaxError: The requested module './load-module-native.js' does not provide an export named 'importModule'
```
And in CF it fails with the other Node import errors (e.g. `✘ [ERROR] Could not resolve "fs"`)

**Comment by jeffijoe** [comment]
Yeah so there its loading `awilix.module.mjs` which does include `fs` and `fast-glob`, it also includes an `import()`-compatible `loadModules` implementation which is what it's complaining about there, so I think we should definitely aim to use the browser build.

**Comment by ccremer** [comment]
> It appears CF isn't respecting the workerd key?

Seems like it, or I'm not using the environment/technology where they do.

I tried a different approach: To re-export everything from `.js` in a `.mjs`, e.g.
```ts
import * as awilix from 'awilix/browser';

const {
  AwilixError,
  AwilixRegistrationError,
  AwilixResolutionError,
  AwilixTypeError,
  InjectionMode,
  Lifetime,
  RESOLVER,
  aliasTo,
  asClass,
  asFunction,
  asValue,
  createBuildResolver,
  createContainer,
  createDisposableResolver,
  isClass,
  isFunction,
} = awilix;

export {
  AwilixError,
  AwilixRegistrationError,
  AwilixResolutionError,
  AwilixTypeError,
  InjectionMode,
  Lifetime,
  RESOLVER,
  aliasTo,
  asClass,
  asFunction,
  asValue,
  createBuildResolver,
  createContainer,
  createDisposableResolver,
  isClass,
  isFunction,
};
```
and 
```ts
      '.': {
        import: './lib/awilix.module.mjs',
        types: './lib/awilix.d.ts',
        default: './lib/awilix.js',
      },
      './browser': {
        import: './lib/awilix.browser.js',
        types: './lib/awilix.d.ts',
        default: './lib/awilix.browser.js',
      },
      './workerd': {
        import: './lib/awilix.browser.mjs',
        types: './lib/awilix.d.ts',
        default: './lib/awilix.browser.mjs',
      },
```
with imports like `import { asClass, asValue, createContainer, type AwilixContainer } from 'awilix/workerd';`,
but that fails too in CF (unless I'm doing something wrong, which is highly likely.
```console
14:59:41.302 | /opt/buildhome/repo/node_modules/awilix/lib/awilix.browser.js:1360
-- | --
14:59:41.302 | export { AwilixError, AwilixRegistrationError, AwilixResolutionError, AwilixTypeError, InjectionMode, Lifetime, RESOLVER, aliasTo, asClass, asFunction, asValue, createBuildResolver, createContainer, createDisposableResolver, isClass, isFunction };
14:59:41.303 | ^^^^^^
14:59:41.303 | SyntaxError: Unexpected token 'export'
```

So far, the only thing that really worked, is to actually have a `awilix.browser.mjs` being a copy of `awilix.browser.js`, so it really boils down to the file extension.
Is it really impossible to build awilix with the .mjs extension?

**Comment by jeffijoe** [comment]
Its definitely possible, but have duplicate files bloats the package size. I suppose renaming it would be the best option, I was just hoping adding the proper key would be sufficient.

![image](https://github.com/user-attachments/assets/f7d933f8-aa17-466b-9771-417956b823db)

**Comment by ccremer** [comment]
I can totally understand you :D

However, I come with new insight, which should relieve you of our pain :D

It's node v20 that doesn't work. Node v22 works.
It' that simple -.-

There's no need to add a workerd key, or renaming to .mjs.
I was just running node v22 locally, but had v20 in .npmrc and that's the version CF used to build it.
Upgrading to v22 resolved it and magically everything was able to build from `awilix/browser` :tada: 
This explains why building locally worked with a solution but not on CF. So there seems to be significant enough change between v20 and v22 that allows this import now.

**Comment by ccremer** [comment]
So for now, you don't need to do anything, except maybe point out in the Readme that node v22 may help resolve some import problems :)

I apologize for wasting your time with my inability to check if versions match, but I'm glad I could figure that out before doing something unnecessary.

**Comment by ccremer** [comment]
@DDuran19 I've added a `.nvmrc` file containing `v22.8.0`, and CF build shows this:
```console
16:07:30.156 | Success: Dependencies restored from build cache.
-- | --
16:07:30.257 | Detected the following tools from environment: nodejs@22.8.0, npm@9.6.7
16:07:30.258 | Installing nodejs 22.8.0
16:07:31.122 | Trying to update node-build... ok
```
So it uses node v22 in my case.

**Comment by DDuran19** [comment]
oh okay, I am unfamiliar with what a .nvmrc is. I encountered problems with newer versions of node and I didn't know that there's a fix like that lol

**Comment by DDuran19** [comment]
so, does that mean that we are unable to use this unless we update to node v22?

**Comment by ccremer** [comment]
`.nvmrc` is from [node-version-manager](https://github.com/nvm-sh/nvm), kind of like `venv` for Python

> so, does that mean that we are unable to use this unless we update to node v22?

Yes, unless Awilix fully goes the Module way and drops CommonJS (AFAIK)

**Comment by jeffijoe** [comment]
That should not be necessary, its what the exports section in package.json is supposed to solve.

@ccremer if we rename the browser file from js to mjs, is that all thats needed to make it work?

**Comment by ccremer** [comment]
Yes, and also rename accordingly in the `exports` section:
```ts
      '.': {
        import: './lib/awilix.module.mjs',
        types: './lib/awilix.d.ts',
        default: './lib/awilix.js',
      },
      './browser': {
        import: './lib/awilix.browser.mjs',
        types: './lib/awilix.d.ts',
        default: './lib/awilix.browser.mjs',
      },
      './lib/*.js': {
        types: './lib/*.d.ts',
        default: './lib/*.js',
      },
      './lib/*': {
        default: './lib/*.js',
      },
```
And even with node v20, there was no warning about adding type:module to package.json either. So that should :tm: work.

**Comment by jeffijoe** [comment]
Fellas, please try `awilix@12.0.2-alpha.0`

**Comment by MathiasWP** [comment]
> Fellas, please try `awilix@12.0.2-alpha.0`

that did the trick!

**Comment by MathiasWP** [comment]
yep, since awilix is a commonjs project this was all i needed for it to work in esm projects 👍

**Comment by DDuran19** [comment]
Thanks for the update! I tried it, it doesn't work on build it still uses fast-glob
here's my import statement `import { createContainer, asFunction, asClass } from 'awilix/browser`

`import Awilix from 'awilix/browser'` doesn't work, it says it doesnt have default export `The requested module 'awilix/browser' does not provide an export named 'default'`

![image](https://github.com/user-attachments/assets/5051b178-fb9b-4d20-8ea5-6f67439a9e79)

**Comment by jeffijoe** [comment]
@DDuran19 that shouldn't be possible, `awilix/browser` only has entries that point to browser builds, both of which I manually verified to not contain any dependencies.

**Comment by DDuran19** [comment]
Sorry! Im not sure what's happening. It works good on dev (cause it is still running on NodeJS) but when  built, it  somehow still imports  the Node modules... 


I don't know if this helps but I think Cloudflare got around with this limitation through dynamic imports.. They have this wrangler package that has a function called getPlatformProxy which when called, uses Node - specific modules to "mimic" a cloudflare platform. ( when you don't dynamically import this function, it results to build error similar to the one above)

**Comment by DDuran19** [comment]
![image](https://github.com/user-attachments/assets/008771ce-5d97-4d99-b7f3-ebf053e53144)
![image](https://github.com/user-attachments/assets/92e9a25a-4fcc-4a6a-9778-fd812453df3c)

it builds through vite, but then after using the cloudflare adapter, it returns an error
![image](https://github.com/user-attachments/assets/bb72702a-3c3e-48ff-b44d-7c8f6e803b30)
![image](https://github.com/user-attachments/assets/842616d5-24c5-4df4-b4c4-7bb7b0c34b63)

**Comment by jeffijoe** [comment]
I dont see how it's possible to load `awilix.module.mjs` when you're importing `awilix/browser`

<img width="465" alt="image" src="https://github.com/user-attachments/assets/e55dbff5-1e15-4c6f-bf53-11a3494c7775">

Just double-checking, this is the correct usage:

```js
import { createContainer } from 'awilix/browser'
```

**Comment by ccremer** [comment]
Hi
I can confirm that on CF the build just works:
* node v20
* no warnings or errors
* Using `awilix/browser`
* awilix@12.0.2-alpha.0

:tada:

**Comment by jeffijoe** [comment]
@ccremer what if you use just `import { ... } from 'awilix'`? I've modified the root export as well to include a `browser` and `workerd` conditional, I wonder if that "just works" 😅 

If not, then at least `awilix/browser` works 👍

**Comment by ccremer** [comment]
Nope, `import { ... } from 'awilix'` doesn't work, I end up with: 
```
> Using @sveltejs/adapter-cloudflare
✘ [ERROR] Could not resolve "fs"
```
and a bunch of other similar errors.

**Comment by jeffijoe** [comment]
Thanks everyone for your help! `12.0.2` has been released!

**Comment by ccremer** [comment]
Thank you for your dedication :blush:
