### ISSUE TITLE
Inject mocks for test suite

### ISSUE THREAD

**Issue by leorossi** [jeffijoe/awilix#37]
I migrated from another DI library to `awilix`. I migrated the codebase but now I am struggling with test suite, since I use mocks for many of the tests I am wondering how I can inject my custom modules after I register them in the container. 
Is there a way to do that?

**Comment by jeffijoe** [comment]
Not sure what you mean, could you elaborate, perhaps with an example of what you're trying to do?

**Comment by leorossi** [comment]
Thanks for the quick reply.
I am migrating also the test suite which originally was using the old library, so I am not sure the same approach will work with `awilix`. Here is an example

Example:
file `api_utils.js` is the module to be tested.
```
module.exports = function({ env, log  }) {
  const API_Utils = function API_Utils() {

  }
  API_Utils.prototype.doStuff = function() {
    log.info('Doing some stuff');
  }
  return API_Utils;
};
```

This is a sample module that can use the previous one

```
module.exports = function({ api_utils }) {
  apiUtils = new api_utils();
  apiUtils.doStuff();
}
```
The unit test file `test/api_utils.js` (using `mocha`) 

```
...
describe('API_Utils', () => {
  it('should log "Doing some stuff"', (done) => {
    const mocks = {
      log: {
        info: function(message) {
          assert.equals(message, 'Doing some stuff');
        }
      }
    }
   // How should I inject mocks.log ?
  });
});
```

**Comment by jeffijoe** [comment]
First of all, your general usage seems wrong to me, since you are exporting a function which itself creates a function.

This is how I would do it:

`api_utils.js`

```js
module.exports = API_Utils

function API_Utils ({ env, log  }) {
  this.env = env
  this.log = log
};

API_Utils.prototype.doStuff = function() {
  this.log.info('Doing some stuff');
}
```

And the usage:

```js
module.exports = function({ apiUtils }) {
  apiUtils.doStuff();
}
```

And finally the test:

```js
const APIUtils = require('../path/to/api_utils.js')

describe('API_Utils', () => {
  it('should log "Doing some stuff"', (done) => {
    const mocks = {
      log: {
        info: function(message) {
          assert.equals(message, 'Doing some stuff');
        }
      }
    }
    const apiUtils = new APIUtils(mocks)
    // Use here
  });
});
```

Does this make sense?

**Comment by leorossi** [comment]
Yes it makes sense. 

The old library required to use the 
```
module.exports = function(dep1, dep2 ... ) {
 // here create the returnable object
}
```
That's why is used the same with `awilix`. Will test soon and update (or close) the issue. Thanks for now

**Comment by leorossi** [comment]
Ok I managed to understand better how to refactor the codebase and make it simpler.
I have another question but I'll close this issue and open another, after searching for previous similar issues. Thanks.
