### ISSUE TITLE
`awilix/browser`: SyntaxError: Named export 'RESOLVER' not found

### ISSUE THREAD

**Issue by MathiasWP** [jeffijoe/awilix#377]
Upgrading to Awilix v12 throws this error when trying to import from `awilix/browser`:

<img width="687" alt="image" src="https://github.com/user-attachments/assets/b8eafcde-872f-4692-b4a9-47e6d2eb352a">

**Comment by MathiasWP** [comment]
I see now that it is because i'm in a Node env, and there's a entry for that ENV

**Comment by jeffijoe** [comment]
I'm renaming `awilix.browser.js` to `awilix.browser.mjs` (see discussion in #368) which should fix this.

**Comment by jeffijoe** [comment]
Please try `awilix@12.0.2-alpha.0`

**Comment by MathiasWP** [comment]
> I'm renaming `awilix.browser.js` to `awilix.browser.mjs` (see discussion in #368) which should fix this.

Thanks! I was just setting up a PR to do this, but you got there first 😸

**Comment by jeffijoe** [comment]
We've been trying to figure this out for a few days.  

![image](https://github.com/user-attachments/assets/1f67991a-1f95-4890-b3f6-bb0223901857)

**Comment by MathiasWP** [comment]
i feel sorry for you haha, are you making a new release with this fix?

**Comment by jeffijoe** [comment]
Yes, once it's been confirmed to also work with CloudFlare - I'm getting tired of writing "fix exports" in the changelog. 😅
