### ISSUE TITLE
awalix version12.0

### ISSUE THREAD

**Issue by Onjaniaina754** [jeffijoe/awilix#379]
awilix 12.0 os.platform is not a function

**Comment by jeffijoe** [comment]
Awilix doesn't use `os.platform`

**Comment by bartosz-szymanski** [comment]
But `fast-glob` does.

**Comment by jeffijoe** [comment]
I see. Any additional info would be appreciated, this issue is not much to go by. Does this error on install? When calling `loadModules`?

**Comment by bartosz-szymanski** [comment]
I have updated my previous comment.

**Comment by bartosz-szymanski** [comment]
I did not.
It works like a charm, thank you very much. 
Somehow it works in my different project with awilix 10.0.1 and vite 4.4.5 where I do not use `import { .. } from 'awilix/browser'`

**Comment by jeffijoe** [comment]
Awilix 10 didn't have any `exports` in `package.json`, but Vite should honor them or use the existing fields that didn't change.
