### ISSUE TITLE
Event when value has been changed

### ISSUE THREAD

**Issue by dominikj111** [jeffijoe/awilix#380]
I'm registering my value by `asValue` and I'm wondering if there is any event to react on when I'm overriding registered value.

Thank you

**Comment by jeffijoe** [comment]
There’s not, but you could wrap the container to do this. Whats the use case? Usually these things are better handled in userland. The container shouldn’t really have to change much after startup. Some containers even prevent updates after initializing.

**Comment by dominikj111** [comment]
Of course, I just didn't want to do something what would be potentially part of the lib.

> The container shouldn’t really have to change much after startup. ...
It makes sense. I jus noticed `asValue` and I was thinking what I can do with it. Maybe `asConst` will not cause me to think like that :) 

I'm working on a quite complex set of React applications. Not the SPA, but plenty of modules where any is an app in page container. I have single shared context per module application, so not a complex pattern. Plus mix of many React components, hooks and static utilities.

I'm looking for a good way to shape it better with DI.
