### ISSUE TITLE
Importing awilix is broken in a browser environment

### ISSUE THREAD

**Issue by christianlundberg** [jeffijoe/awilix#384]
Importing from `awilix` when running in a browser environment results in an error:

`Uncaught TypeError: os.platform is not a function`

It seems that this is happening because, the [package exports](https://github.com/jeffijoe/awilix/blob/master/package.json#L20) incorrectly list `browser` at the end, whereas the [Node](https://github.com/jeffijoe/awilix/blob/master/package.json#L20) documention mentions that key order is important, and an earlier condition match would have a higher priority.

Importing from `awilix/browser` fixes this issue, but it's not an option in my case, because I'm working on a package that can run on browser and react native, and package exports aren't supported by default on react native.

**Comment by jeffijoe** [comment]
So listing `browser` first would fix the issue?

**Comment by christianlundberg** [comment]
@jeffijoe yes, I believe right now it does nothing. By moving it to the top, it would match the `browser` key when building for web, and `import` should match when building for Node. You might also want to add the `react-native` key in the package exports as well, since there's already experimental support for it, because once it's enabled by default, you might have the same issue where it starts matching the `import` key.

**Comment by christianlundberg** [comment]
I just noticed I posted the wrong link to the docs

https://nodejs.org/api/packages.html#conditional-exports

**Comment by jeffijoe** [comment]
@christianlundberg please try `awilix@12.0.4-alpha.0` and let me know if it fixes the issue.

**Comment by christianlundberg** [comment]
@jeffijoe thanks for the quick response, it working perfectly in the browser environment now.

**Comment by jeffijoe** [comment]
Perfect, I'll release the official patch now, thanks for testing

**Comment by jeffijoe** [comment]
`12.0.4` released, thanks for the report and help testing!
