### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Vincz** [jeffijoe/awilix#43]
Hi! First of all, you did a really good job with Awilix. I like IOC and your lib is really good.
I’m currently working on a node framework, modular and I’d like to use Awilix (I don't want ti reinvent the wheel) as one of the main ingredient, using the power of container to have a robust plugins system (plugins able to declare services).
The idea would be to be able to “describe” services creation like the PHP Symfony Framework do (https://symfony.com/doc/current/service_container/definitions.html).
For example, imagine if I have a mail builder service sending emails thank to a “mailer” service, I would like to be able to describe the service like that (the “@“ prefix means it’s a reference to a service).

    // services.js
    services: {
        “my-mail-builder”: {
            class: “service/my-mail-builder”, 
            args: [“@mailer”, “no-reply@mydomain.com”]
        }
    }

And why not with other features, like calls to setters, services tagging, etc… 
Currently, correct me if I’m wrong, Awilix parses the final class to detect the services that need to be injected, right ? The “resolution modes”: classic or proxy.
So, the service itself is responsible for declaring every others services it depends on. It could be great to be able to declare the dependencies (the constructor args) outside the service itself. An "explicit" way. So, for the example above, we would end with something like that:

	container.register({
		“my-amazing-service”: asClass(require(“service/my-amazing-service”)).withArgs(“@mailer”, “no-reply@mydomain.com”)
	});

This way, we would be able to change the way the services are wired really easily, with config.
What do you think ?

**Comment by jeffijoe** [comment]
Thanks for the kind words!

Awilix already supports [`inject`](https://github.com/jeffijoe/awilix#per-module-local-injections), which works regardless of resolution mode. It lets you add per-module arguments, although you still need to know the argument name up-front.

Does that solve your issue?

Also, keep in mind that you can create your own registration types that resolves the way you want it to. Take a look at [`asValue` ](https://github.com/jeffijoe/awilix/blob/master/lib/registrations.js#L82) for a simple example.

**Comment by jeffijoe** [comment]
Also, the whole idea with a container is that you shouldn't have to worry about each implementation's dependencies; that's what the container does for you. If I were you, I'd use your `args` as a way to use `inject` for isolated per-module dependencies and let Awilix figure out the rest. 😄

**Comment by Vincz** [comment]
You're right. I think I should be able to achieve what I want by defining a asDefinition() function just like asValue, asClass or asFunction. 
The purpose of this service definitions is to be able to modify the behavior of services that can be define in the project dependencies (for a plugin system).

For example, let's say, that I create a plugin to expose a mailer service (a module myframework-mailer-plugin). 
I have multiple ways to do so:

**Create the service manually in my project**

    const MailerClass = require('myframework-mailer-plugin').Mailer;
    container.registerClass("mailer", MailerClass);

I don't like it because I would prefer that my plugin define their own services.

**Give the container to the plugin at some point**

    const populateContainer = require('myframework-mailer-plugin').servicePopulator;
    populateContainer(container);

I don't like it either because the plugin is able to do anything with the container and it'll define the service is own way without anyway to "customize" the service creation process.

**With the service definitions, we can create and customize the service in the plugin are define.**

    // myframework-mailer-plugin.js
    const MailerClass = require('myframework-mailer-plugin').Mailer;
    module.exports.services = {
        mailer: {
            class: MailerClass,
            args: ["@mailer.transport"]
        }
    }

And in my project, I'll grab the definition of services exposed by the plugin and be able to change them.

    const MyMailerClass = require('./MyMailerClass'); // My custom class that extends the MailerClass from the plugin
    const definitions = getAllPluginsDefinitions();
    definitions.mailer.class = MyMailerClass
    container.processDefinitions(definitions);

This definitions would allow to customize the service generations process in many ways.
I think the auto-wiring of the services based on the args is the best way for the personal codebase.

**Comment by jeffijoe** [comment]
Well like I said you can do basically anything you want by writing using a custom registration 😃

The registration API isn't documented other than with code comments cause I didn't think anyone would ever want to write any, but glad I implemented it in a modular fashion now! 🎉

**Comment by Vincz** [comment]
@jeffijoe Yes, of course !

I've made some progress but I still have design questions.
The api looks like this : 

    container.registerDefinition({
        target: aClass|aFunction|aString,
        args: array|object
    })

The **target** can be a class, a function or a string. 
If it's a string, it can be of two forms:
    `"xxxxxx"   == require("xxxxx")`
or
    `"xxxxxx::a.b.c"  == require("xxxxx")[a][b][c]`

this way, we can resolve exported function or classe locally or in modules. This behavior could be customise by providing a custom targetResolver function.

If the **args** is provided, it must be an array if the resolution mode is classic, and an object if the resolution is a proxy.

If it is defined, it'll replace the corresponding keys in the constructor (using inject).
It will also be recursively parse to resolve string prefixed by an "@".

For example:

    const service = ({blue, red, logger}) => () => console.log(blue("hello blue"), red("hello red"));

    registerDefinition({
        target: service,
        args: { 
            blue: (msg) => "<blue>" + msg + "</blue>",
            logger: "@logger2"
        }
    })

Will replace **blue** by the function define in args
Will leave the auto-resolve of **red**
Will replace **logger** by `resolve(logger2)`

So in the end, the asDefinition function, just wrap the asFunction or asClass resolver function  (by checking the type of the target definition), after setting an injector if some args are provided. But everything is done in the resolve (as I need the container to resolve the args).

The goal is to be able to load a set of definitions, and to be able to change this definitions before the services are created.

For example, something like that:

    container.getDefinition('myservice').replaceArgs("logger", "@logger3")

I realise that It's a lot of changes if I want to cover my use cases and I'm wondering if I should submit PRs on your project or if I should start my own. What do you think about that ?

**Comment by jeffijoe** [comment]
You can access the object returned by the `as*` functions by using `container.registrations.myservice`, so you can alter it if you want. You could just wrap Awilix and expose an API that uses it.

**Comment by Vincz** [comment]
With the new API their is many ways to get the same result:

`asClass == asDefinition(target: class)`
`asFunction == asDefinition(target: class)`

and asClass is almost the same as asFunction except the class is wrapped in asClass and the target is the constructor instead of the function itself.

Also, you do already have the isClass() function. So, you're able to guess, given an argument, if it's a class or a function.
And the current version of asDefinition, well... it's just resolving the target, checking if the resolved module is a class or a function, and calling generateResolver accordingly.

So in the end, we could remove asClass and asFunction, and just keep asDefinition (or whatever name) and auto-detect everything (is it a class ? is it as function ? is it a module that need to be require ?) and embedding the service name in the definition.

We could have a Definition class with a nice api like:
```
    definition.getServiceName()
    definition.replaceArg()
    definition.setTarget()
    definition.setOption(xxx)
```

And we could interact with it through the container
    container.getDefinition(serviceName)

About the magic strings, this is how Symfony handle them:
http://symfony.com/doc/current/service_container/parameters.html

Their is also a notion of container parameters, resolved by the magic string "%<param>%"
So as the magic string would only be used in the args definition, I don't think it would be a problem. Symbol could be great, but the idea is to be able to define this "definitions" from a nice readable config file.

**Comment by jeffijoe** [comment]
I would prefer to keep the `asClass` and `asFunction` as-is to ensure you always have the choice to chose one over the other in case the `isClass` heuristic fails—which is possible. While it is common to use `PascalCase` for constructor functions, not everyone follows this pattern and the option to manually choose the registration type is favorable to them.

Awilix does not expose any "official" way to mutate registrations other than by explicitly overwriting them with new ones.

What exactly is it you are trying to achieve with your proposed mutable API? Why would you need/want to use `definition.replaceArg()`?

**Comment by jeffijoe** [comment]
I'd like to stay in the spirit of module composition, and so I suggest you author an npm module that wraps Awilix to support your definitions proposal—this will allow for the most flexibility to bring your idea to life. I completely understand where you are coming from regarding the Symfony container, but I'd like Awilix to remain lightweight. The README is already getting quite big, and adding _even more ways to do this_ to core might scare people off.

Here's an example usage and implementation demoing how easily you can build a declarative framework on top of Awilix:

```js
import { createContainer, asClass, asFunction } from 'awilix'
import isClass from 'awilix/lib/isClass'
import { declarative } from 'yournewpackage'

// Pass in a container instance and configure away
const container = declarative(createContainer())
  .define({
    name: 'my-mail-builder',
    target: service,
    args: { 
        blue: (msg) => "<blue>" + msg + "</blue>",
        logger: "@logger2"
    }
  })
  .container



// example implementation
function declarative (container) {
  return {
    container,
    define (spec) {
      const reg = isClass(spec.target) 
        ? asClass(spec.target) 
        : asFunction(spec.target)
      container.register(
        spec.name, 
        // Custom injector to resolve arguments
        // "scope" is the relevant (child) container to use, important!!
        reg.inject((scope) => resolveArgs(scope, spec.args))
      )
      return this
    }
  }

  function resolveArgs (scope, args) {
    const result = {}
    Object.keys(args).forEach(k => {
      const val = args[k]
      if (typeof val === 'string' && val.startsWith('@')) {
        // Resolve the value from the container
        result[k] = scope.resolve(val.substring(1))
      } else {
        result[k] = val
      }
    })

    return result
  }
}
```

What do you think?

**Comment by Vincz** [comment]
The purpose of this mutable API would be the modularity.

$ npm install myframework-plugin

    // in my app
    const definitions = require("myframework-plugin").definitions;
    const container = awilix.createContainer();

    container->loadDefinitions(definitions);

    // the exposed services are amesome, but I just need to customise one of them

    container->getDefinition('super_service')->setTarget(myCustomClass)

**Comment by Vincz** [comment]
Yes, you're right. I could wrap Awilix and make an Awilix container builder.

**Comment by jeffijoe** [comment]
> `container->getDefinition('super_service')->setTarget(myCustomClass)`

You can do this already 😃

```js
container.register('super_service', asClass(MyCustomClass))
```

**Comment by Vincz** [comment]
Yes, you're right. But there is others use cases, where it could be nice to just customise part of the service declaration without having to redefine the complete service.

**Comment by jeffijoe** [comment]
In that case, you can resort to:

```
container.register('myService', {
  ...container.registrations.myService,
  injector: () => ({ woo: 'hoo' }), // add new injector
  lifetime: Lifetime.SCOPED // add new lifetime
})
```

It will overwrite the registration by merging the old one into the new one. 😄

**Comment by jeffijoe** [comment]
In your container builder wrapper, you can defer building the container until all your mutations on your definitions have taken place. That's what I recommend, at least.

**Comment by Vincz** [comment]
Yes, exactly. I was thinking about a generate() method on the container that would freeze it, making it immutable.

**Comment by jeffijoe** [comment]
That'll be difficult because child containers (scopes) rely on being able to add registrations right before resolving a service—that's how can inject the current user into a service.
