### ISSUE TITLE
improve readme for container.listModules()

### ISSUE THREAD

**Issue by constb** [jeffijoe/awilix#47]
I might be an idiot, but I bet I'm not the only one. 😄 I spent hours trying to figure out why `container.listModules()` just refuses to work in my serverless/aws-lambda app, until it hit me – I'm bundling my app using webpack! So there's simply no files to look for and require at all!

I don't know, maybe if you added a short disclaimer that one shouldn't expect it to work like this, it would save somebody else a little time or more…

**Comment by jeffijoe** [comment]
Check out https://github.com/jeffijoe/awilix/issues/19 — basically Awilix _does_ work in Webpack, but anything that relies on `glob` sadly can't work. I'll make sure to add this under the `loadModules` and `listModules` sections, thanks for bringing this up!

On a side note: why are you webpacking your server code? 😄

**Comment by jeffijoe** [comment]
Readme has been updated. Thanks again for bringing this up! 👍 

![image](https://user-images.githubusercontent.com/2505474/32600838-29435f94-c541-11e7-9fbb-c6a4a0b02727.png)

**Comment by constb** [comment]
> On a side note: why are you webpacking your server code?

aws lambda only has node 6, and I just can't imagine coding without async/await anymore… 😄

**Comment by jeffijoe** [comment]
Oh man—alright you are most certainly excused! 😂

**Comment by constb** [comment]
> Any reason you don't just use Babel without Webpack? 😄

tooling mostly. I use serverless framework and it already has webpack plugin and a starter template that has it preinstalled. and I'm a bit of a newbie in all this (php dev learning node), so I just stick with what I've got for now :) it's good though to discover that node.js people already took care of IoC and stuff… 😄

**Comment by jeffijoe** [comment]
If you're feeling adventurous, check out my [Koa template](https://github.com/jeffijoe/koa-es7-boilerplate) which uses Awilix. 😄

I've never used serverless framework myself, but it should definitely be possible. 😁
