### ISSUE TITLE
Disposer support

### ISSUE THREAD

**Issue by jeffijoe** [jeffijoe/awilix#48]
# Proposal

Support disposing dependencies.

Each resolver (registration) can specify a disposer function to call when `container.dispose()` is called. 

# Motivation

This is useful for managing dependencies that have resources to dispose—connection pools for example.

In test runners like Jest, watch-mode will recycle worker processes which means connections may or may not have been closed between each run. In testing HTTP servers, It is a good practice to call `server.close()` after the tests are done.

We want to be able to run cleanup on dependencies in the same way. For example:

```js
server.on('close', () => container.dispose())
```

# Proposed API

* Introduce `container.dispose()`
* Introduce `disposer` option for `asClass` and `asFunction` resolvers
* Disposing a container also disposes it's child (scoped) containers
* Containers are disposed bottom-first; this means scoped containers are disposed before their parent.

# Example

```js
const pg = require('pg')
const { createContainer, asFunction } = require('awilix')
const container = createContainer()
  .register({
    pool: (
      asFunction(() => new pg.Pool({ ... }))
        .disposer((pool) => pool.end())
    )
  })

// .. later
container.dispose()
```

**Comment by cikasfm** [comment]
+1 Yes, please!

**Comment by Seldszar** [comment]
Would it be possible to make disposers async?
Like for waiting a database disconnection, for example.

**Comment by jeffijoe** [comment]
@Seldszar yeah, I was thinking that as well. 😀
