### ISSUE TITLE
loadModules - return container?

### ISSUE THREAD

**Issue by jeffijoe** [jeffijoe/awilix#5]
Currently `loadModules` returns an array of objects that tell you what paths were loaded. However given that all other container methods (apart from `resolve` for obvious reasons) are chainable (returns the container itself). Should `loadModules` do that as well? Is the result from `loadModules` more useful than chaining?

@donjae @jonahx @ddproxy what do you think? :smile:

**Comment by donjae** [comment]
Tbh, I have no bias either way since I just use the setup from the Koa starterpack. 

It's up to you!

**Comment by jeffijoe** [comment]
Yeah I am thinking returning the container might be a good idea. This would be a breaking change but I don't feel it warants a major version.

**Comment by jonahx** [comment]
I like it.  It wouldn’t break anything for me I don’t think.

**Comment by jeffijoe** [comment]
Excellent, will get on this when I get the time. Thanks guys,
