### ISSUE TITLE
Why "Awilix", not "DI" or similar?

### ISSUE THREAD

**Issue by cikasfm** [jeffijoe/awilix#54]
OK, stupid question.

This is a great framework! As coming from Java / Spring world to Node.JS - I was looking for something similar and I'm so glad I finally found this!

I bet that the reason I wasn't able to find this lib/fw in Search Engines is because of the name...I'd never follow this name to find DI framework. I know Spring is not named as "DI" or anything similar so maybe there's really no reason for it; but it's already a 10.000x times more popular than this, but to help this project grow and be used more often - why not name it something related to "DI"? Well at least "Jeff's DI" or "Awilix DI" or smth? :)

I mean I know I could rename it myself in my local code...

```
const di = require('awilix')

const container = di.createContainer({
  resolutionMode: di.ResolutionMode.PROXY
})
```

or

```
const ioc = require('awilix')

const container = ioc.createContainer({
  resolutionMode: ioc.ResolutionMode.PROXY
})
```

I mean I'd suggest to rename this to one of:

- `jeffjoe/di`
- `jeffjoe/node-di` ( or `js-di`? )
- `jeffjoe/awilix-di`

Or similar. WDYT?

**Comment by jeffijoe** [comment]
Cause it sounds cool! When people are like “so hey what DI lib do you use?” you get to reply “Awilix... aw yeah.” 😎

Haha, in all seriousness, I (or the community? 😉) just need to write some articles and build cool stuff with it and spread the word on Twitter, etc. I already wrote a relatively popular Medium series titled “Node.js Dependency Injection - 2016 edition” which has all the right keywords. 😄 

Even if it was called “Jeff’s DI” I doubt you would have found it any sooner as I think popularity wins over keywords. Awilix reached 250 stars just a month ago, so it’s going slow but steady. 😄 

But really, thanks for the kind words! If you have any ideas to help spread the word more easily do let me know!

**Comment by cikasfm** [comment]
Yes I've just accidentally found this article on Medium, which is great! Maybe it's just me with non-English heritage just have feeling that it's hard to pronounce this word ( or as general in US - more than 2 syllables are too many :D )

Just got +1 star and +1 tweet ;)

**Comment by jeffijoe** [comment]
I personally pronounce it “ah-wee-liks”, I got the name from “Awilix, mayan goddess of the Moon” from the videogame Smite. 😄 

Thanks for the star + the tweet!

**Comment by julestruong** [comment]
I definitly second cikasfm, i've always wanted a DI manager in nodejs, and find this by chance.

**Comment by jeffijoe** [comment]
@julestruong thank you!

Once Awilix gets a few more stars I'm sure it'll be easier for people to find it. Also (at least for me), the Awilix Medium article is ranked 1st on Google search for "node dependency injection" 😄 

![image](https://user-images.githubusercontent.com/2505474/32886397-d4453550-cac0-11e7-8a58-5ecd266a757c.png)

**Comment by cikasfm** [comment]
yes, as of now; this just didn't happen ~6 months ago when I really needed this... :)

**Comment by jeffijoe** [comment]
Haha we all have to start somewhere 😄
