### ISSUE TITLE
Tracking child containers may lead to memory issue

### ISSUE THREAD

**Issue by jeffijoe** [jeffijoe/awilix#65]
In order for a parent container to dispose it's children, the parent needs to track the children.

This is a problem because children are usually created per request, meaning each request means an entry in the child array for the parent. With enough requests, that array will be very large.

I don't think there's a good way to deal with this, other than simply not disposing child containers which means we can avoid the child array.

Related to #48

**Comment by jeffijoe** [comment]
@Seldszar do you think it's fine if we just don't dispose child containers automatically?

In a way it kinda makes sense; if you wanted a connection per request, you should also manually close it after the request and not wait for the parent container to do this when the server shuts down.

**Comment by Seldszar** [comment]
You mean scopes? It wouldn't be a big deal for me to dispose them manually and I agree with the reference array being too big and causing potential performance/memory issues.

**Comment by jeffijoe** [comment]
@Seldszar Yes—**scopes** are basically just another container with a reference to it's parent. 😄 

Excellent, I'll fix this now.

**Comment by jeffijoe** [comment]
Published as `v3.0.0-rc.3`, thanks for the quick response @Seldszar!
