### ISSUE TITLE
Different behaviour on node and babel+webpack

### ISSUE THREAD

**Issue by smikheiev** [jeffijoe/awilix#72]
I made a simple test project: https://github.com/smikheiev/awilix-test

There are two classes: `AppModel` and `AppController`, `AppController` has dependency of `AppModel`. Both classes are registered in container. And when I run it in browser (built with babel and webpack) it doesn't work like it should, but with node it works like a charm.

When I run it with node `AppController` has correct dependency injection. Constructor argument `opts` is `Proxy` (`opts [AwilixContainer.cradle]`) and `AppModel` instance can be simply get from it (using object property or destructuring).
But when I run it with browser (babel+webpack) argument `opts` of `AppControler` constructor is `arguments` object (`opts Arguments(1)`), where `Proxy` is the first element and it's needed to do something like `opts[0]` to get `AppModel` instance from it.

I found that the problem in browser is with passing arguments to constructor, because if to get the model with `container.cradle` it's ok.

**Comment by jeffijoe** [comment]
Thanks for reporting! I'll investigate and let you know. Happy holidays!

**Comment by jeffijoe** [comment]
@smikheiev as I suspected, the issue was TypeScript transpiling the class instantiation wrong—how that happens I have no idea.

I fixed it by replacing `new Type(...arguments)` with `Reflect.construct(Type, arguments)`, and has pushed the fix to `npm` as `awilix@3.0.1`.

Thanks again for reporting!

**Comment by smikheiev** [comment]
Cool, thanks for such a quick fix! Happy holidays!
