### ISSUE TITLE
Registering a class

### ISSUE THREAD

**Issue by jshjohnson** [jeffijoe/awilix#73]
Firstly, thanks for creating a great library!

I would like to know how one goes about registering a class to a container. At the moment I am getting a `TypeError: Cannot read property 'constructor' of undefined` error.

Here is the class I want to register:

```js
module.exports = ({ mongoose }) => {
  const { Schema } = mongoose;

  const bugSchema = new Schema({
    id: {
      type: String,
      required: true,
      index: true,
      unique: true,
    },
    url: {
      type: String,
      required: true,
      unique: true,
    },
  });

  const Bug = mongoose.model('Bug', bugSchema);

  return Bug;
};
```

And here is how I'm registering it:

```js
const Bug = require('./schemas/bug');

container.register({
  Bug: asClass(Bug),
});
```

Thanks

**Comment by jeffijoe** [comment]
So you are basically returning a function (class constructor) from another function. How do you expect to use the `Bug` class? 😄

**Comment by jeffijoe** [comment]
Please let me know if this answered your question so I can close, thanks 😀

**Comment by jshjohnson** [comment]
Hey @jeffijoe.

How would I go about exporting a class with a dependency then? The reason I need the class exported is because I need access to it's static methods and I don't really want to wrap each method with functions.

**Comment by jeffijoe** [comment]
Mongoose is a very DI-hostile library since it forces you to generate classes using a connection. The approach I mentioned in my last comment will work though.

```js
// service.js
module.exports = function({ Bug }) {
  // We inject the Bug constructor here.
  return {
    create(data) {
       const bug = await Bug.create(data)
       return bug
    }
  }
}

// container.js
const container = createContainer()
  .register({
    // singleton = reuse the constructor once it has been created
    Bug: asFunction(require('./Bug')).singleton(), 
    service: asFunction(require('./service')),
    mongoose: 
      // Whenever we first request a `mongoose`, create a connection.
      asFunction(
        () => require('mongoose').createConnection()
      )
        // Make sure we only have 1 connection per process.
        // (the connection is reused)
        .singleton()
        // Whenever we use `container.dispose()`, close the connection.
        .disposer((conn) => conn.close())
  })

// usage
const service = container.resolve('service')

service.create({ title: 'Stuff not working' })
  .then((bug) => console.log(bug))
```

Does this make sense? 😄

**Comment by jshjohnson** [comment]
Nice! Thanks for your help. :)

**Comment by jeffijoe** [comment]
You're most welcome!
