### ISSUE TITLE
Accessing container for building dependencies from modules

### ISSUE THREAD

**Issue by prabhjot85** [jeffijoe/awilix#74]
First of all, thanks for creating this nice and simple library. Looking at this issue (https://github.com/jeffijoe/awilix/issues/50), I understand that in order to access the registered instances, one needs access to container. How do you recommend accessing the container from separate modules? I'd not like to pass the container instance out of band. 

As an example
//index.js

```
 const container = createContainer();
  container.register({
    myRepository: asClass(require('./lib/sample/myRepository')).singleton(),
   logger: asClass(require('./lib/logger)).singleton()
  });

```

//myRepository.js
```
class MyRepository {
  createSample() {
     return container.build(SampleInstance); **//How do I get access to container?**

}
}

```
//SampleInstance.js

```
class SampleInstancer{
     constructor({logger}){  //**Expected to be injected by container, but it's not registered**
          this.logger = logger;
    }

}
```

**Comment by jeffijoe** [comment]
Thanks!

Nice crate digging on finding that issue! 😄 You can definitely use `container.build` for this. More specifically, you want to use a **factory** (as I've alluded to [here](https://github.com/jeffijoe/awilix/issues/29#issuecomment-318328305)) which will let you instantiate things ad-hoc as many times as you want, **without coupling yourself to the container**. 🚀

I strongly suggest you follow the approach outlined in #29 to avoid referencing the container, however it you must, you can make the container available using `inject`:

```js
container.register({
  myRepository: 
      asClass(require('./lib/sample/myRepository'))
        .singleton()
        .inject((c) => ({ container: c })),
})
```

This will inject the correct container into `myRepository`.

```js
class MyRepository {
  constructor({ container }) {
    this.container = container
  }
  createSample() {
     return this.container.build(SampleInstance);
  }
}
```

Again, I **strongly suggest you take the approach in #29** as using `container.build(Class)` will do some internal preparation work each time it's called, unless it's called with a **resolver**; see the [docs on `build`](https://github.com/jeffijoe/awilix#containerbuild)

Hope this helps. 😄

**Comment by prabhjot85** [comment]
Thanks @jeffijoe. This should work for me. Closing the issue.
