### ISSUE TITLE
[Typescript] no exported member 'listModules'

### ISSUE THREAD

**Issue by TdyP** [jeffijoe/awilix#76]
Hi!
I would like to use Awilix in a Typescript project.
I'm trying to import the `listModules` function:
```
import {listModules} from 'awilix';
```

But getting an error:
```
src/DepsManager.ts(2,43): error TS2305: Module '"[....]/node_modules/awilix/lib/awilix"' has no exported member 'listModules'.
```

Is it a problem with my `import` or something missing in types declaration? 

Thanks for your help! :)

**Comment by jeffijoe** [comment]
Thats odd, it should definitely be exported!

https://github.com/jeffijoe/awilix/blob/master/src/awilix.ts#L2

Are you sure you are using `awilix@3`?

**Comment by TdyP** [comment]
yep, running awilix@3.0.3

awilix.d.ts : 
```
export * from './errors';
export * from './container';
export * from './resolvers';
export * from './injection-mode';
export * from './lifetime';
```

No list-modules in it

**Comment by jeffijoe** [comment]
Wow, that's weird. I'll look into why that gets stripped out.

**Comment by TdyP** [comment]
OK
Importing from `awilix/lib/list-modules`does make the job.

Thanks for your reactivity 👍

**Comment by jeffijoe** [comment]
I think I figured it out; The Rollup build is overwriting the typings, and the Rollup browser builds don't contain `listModules`. I'll see what I can do.

**Comment by jeffijoe** [comment]
@TdyP fixed in 3.0.4; this was a great catch, well done! Thanks for reporting! 👍

**Comment by TdyP** [comment]
Issue fixed with a new release in 1 hour 🥇 

Thanks, keep up the good work!

**Comment by jeffijoe** [comment]
No, thank _you_ for using Awilix! 🚀
