### ISSUE TITLE
Electron BrowserWindow - no arg Constructor?

### ISSUE THREAD

**Issue by tehnorm** [jeffijoe/awilix#77]
Awilix is pretty slick! Thank you for hard work.

I think I might be missing how `injector` is meant to function.

Say I have:
```
registry.register('electronBrowserWindow', asClass(BrowserWindow, {
        injector: () => ({ height: 600, width: 1200, backgroundColor: '#312450' }),
        lifetime: Lifetime.TRANSIENT,
        injectionMode: awilix.InjectionMode.PROXY
}));
```

I would expect when `electronBrowserWindow` is resolved it to be created with the arguments provided in `injector`. It would seem this is not the case. 

I think I understand why - as the constructor signature to `BrowserWindow` has no arguments when in reality it optionally takes quite a few: https://electronjs.org/docs/api/browser-window#new-browserwindowoptions

```
console.log(BrowserWindow.toString());
function BrowserWindow() { [native code] }
```

What would be the approach to having awilix really, pretty please, cherry on top inject - the arguments provided via the `injector`. Maybe there already is a pattern to accomplish this use case?

**Comment by jeffijoe** [comment]
You are using it correctly! What happens? Does the window get created? Since you use Proxy injection, BrowserWindow’s arity is irelevant.

**Comment by jeffijoe** [comment]
I don't know Electron's internals, but could it be possible they are doing some check on the options object passed in that the proxy does not fool?

Either way, since you likely are not passing in any dependencies from your container into `BrowserWindow`, I suggest using:

```js
registry.register(
  "electronBrowserWindow",
  asFunction(
    () =>
      new BrowserWindow({
        height: 600,
        width: 1200,
        backgroundColor: "#312450"
      }),
    {
      lifetime: Lifetime.TRANSIENT,
      injectionMode: awilix.InjectionMode.PROXY
    }
  )
);
```

May I ask why you are using `TRANSIENT` lifetime? 😄

**Comment by tehnorm** [comment]
Thank you for the quick reply! The `BrowserWindow` is created but does not make use of any of the passed options. The `asFunction` method seems like a reasonable approach. As I understand `TRANSIENT` will hand back a new object on each resolution? In the case of a `BrowserWindow` in our application we can create additional windows so it seems like the correct lifetime value.

**Comment by jeffijoe** [comment]
Yes thats correct, just checking 😄

**Comment by tehnorm** [comment]
The function method worked. Thank you for your help on this!

**Comment by jeffijoe** [comment]
You’re most welcome!
