### ISSUE TITLE
[Question] How to resolve with event emiter

### ISSUE THREAD

**Issue by huyaloha** [jeffijoe/awilix#78]
Hi @jeffijoe,
I'm using Hydra for my project with Awilix. Everything work fine with Awilix and Awilix-express for REST API. However, if the app is fired via `hydra.getHydra().on(...)`, the umfHandler cannot be resolved.

```js
module.exports = class Hydra {
  constructor (opts) {
    this.config = require('./config').HYDRA;
    this.umfHandler = umfHandler; // Resolve handler successfully
  }

  initialize () {
    return new Promise(function (resolve, reject) {
      hydra
        .init(config, function () {
          hydra.registerRoutes(routerConfig);
          hydra.getHydra().on('message', (message) => {
            this.umfHandler(message);  // Undefined
          });
        })
        .then(function () {
          resolve(hydra);
        })
        .catch(function (err) {
          reject(err);
        });
    });
  }
};
```

Do we have any way to resolve the function like that.

```js
// container.js
container.loadModules(
  [
    ['../src/repository/*.js', Lifetime.SINGLETON],
    ['../src/service/*.js', Lifetime.SCOPED]
  ],
  opts
).register({
  mongoose: asFunction(
    () => require('mongoose').createConnection(config.database.mongodb)
  ).singleton().disposer((conn) => conn.close()),
  umfHandler: asFunction(
    () => require('./umf')
  ).singleton(),
  containerMiddleware: asValue(scopePerRequest(container))
});
```

**Comment by jeffijoe** [comment]
Not sure if it's a typo but you're not defining `umfHandler` anywhere in your constructor.

```js
this.umfHandler = umfHandler; // <- not defined
```

Maybe you meant this?

```js
this.umfHandler = opts.umfHandler;
```

**Comment by huyaloha** [comment]
Sorry, my bad. Yes, typo. Actually and I can resolve successfully on constructor
`this.umfHandler = opts.umfHandler;` 

What I would like to achieve  are:
- I have couple of services and all using Hydra for service discovery, message exchange, api gateway
- In service A, it sends a message M via hydra to service B
- Hydra will handle the message by delivery the message to service B then invoke a function in umfHandler
`hydra.getHydra().on('message', (message) => {
            this.umfHandler(message);  // Try to resolve but got Undefined
          });`

I have tried couple ways but cannot resolve the `umfHandler` inside `hydra.getHydra().on(....)`. So, is it possible to resolve, yes, per event? 
I have no issue with Express by using `awilix-express` and inject as middleware (`containerMiddleware: asValue(scopePerRequest(container))`)

**Comment by jeffijoe** [comment]
Your problem is actually related to your use of `this`:

Your `this` refers to whatever `this` is in the innermost `function`, which is no longer your class instance. Test this by `console.log(this)`.

```js
return new Promise(function (resolve, reject) {
```

And here

```js
.init(config, function () {
```

If you make them arrow functions, it should work:

```js
module.exports = class Hydra {
  constructor(opts) {
    this.config = require("./config").HYDRA;
    this.umfHandler = umfHandler; // Resolve handler successfully
  }

  initialize() {
    return new Promise((resolve, reject) => {
      hydra
        .init(config, () => {
          hydra.registerRoutes(routerConfig);
          hydra.getHydra().on("message", message => {
            this.umfHandler(message); // Undefined
          });
        })
        .then(function() {
          resolve(hydra);
        })
        .catch(function(err) {
          reject(err);
        });
    });
  }
};
```

Since you register `umfHandler` as `SINGLETON`, resolving per event will have no effect. 😄

**Comment by huyaloha** [comment]
Thanks for your help, it works.

**Comment by huyaloha** [comment]
Hi @jeffijoe one more thing, Is it possible to pass the message into function and I still can resolve the related services to do some other businesses.

for example
```
module.exports = ({message, customerService, notificationService}) => {
  switch (message.typ) {
    case MAIL:
      notificationService(message);
      break;
    case CUSTOMER:
      customerService(message);
      break;
    default:
      logger.debug('Not support message type');
  }
};

// Assume all services have been registered in container.js

**Comment by jeffijoe** [comment]
I suggest making it a factory function.

```js
module.exports = ({ customerService, notificationService}) => (message) => {
  switch (message.typ) {
    case MAIL:
      notificationService(message);
      break;
    case CUSTOMER:
      customerService(message);
      break;
    default:
      logger.debug('Not support message type');
  }
};
```

**Comment by huyaloha** [comment]
Thanks, @jeffijoe. Factory function is great. I have just started developing with Javascript/NodeJs last 3 weeks and it's the first time using factory function.

**Comment by jeffijoe** [comment]
Happy to help!
