### ISSUE TITLE
loadModules function doesn't work with relative paths like '../src/lib'

### ISSUE THREAD

**Issue by joeltello** [jeffijoe/awilix#8]
This is my project's structure:

```
project
│
└───bin
│   │   dependencies.js
│   │   server.js
│   
└───src
│   │
│   └───services
│   │   │   user.js
│   │   │   ...
│   │
│   └───lib
│       │   response-handlers.js
│       │   ...
```

inside `bin/dependencies.js` I'm trying to load my js files from services and lib:
```
container.loadModules([
    '../src/lib/*.js',
    '../src/services/*.js'
  ])
```

When I try to resolve the functions from those modules I get the following error:
```
AwilixResolutionError: Could not resolve 'sendValidResponse'
```

**Comment by joeltello** [comment]
does `opts.cwd` have something to do with this?

**Comment by jeffijoe** [comment]
Yes, The default is the current working dir (usually where your package.json is), because Node wont tell us the dir of the file unless you explicitly do so with '__dirname' which you may pass to opts.cwd 😀

**Comment by joeltello** [comment]
I just changed cwd to __dirname, but didn't help, I still get the same error.

**Comment by jeffijoe** [comment]
Could I see the contents of the file that contains the function you want to register?

**Comment by jeffijoe** [comment]
Here's a working project boilerplate using `loadModules`: https://github.com/jeffijoe/koa-es7-boilerplate/blob/master/src/lib/configureContainer.js

**Comment by joeltello** [comment]
Thank you so much. So it was a combination of `export default` and file name with dashes!

**Comment by jeffijoe** [comment]
Yeah thats what I was thinking - I've personally noticed more people naming their files after their default export, which is why that is the default convention in Awilix.

If you want to continue using filenames with dashes, you can specify `opts.formatName: 'camelCase'` for `loadModules` - it will use the [`camel-case`](https://github.com/blakeembrey/camel-case) module to convert your dashed version to camel case. 😄

**Comment by joeltello** [comment]
the file name is not an issue, this is what I am doing:
```
const { sendValidResponse, sendErrorResponse } = container.resolve('response-handlers')
```

**Comment by jeffijoe** [comment]
Right - I'm guessing you just found out that only the default export is registered. 😄 

The reason for this is that I don't want to register any other exported members since they are likely just going to pollute the container.

Also, please keep in mind you don't have to use `loadModules` - the following is perfectly acceptable as well:

```js
// response-handlers
export function sendValidResponse ({ db }) {
  return async (req, res) => {
    res.status(200).send(await db.get('something'))
  }
}

// dependencies.js
import * as handlers from '../src/response-handlers'
import mapValues from 'lodash/mapValues'

const container = createContainer()
  .registerFunction(
    // Map to scoped registration
    mapValues(handlers, (handler) => [handler, Lifetime.SCOPED])
  )
```

Basically using `lodash/mapValues` to register all handlers with scoped lifetime.

**Comment by joeltello** [comment]
yes, I was using that version of the code before, but wanted to take advantage of passing the modules as arguments from this [example:](https://github.com/jeffijoe/awilix/blob/master/examples/simple/services/functionalService.js)

```
export default function (opts) {
  return {
    getUser: getUser.bind(null, opts),
  }
}

```

**Comment by joeltello** [comment]
what would happen if I do something like this:
```
container.loadModules([
  '../src/lib/user.js',
  '../src/services/user.js'
])
```
will the second user.js overwrite the first?

**Comment by jeffijoe** [comment]
That one was the earliest pattern and was more or less converted from awilix v1 to v2, but I recommend using this instead (it's less confusing IMO)

```js
export default function makeUserService ({ someService }) {
  return {
    getUser: () => someService.doStuff()
  }
}
```

**Comment by jeffijoe** [comment]
Yes, the last one registered wins.

**Comment by jeffijoe** [comment]
You can use this to your advantage with scoping! E.g. register a default `logger`, but overwrite it with a scoped version that also collects request and user info. 😎
