### ISSUE TITLE
Single Instance Container

### ISSUE THREAD

**Issue by faustbrian** [jeffijoe/awilix#81]
Hey, just found Awilix and looks great but I am wondering one thing. Is there a recommended way to instantiate the container object and pass it around between files?

I was thinking of doing something like the following to be able to do `const cont = require('root/container')` from any file and always receive the same container instance but was wondering if there is a recommended way of doing it without having a wrapper singleton like in my example.

```js
const awilix = require('awilix')

let instance = null

module.exports = class Container {
  constructor () {
    if (!instance) {
      instance = this

      this.awilix = awilix.createContainer()
    }

    return instance
  }

  register (opts) {
    this.awilix.register(opts)
  }

  resolve (dep) {
    return this.awilix.resolve(dep)
  }
}
```

**Comment by jeffijoe** [comment]
Why not just do this?

```js
module.exports = createContainer()
```

Why do you want to do this though? You should instantiate the container in the context of the app you're making; for example a HTTP server you would instantiate it when creating the server.

The majority of your code should not know about Awilix at all though, so why do you want to import the container so many places? 😄

**Comment by faustbrian** [comment]
There are a few places where things need to be manually resolved so I would need to be able to have access to the initial container instance from anywhere.

**Comment by jeffijoe** [comment]
If you are using scopes then that is not a good idea. I suggest you do the following:

```js
const container = createContainer()
container.register({ container: (c) => c })
```

This will give you the correct container when being injected to a class/function, for example:

```js
class MyClass {
  constructor({ container }) {
    this.container = container
  }
}
```

**Comment by faustbrian** [comment]
This is what I was initially testing and works for most cases but the issue is that there are a few spots where my only way of getting something out of the container is to manually call `resolve` because they are methods like `module.exports = async () => {}` which are executed by 3rd-party packages/workers.

**Comment by jeffijoe** [comment]
Ah, so something like Lambda/CloudFunctions? If thats the case then you wouldn't have to use a singleton.

I always have a `container.js` that looks something like:

```js
import { createContainer } from 'awilix'

export function configureContainer() {
  return createContainer()
    .register({ ... })
}
```

Anyway, it's completely up to you 😄

**Comment by faustbrian** [comment]
So I should be able to do this and the `require` cache of node.js would keep the first container instance right for any subsequent `require` statements?

*container.js*
```js
const { createContainer } = require('awilix')

module.exports = createContainer()
```

*first-module*
```js
const container = require('app/container')
container.resolve('db')
```

*second-module*
```js
const container = require('app/container')
container.resolve('db') // same instance as first-module
```

**Comment by jeffijoe** [comment]
That is correct. :)

**Comment by faustbrian** [comment]
Looks like that works everywhere except in `module.exports = () => {}` which is executed by a web worker where it instantiates a new instance of the container instead of giving me the existing one.

**Comment by jeffijoe** [comment]
That's because web workers have a completely different context; you can't share instances of anything between web workers and the main JS thread.

**Comment by faustbrian** [comment]
Yeah, I was hoping there would be some way to use the container there. Guess I will create a fresh instance of the container inside those.

Thanks for the help!
