### ISSUE TITLE
Lazy vs Eager initialisation

### ISSUE THREAD

**Issue by jleskovar** [jeffijoe/awilix#82]
Hey there,

Great library. Is there any thought around allowing classes to register themselves as being eagerly initialised - i.e. resolver is invoked without having to explicitly call container.resolve(). My use case is I have an exported singleton class A, which wants to bind to a singleton EventEmitter in its constructor:

```
export default class A {
  constructor({ eventBus }) {
    eventBus.on('OnServerStarted', () => console.log('started'))
  }
}
```

A won't be instantiated until we do a container.resolve() for A. It would be great if there was a mechanism for declaring that A should be instantiated as soon as possible, without having to container.resolve() it explicitly in my application's entry point, only to discard the value.

Perhaps something like the following

```
export default class AwesomeService {
  constructor(awesomeRepository) {
    this.awesomeRepository = awesomeRepository
  }
}

AwesomeService[RESOLVER] = {
  injectionMode: InjectionMode.CLASSIC,
  initialisationMode: InitMode.EAGER
}
```

**Comment by jeffijoe** [comment]
The issue with that would be that you don’t know when you can safely resolve it (you might not have registered its’ dependencies yet) so resolving upon registration would not work.

To be honest I think this is better handled in userland code as only the user knows when the time is right to resolve.

Do you have a lot of services to do this for using autoloading? Assuming you use autoloading given your example of using the inline config approach.

I think using `container.resolve` in the entrypoint is fine for this particular use case. If you don’t intend to inject the subscriber (`A`) anywhere, you can skip registering it and use `container.build`. 😀

**Comment by jleskovar** [comment]
You're right that there's no easy for the kernel to know when's the right time to resolve. I didn't know about container.build() though, sounds like I can use that. Not using Autoloading, was just copying the example from the readme :)

**Comment by jeffijoe** [comment]
Ah, gotcha 😄

I’m going to close for now as it’s simply not possible to know when we should resolve. If you (or anyone else) come up with some ideas I can always reopen. 😀
