### ISSUE TITLE
Multiple registrations and resolveAll support

### ISSUE THREAD

**Issue by x3mka** [jeffijoe/awilix#86]
Hello, 

Are there any plans to support registering multiple services and resolveAll for them?
For example:
container.register(key, service) - default registration, as is now
container.register(key, service, name) -  named registration

container.resolve(key) - returns default registration
container.resolveAll(key) - returns array or some collection of all key service registrations.

Thanks.

**Comment by jeffijoe** [comment]
Please check #80 - I think thats what you are after. If thats not the case please let me know your specific use case and I’ll reopen if applicable. 😀

**Comment by x3mka** [comment]
I looks like it's not the same. The main difference is in separate calls to .register
Imagine some plugin system, when we pass a container to a configuration function. For example, plugins can provide service functions for react routing:

function configure(container) {
  container.register(routeProvider: thisPluginRouteProvider)
}

Once all plugins configured I want to build router by iterating over all plugins route providers:
container.resolveAll(routeProvider)

I am from .NET world and it's pretty common functionality for containers of different IoC solutions.
As I understand your code, it's not possible to add this with just a custom resolver. It's about a concept of default and named registrations.

**Comment by jeffijoe** [comment]
I see. I know in Unity you can register multiple implementations of the same interface, but the reason that works is because in .NET you have reflection and interfaces are actually runtime types, whereas in JS we don't have that, which is why the `name` part in `register(name, resolver)` is needed.

Awilx' scope feature requires that names be unique, as this is how we can overwrite registrations on the scope level, so I'm afraid your proposed API is not going to work.

However I think your use case can be solved using the solution from #80 :)

Firstly, you should probably limit the exposure of the container itself to the plugin system. I suggest you write your plugin system in a way that does not directly reference the container.

Example:

```js
class RouteProvider1 { /*...*/ }

class RouteProvider2 { /*...*/ }

// No references to container!
function configure() {
  return {
    routeProviders: [
      RouteProvider1,
      RouteProvider2
    ]
  }
}


// In your route creation...
function createRouter(container) {
  const result = configure()
  const routeProviders = result.routeProviders.map(
    Class => container.build(Class)
  )
}
```

Does this help?

**Comment by x3mka** [comment]
Thanks. I have already some workarounds for my plugin system. 

But just to clarify :) 
I meant name for a specific registration. Example: 
container.register(name, resolver, registrationName = 'default')

I can give you another example when it could be convenient. 
container.register(logger, LocalLogger) - default one, the same as container.register(logger, LocalLogger, 'default')
container.register(logger, ExternalLogger, 'external') - named one

Depending on an app setting 'logger_type' you can get:
container.resolve(logger, logger_type)

And to build drop down items for mentioned logger type setting you need all available logger registrations: container.resolveAll(logger)

If you think it's valuable I can work on a pull request when having free time.

**Comment by jeffijoe** [comment]
Given you need to use `resolveAll` in your own code, I don't think it's a good fit as that kinda goes against the idea of IoC in my opinion.

I think this is something best solved on a case by case basis in userland code. 😄

**Comment by MeirionHughes** [comment]
Its a shame this isn't available; it was a common pattern with a few DI containers I've used in C#, its also available on inversify. The real power of this feature is when you use a modular application structure, where each module configures itself. Or adds extra "Providers" etc. 

just did a quick work around, which seems to work: 

```ts
import * as awilix from 'awilix';
import {AwilixContainer, Resolver} from 'awilix';

class ModuleA { constructor() { } }
class ModuleB { constructor() { } }

let container = awilix.createContainer();

function asAliasArray<T = any>(alias: string | symbol) {
  return {
    resolve: (container: AwilixContainer) => {
      let list: Resolver<T>[] = container.resolve(alias);
      return list.map(r => container.build(r))
    }
  }
}

container.register("modulesList", awilix.asValue([]));
container.register("modules", asAliasArray("modulesList"));

container.resolve<Resolver<any>[]>("modulesList")
  .push(awilix.asClass(ModuleA));

container.resolve<Resolver<any>[]>("modulesList")
  .push(awilix.asClass(ModuleA));

console.log(container.resolve("modules"));
```

**Comment by jeffijoe** [comment]
@MeirionHughes the reason Inversify can do it is because they rely on the use of Symbols (IIRC) whereas Awilix does not in order to avoid littering your code with DI-specific annotations.

Awilix' Resolver API was built with composition in mind, so you can pretty much build whatever specific things you need on top of it, as you just did right there. Nice job! 😄

**Comment by MeirionHughes** [comment]
Well the problem with doing this in user-land is, as far as I can see, it requires performing a resolution of a cache object, during the configuration / pre-build stage, _which I consider to be bad-practice_.

I had another stab as making this a little easier for me to use: 

```ts
  container.registerAdd = function <T>(name: string | symbol, registration: Resolver<T>) {
    let storeKey = typeof (name) === "string" ? name + "_STORE" : Symbol.for(name.toString() + "_STORE");

    if (this.registrations[storeKey] === undefined) {
      this.register(storeKey, asValue([]));
    }
    let store = this.resolve(storeKey);
    console.log(store);
    if (this.registrations[name] === undefined) {
      this.register(name, asArray(store));
    }
    store.unshift(registration);

    return this;
  }.bind(container);
```
then to configure: 

```ts
container.registerAdd("IPresentableTraceProvider[]", asClass(CurveTracePresenterProvider));
container.registerAdd("IPresentableTraceProvider[]", asClass(ReferenceTracePresenterProvider));
```
Its important to stress here that the whole point in doing this is that this allows you to register things like "providers" across multiple configuration points, in a dynamic non-fixed fashion. 

anyway, this works fine - I suspect it would fall apart if you combined containers/modules though.
