### ISSUE TITLE
this is undefined in class es6

### ISSUE THREAD

**Issue by Milambeer** [jeffijoe/awilix#88]
I, i am trying to add a class in my container, but i can not retrieve data from this because it says it's undefined

The container:
```
container.register({
  // Controller injection
  postService: awilix.asFunction(postService),
  postController: awilix.asClass(postController),
})
```

The controller:
```
class PostController {
  constructor({ postService }) {
    this.postService = postService
  }

  getPosts(ctx, next) {
   this.postService.something() // ==> this undefined
 }
}
```

Thanks for help!

**Comment by jeffijoe** [comment]
What exactly is undefined? `this`? `this.postService`? Or `this.postService.something`?

How are you calling `getPosts`? Using `awilix-koa`?

In your container, what is `postService`?

**Comment by Milambeer** [comment]
```this``` is undenfined.

I am calling getPosts like that
```
const Router = require('koa-router')

const makeRouter = ({ postController }) => {
  const router = new Router()
  const BASE_URL = `/posts`

  router.get(`${BASE_URL}`, postController.getPosts)
  return router
}

module.exports = makeRouter
```

postService is just an example function. 

Thanks

**Comment by jeffijoe** [comment]
This is not a problem with Awilix, but a problem with your `this` binding. :)


```
router.get(`${BASE_URL}`, postController.getPosts.bind(postController))
```

I would suggest using `awilix-koa` as it manages all the router plumbing for you. :)

**Comment by Milambeer** [comment]
Ok thanks will check on this:p
