### ISSUE TITLE
Additional TypeScript example using loadModules

### ISSUE THREAD

**Issue by KATT** [jeffijoe/awilix#89]
Excuse me to open this as an issue, as it's more of question/discussion.

I did a little example on how to put together dynamically `loadModules` and using TypeScript to my preferred style of defining my modules.

1. Can you give me some feedback?
2. Would you want me to do a PR with a similar setup?

https://github.com/KATT/awilix-typescript-dependency-injection

**Comment by jeffijoe** [comment]
No problem, happy to provide feedback. 😄

* I like that you define the `ICradle`, however you should avoid importing/passing around the cradle manually. For example, when using scopes, the cradle is a different instance. When bootstrapping (building/resolving the application root), you can use `container.build`. 😄
* I've noticed TypeScript users prefer using function parameters (`InjectionMode.CLASSIC`) rather than a cradle object with Awilix, as it avoids having to specify all properties on the cradle interface when mocking.

You nailed it by having all your components in a `lib` folder! But by doing `import { ICradle } from '../cradle'` inside the aggregate you are (loosely) referencing how the container internals work. This is why I also personally use Classic injection for TypeScript.

In case you haven't looked at classic injection yet, [check it out in the docs](https://github.com/jeffijoe/awilix#injection-modes). 😄

**Comment by KATT** [comment]
Thanks for the feedback! I'll have a think if I should consider using `class`es. :)

**Comment by jeffijoe** [comment]
Classic injection does not mandate the use of classes, the "Classic" part refers to using parameters for injecting rather than an "options object", so you can keep using functions (which I also do). 😄

**Comment by jeffijoe** [comment]
Meaning, instead of doing

```ts
function createService({ cat, dog }: { cat: ICat, dog: IDog }) {}
```

You do

```ts
function createService(cat: ICat, dog: IDog) {}
```

**Comment by KATT** [comment]
Sorcery! I will have a play when I'm back at a 🖥

**Comment by KATT** [comment]
I did it as you suggested https://github.com/KATT/awilix-typescript-dependency-injection/commit/b7ee85580b0b28ce6792133fe4cf24a81e2f1140

It works well. Nice. I like only typecasting the entry point module when starting the app.

Still feels odd with the arguments being parsed.. a bit too magical for my liking, and I like options object over argument lists... but you're right, it's a bit smelly to define + pass the `ICradle` around too. 

Another way would be this. Might prefer that over the others: https://github.com/KATT/awilix-typescript-dependency-injection/commit/3fda04c06d6b1b53672f8f4121f4c6eadc0983f0

In terms of performance I always want `Lifetime.SINGLETON`, so it shouldn't really impact? 

And mocks you gotta mock anyway!

Sorry if I'm a pain, I'm thinking out loud. :)

**Comment by jeffijoe** [comment]
Honestly you can do it however you'd like. 😄

I used to prefer the options object (which was the reason I created Awilix using Proxies to begin with), however the problem with incorrect parameter passing goes away with TypeScript, and so I've started preferring the classic approach personally. Doesn't hurt that it's faster, too, hehe.

About `Lifetime.SINGLETON`, yes, using singletons—especially when resolving often—is better for performance, however Awilix' real power is its' scoping feature, which comes in handy when you're dealing with state that must be isolated, such as for an HTTP request, or an open socket connection. 

If you are only resolving the root object/aggregate and thats it, then technically you only have a single scope for your entire process, meaning that if you used `Lifetime.SCOPED` you would get the same behavior as when using `Lifetime.SINGLETON`. 😉

**Comment by KATT** [comment]
Yeah, I use scopes to separate each section of my app, but they also register everything as `SINGLETON`s in their scopes! 

I switched to singletons when I had a module fetches and automatically updating an API token when needed, but I only want it to do it once (the module exposes a `async fetch()` that "eventually" resolves to the token. Noticed it was doing the request several times when I expected it to only happen once because it was used by several other modules.

Haven't used awilix to deal with state (yet) as haven't had use of it. The biggest app I'm using it for is running Apollo Server so all "state" specific to a request is stored in [`context`](https://www.apollographql.com/docs/link/overview.html#context) and passed to my GraphQL-resolvers through that.

**Comment by KATT** [comment]
Yes, that is some straight out 🦄shit, haha

**Comment by jeffijoe** [comment]
`SINGLETON` registrations will always cache in the root container, so I think you are using scopes incorrectly; scopes are not intended to separate domains, but to separate state.

Your API token fetcher is a good use case for `SINGLETON`, so register it as such in the root container.

Your `context` in ApolloServer is more or less the same as the `req` (Express) or `ctx` (Koa), what I like to do is use a middleware that creates a scope, then register interesting values from the context in the scope which can then be injected to the service layer, all without the service layer knowing anything about the transport (ApolloServer, Express, Koa).

```js
// Koa
app.use(scopePerRequest(container))
app.use((ctx, next) => {
  const scope = ctx.state.container
  scope.register({ user: ctx.state.user })
  return next()
})

router.get('/api/todos', inject(
  todoService => 
    async (ctx, next) => 
      ctx.body = await todoService.find()
))

function createTodoService(user) {
  return {
    find() {
      // find todos using user.id
    }
  }
}
```

**Comment by KATT** [comment]
> `SINGLETON` registrations will always cache in the root container, so I think you are using scopes incorrectly; scopes are not intended to separate domains, but to separate state.

Well, they work perfectly for separating domains too! 

However, if they're registered in the root container, that's a potential problem for name collisions.. surprised I haven't noticed that being a problem for me yet. 🤔 

> Your `context` in ApolloServer is more or less the same as the req (Express) or ctx (Koa), what I like to do is use a middleware that creates a scope, then register interesting values from the context in the scope which can then be injected to the service layer, all without the service layer knowing anything about the transport (ApolloServer, Express, Koa).

I get that.. but in Apollo Server the `context` object is actually intended to be used for this, it's not like the classical approach of mutating the `req`-object in express which I agree is really 😷 

However, I might have a look at it and see if it makes it more elegant, sounds like I might be missing some juice indeed!

**Comment by jeffijoe** [comment]
ApolloServer is just the transport, your services should not care. ;)

> However, if they're registered in the root container, that's a potential problem for name collisions.. surprised I haven't noticed that being a problem for me yet.

You can register it in the scoped container, but it will be cached in the root container, so if you have name collisions across scopes then the first-resolved value is used. So.. don't use it for separating domains 😄

**Comment by chrisandrews7** [comment]
How would you recommend separating domains that use autoloading?

In an example like this, when trying to give all the main container dependencies and just the domain specific modules to just the index file. How would you avoid collisions?
```js
mainContainer.register(
  ['domainA', 'domainB'].reduce((domains, domain) => {
    const scope = mainContainer
      .createScope()
      .loadModules(`domains/${domain}/**/!(*.spec).js`, { cwd: __dirname });

    return {
      ...domains,
      [domain]: asValue(scope.cradle.index),
    };
  }, {}),
);```

**Comment by KATT** [comment]
> I wouldn't ever introduce naming collisions in the first place, nor separate domains like that (I use microservices). 😄

In my case I am making a GraphQL API Gateway and each scoped domain represents a microservice basically.

> Howerver, you can use _[..]_

Brilliant. I will refactor to this structure.

**Comment by KATT** [comment]
.. didn't work. Singleton is not respected when same module again, it's "singleton" per container

**Comment by jeffijoe** [comment]
Singletons are cached in the root container. Could you share your code and what is not behaving as expected? Need more details. 😀

**Comment by KATT** [comment]
My container has gotten a bit convoluted, but I'm achieving what I want... I'll give an overview and share some code.

- I have several `domains`
- Domains can expose `models` through their `index.js`-file
- I register domains' models to the global scope
- Domains can therefore use other domains' models and communicate with each other.

My main `container.js` is something like this:

```js
const container = createContainer();

// [..]

container
  .loadModules(`${__dirname}/lib/**/!(*.spec).js`, {
    resolverOptions: {
      lifetime: Lifetime.SINGLETON,
    },
  });

// dynamically load domains
const { getModulesInDir } = container.cradle;
const models = createContainer();

const domainNames = getModulesInDir(`${__dirname}/domains`);

const domains = {};
container.register({
  domains: asValue(domains),
  models: asValue(models.cradle),
});

domainNames.forEach(name => {
  const domainContainer = createContainer();

  _.forEach(container.registrations, (value, key) => {
    domainContainer.register({
      [key]: asValue(container.cradle[key]),
    });
  });

  domainContainer.loadModules(`${__dirname}/graphql/${name}/**/!(*.spec).js`);

  domains[name] = domainContainer.cradle.index;
}, {});

// register domains' models in global container
domainNames.forEach(name => {
  const domain = container.cradle.domains[name];

  _.forEach(domain.models || {}, (value, key) => {
    if (models.registrations[key]) {
      throw new Error(
        `Could not register model '${key}' from domain ${name} - key already in use in models container.`,
      );
    }
    models.register(key, asValue(value));
  });
});

module.exports = container.cradle;
```

Not very pretty, but it works.. it's definitely not awilix fault it's convoluted. I should be able to find a neater solution to my problem.

**Comment by jeffijoe** [comment]
I'd love to help more but I simply don't understand the use case. 😅
