### ISSUE TITLE
resolve dependencies

### ISSUE THREAD

**Issue by Crizstian** [jeffijoe/awilix#9]
Hey, good library

i want to know if there is an option or how can i resolve multiple dependencies in one call ?

example:
`
const {deps1, deps2, deps3} = container.resolve('deps1', 'deps2', 'deps3')
`

**Comment by jeffijoe** [comment]
The `cradle` is the proxy that triggers resolution, so:

```
const { dep1, dep2, dep3 } = container.cradle
```

**Comment by Crizstian** [comment]
This have worked thanks
