### ISSUE TITLE
Cyclic dependencies detected

### ISSUE THREAD

**Issue by farhantahir** [jeffijoe/awilix#94]
```
AwilixResolutionError: Could not resolve 'user'. Cyclic dependencies detected.
Resolution path: registerationService -> userRepository -> user -> user
```

User.js

```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const userSchema = new Schema({
  name: String,
  email: String,
  password: String
});

class UserClass {
  
}

userSchema.loadClass(UserClass);

module.exports = mongoose.model('Users', userSchema);


```
UserRepository.js

```
const BaseRepository = require('./BaseRepository');

class UserRepository extends BaseRepository {
  constructor({ user }) {
    this.model = user;
  }
  
  find(filters = {}) {
    return this.model.find(filters);
  }
}

module.exports = UserRepository;
```
RegisterationService.js

```
class RegisterationService {
  constructor({userRepository}) {
    this.userRepository = userRepository;
  }

  signUp() {
  // testing it out
    return new Promise((res, rej) => {
      setTimeout(() => res(), 1000);
    });
  }
}

module.exports = RegisterationService;
```

**Comment by jeffijoe** [comment]
User is a class and Awilix is trying to instantiate it which is not what you want. You should register your models as values.

**Comment by farhantahir** [comment]
@jeffijoe damn I jest read that thing in docs.
```
// We can tell Awilix what to register everything as,
// instead of guessing. If omitted, will inspect the
 // module to determine what to register as.
```

:smile:

**Comment by jeffijoe** [comment]
I would recommend the function wrapping approach though. You won't have any performance issues because you are using singleton. 😄

**Comment by jeffijoe** [comment]
@farhantahir did this solve your problem?

**Comment by farhantahir** [comment]
@jeffijoe no still getting the following 

```
 Could not resolve 'user'. Cyclic dependencies detected.

Resolution path: registerationService -> userRepository -> user -> user

```

**Comment by jeffijoe** [comment]
Did you make the change I suggested?

**Comment by farhantahir** [comment]
yes I did made the change.

**Comment by jeffijoe** [comment]
If `module.exports = () => mongoose.model('Users', userSchema);` is there, it should work. Do you have a repo I can look at?

**Comment by farhantahir** [comment]
@jeffijoe Yeah its working now. I had put that in wrong file. Thanks a lot. 

Just one last question. As for express we have to require models in mostly like `app.js`. Then with this I have to always do `require('./User.js')();`. Is there any workaround instead of exporting function. 

Thanks a lot for the help and quick response.

**Comment by jeffijoe** [comment]
You can register your modules manually. Only `loadModules` prescribes the use of  `module.exports =` / `export default`.

**Comment by jeffijoe** [comment]
If you want to avoid the `() => mongoose.model` approach, use a separate `loadModules` where you set `register` to `asValue`.

**Comment by farhantahir** [comment]
For some reason in case I have to do manual require, though as We are using IoC and DI then that shouldn't be a case. But Thanks a lot. Instead of exporting model in wrapped function I used another `loadModules()` to load all models with `asValue`.

Thanks.

**Comment by farhantahir** [comment]
Final `IoC.js` a IoC configuration file. 

```
const awilix = require('awilix')
const Lifetime = awilix.Lifetime
const container = awilix.createContainer()

container.loadModules(
  [  
    'src/services/**/*.js',
    'src/repositories/**/*.js'    
  ],
  {
    cwd: __dirname,
    formatName: 'camelCase',
    resolverOptions: {
      lifetime: Lifetime.SINGLETON
    }
  }
);

container.loadModules(
  [  
    'src/models/**/*.js'    
  ],
  {
    cwd: __dirname,
    formatName: 'camelCase',
    resolverOptions: {
      lifetime: Lifetime.SINGLETON,
      register: awilix.asValue
    }
  }
);

module.exports = container;
```

**Comment by jeffijoe** [comment]
No problem, glad you figured it out. 😄

**Comment by farhantahir** [comment]
hahaha @jeffijoe Thanks for it. My file is cleaner now. :smiley:
