### ISSUE TITLE
[Question] How can I resolve an object asValue being exported. 

### ISSUE THREAD

**Issue by farhantahir** [jeffijoe/awilix#97]

**Comment by farhantahir** [comment]
I have a created a `Helper.js` as follow, Planned to contain reusable helper methods in this file and export these methods.

```
const jwt = require('jsonwebtoken');
const config = require('config');

function generateJWT(payload) {
  return jwt.sign({ ...payload }, config.SECRET_KEY);
}

module.exports = {
  generateJWT
};
```

Now I want this helpers to get resolved in class constructor as follow: 

```
constructor({helpers}) {
  this.helpers = helpers;
}
```

**Comment by farhantahir** [comment]
@jeffijoe I am sorry I had a typo in `module.exports` 

It should have been like below:
```
module.exports = () => ({
  generateJWT
});
```
not

```
module.exports = {
  generateJWT
};

Classic mistake happens with arrow function :p
```

**Comment by jeffijoe** [comment]
No problem, closing 😀

**Comment by farhantahir** [comment]
@jeffijoe 

Just confirm one thing, I have registered it to resolve asFunction, is it right or it could be done in better way ?

**Comment by jeffijoe** [comment]
That's up to you. If you don't want to use the arrow function you can use asValue.

**Comment by farhantahir** [comment]
Actually I tried that already :smile: and it gives following error:

```
{
    "error": "AwilixResolutionError: Could not resolve 'helpers'.\n\nResolution path: helpers"
}
```
With the following
```
module.exports = {
  generateJWT
};
```
`asValue` works fine with arrow function version.
