### ISSUE TITLE
Glob options

### ISSUE THREAD

**Issue by skbolton** [jeffijoe/awilix#99]
Thanks for the awesome library!

Looking into the code a little bit I think this isn't possible but I would like to run it by you. I need to load all modules in `./src/app/commands/**/*.js` besides `./src/app/commands/**/event.js`. I couldn't see a way to pass in the globs in a way to `!` commands with glob. This obviously doesn't work

```
container.loadModules([
  './src/app/commands/**/*.js',
  '!./src/app/commands/**/event.js'
])
```

Do you know of a way to do this?

**Comment by jeffijoe** [comment]
Each entry in the array results in a single glob call. You would need to do whatever filtering you need to do in that single glob expression.

Does that make sense? 😀

**Comment by skbolton** [comment]
Yeah I will change my folder structure or load them manually
